export const allSkills = new Map ([
    // ALL WEAPONS-----------------------------------------------------------------------------------

    ['Whirlwind', {name: 'Whirlwind', buffs: ['Bulwark', 'Finesse'], types: ['Swing'], allTypes: ['Swing', 'Area', 'Physical']}],
    ['Throw Axe', {name: 'Throw Axe', buffs: ['Finesse'], traits: ['Piercing'], types: ['Swing'], allTypes: ['Swing', 'Missile', 'Frontal', 'Physical']}],
    ['Shockwave', {name: 'Shockwave', buffs: ['Colossal', 'Resilience'], types: ['Earth'], allTypes: ['Earth', 'Area', 'Frontal', 'Burst', 'Physical']}],
    ['Demolish', {name: 'Demolish', buffs: ['Colossal'], traits: ['Brutal'], types: ['Earth'], allTypes: ['Earth', 'Missile', 'Burst', 'Physical']}],
    ['Thundering Slash', {name: 'Thundering Slash', buffs: ['Electrified'], debuffDep: ['Dazed'], types: ['Electric', 'Swing'], allTypes: ['Electric', 'Swing', 'Frontal', 'Physical']}],
    ['Thunder Clap', {name: 'Thunder Clap', buffs: ['Electrified', 'Prowess'], traits: ['Brutal'], types: ['Electric', 'Slam'], allTypes: ['Electric', 'Slam', 'Frontal', 'Physical']}],
    ['Heavy Strike', {name: 'Heavy Strike', buffs: ['Prowess', 'Resilience'], debuffs: ['Bleed'], types: ['Slam'], allTypes: ['Slam', 'Frontal', 'Physical']}],
    ['Ground Slam', {name: 'Ground Slam', buffs: ['Prowess'], debuffDep: ['Bleed'], types: ['Slam'], allTypes: ['Slam', 'Area', 'Burst', 'Physical']}],
    ['Flesh Impale', {name: 'Flesh Impale', buffs: ['Form'], debuffs: ['Exposed'], types: ['Thrust'], allTypes: ['Thrust', 'Frontal', 'Physical']}],
    ['Battle Shout', {name: 'Battle Shout', buffs: ['Form'], debuffDep: ['Exposed'], types: ['Thrust'], allTypes: ['Thrust', 'Area', 'Burst', 'Physical']}],

    ['Fire Slash', {name: 'Fire Slash', buffs: ['Haste'], debuffs: ['Burn'], types: ['Fire'], allTypes: ['Fire', 'Missile', 'Frontal', 'Magical']}],
    ['Fire Walk', {name: 'Fire Walk', debuffs: ['Burn'], types: ['Fire'], allTypes: ['Fire', 'Lasting', 'Area', 'Magical']}],
    ['Lightning Field', {name: 'Lightning Field', buffs: ['Electrified'], debuffs: ['Dazed'], types: ['Electric'], allTypes: ['Electric', 'Lasting', 'Aura', 'Magical']}],
    ['Overcharged Blast', {name: 'Overcharged Blast', buffs: ['Electrified'], debuffDep: ['Dazed'], types: ['Electric', 'Blast'], allTypes: ['Electric', 'Blast', 'Area', 'Frontal', 'Magical']}],
    ['Chaotic Inferno', {name: 'Chaotic Inferno', debuffs: ['Disarray'], types: ['Chaos'], allTypes: ['Chaos', 'Lasting', 'Frontal', 'Magical']}],
    ['Chaos Eruption', {name: 'Chaos Eruption', traits: ['Chaotic'], debuffDep: ['Burn'], types: ['Chaos'], allTypes: ['Chaos', 'Missile', 'Frontal', 'Burst', 'Physical']}],
    ['Dark Swarm', {name: 'Dark Swarm', debuffs: ['Disoriented', 'Doom'], types: ['Shadow'], allTypes: ['Shadow', 'Nissile', 'Frontal', 'Magical']}],
    ['Gathering Shadows', {name: 'Gathering Shadows', debuffs: ['Doom'], types: ['Shadow'], allTypes: ['Shadow', 'Area', 'Magical']}],
    ['Runic Ember', {name: 'Runic Ember', buffs: ['Radiance'], debuffs: ['Fragility'], debuffDep: ['Fragility'], types: ['Arcane'], allTypes: ['Arcane', 'Missile', 'Frontal', 'Magical']}],
    ['Arcane Storm', {name: 'Arcane Storm', buffs: ['Radiance'], debuffs: ['Fragility'], types: ['Arcane'], allTypes: ['Arcane', 'Lasting', 'Area', 'Magical']}],

    ['Mortar Shot', {name: 'Mortar Shot', debuffs: ['Bleed'], types: ['Bomb'], allTypes: ['Bomb', 'Area', 'Frontal', 'Burst', 'Physical']}],
    ['Bombardment', {name: 'Bombardment', debuffs: ['Bleed'], types: ['Bomb'], allTypes: ['Bomb', 'Area', 'Burst', 'Physical']}],
    ['Buckshot', {name: 'Buckshot', buffs: ['Ammunition'], traits: ['Brutal'], types: ['Blast'], allTypes: ['Blast', 'Frontal', 'Burst', 'Physical']}],
    ['Power Blast', {name: 'Power Blast', buffs: ['Ammunition'], traits: ['Devastating'], types: ['Blast'], allTypes: ['Blast', 'Frontal', 'Burst', 'Physical']}],
    ['Pesticide Burst', {name: 'Pesticide Burst', debuffs: ['Poison'], types: ['Nature'], allTypes: ['Nature', 'Lasting', 'Frontal', 'Magical']}],
    ['Threshing Blast', {name: 'Threshing Blast', buffs: ['Ammunition'], debuffDep: ['Poison'], types: ['Nature'], allTypes: ['Nature', 'Frontal', 'Burst', 'Physical']}],
    ['Bolt Barrage', {name: 'Bolt Barrage', buffs: ['Aptitude'], types: ['Projectile'], allTypes: ['Projectile', 'Missile', 'Frontal', 'Burst', 'Physical']}],
    ['Cyclone Shot', {name: 'Cyclone Shot', buffs: ['Aptitude'], types: ['Projectile'], allTypes: ['Projectile', 'Missile', 'Frontal', 'Physical']}],
    ['Blazehound Shot', {name: 'Blazehound Shot', buffs: ['Haste'], traits: ['Impactful'], debuffs: ['Burn'], types: ['Fire'], allTypes: ['Fire', 'Area', 'Chain', 'Physical']}],
    ['Lava Howl', {name: 'Lava Howl', debuffs: ['Burn'], debuffDep: ['Burn'], types: ['Fire'], allTypes: ['Fire', 'Lasting', 'Area', 'Physical']}],

    ['Arcane Slash', {name: 'Arcane Slash', buffs: ['Finesse', 'Radiance'], types: ['Arcane', 'Swing'], allTypes: ['Arcane', 'Swing', 'Frontal', 'Magical', 'Physical']}],
    ['Arcane Overload', {name: 'Arcane Overload', buffs: ['Radiance'], types: ['Arcane', 'Swing'], allTypes: ['Arcane', 'Swing', 'Area', 'Magical', 'Physical']}],
    ['Slash', {name: 'Slash', buffs: ['Bulwark', 'Finesse'], types: ['Swing'], allTypes: ['Swing', 'Frontal', 'Physical']}],
    ['Uppercut', {name: 'Uppercut', debuffs: ['Stun'], buffDep: ['Finesse'], types: ['Swing'], allTypes: ['Swing', 'Frontal', 'Physical']}],
    ['Arctic Assault', {name: 'Arctic Assault', buffs: ['IcyVeins'], debuffs: ['Disoriented'], types: ['Ice', 'Thrust'], allTypes: ['Ice', 'Thrust', 'Frontal', 'Physical']}],
    ['Frozen Blade', {name: 'Frozen Blade', buffs: ['IcyVeins'], traits: ['Devastating'], types: ['Ice', 'Swing'], allTypes: ['Ice', 'Swing', 'Missile', 'Frontal', 'Physical']}],
    ['Firestorm', {name: 'Firestorm', buffs: ['Haste'], debuffs: ['Burn'], types: ['Fire', 'Swing'], allTypes: ['Fire', 'Swing', 'Lasting', 'Magical', 'Physical']}],
    ['Fiery Blades', {name: 'Fiery Blades', traits: ['Cunning'], debuffDep: ['Burn'], debuffs: ['Burn'], types: ['Fire', 'Swing'], allTypes: ['Fire', 'Swing', 'Summon', 'Magical', 'Physical']}],
    ['Piercing Tempest', {name: 'Piercing Tempest', buffs: ['Form'], traits: ['Devastating'], types: ['Thrust'], allTypes: ['Thrust', 'Area', 'Frontal', 'Physical']}],
    ['Seeker Blades', {name: 'Seeker Blades', buffs: ['Form'], traits: ['Piercing'], debuffs: ['Exposed'], types: ['Thrust'], allTypes: ['Thrust', 'Missile', 'Frontal', 'Magical']}],

    ['Arcane Missiles', {name: 'Arcane Missiles', buffs: ['Radiance'], debuffs: ['Brittle'], types: ['Arcane'], allTypes: ['Arcane', 'Missile', 'Burst', 'Magical']}],
    ['Arcane Explosion', {name: 'Arcane Explosion', buffs: ['Radiance'], debuffs: ['Brittle'], debuffDep: ['Brittle'], types: ['Arcane'], allTypes: ['Arcane', 'Area', 'Burst', 'Magical']}],
    ['Fiery Missiles', {name: 'Fiery Missiles', debuffs: ['Burn'], types: ['Fire'], allTypes: ['Fire', 'Missile', 'Burst', 'Magical']}],
    ['Fire Pillar', {name: 'Fire Pillar', debuffs: ['Burn', 'Weakness'], types: ['Fire'], allTypes: ['Fire', 'Area', 'Burst', 'Magical']}],
    ['Sacred Orb', {name: 'Sacred Orb', buffs: ['Purity'], debuffs: ['Exposed'], types: ['Holy'], allTypes: ['Holy', 'Missile', 'Frontal', 'Magical']}],
    ['Celestial Retribution', {name: 'Celestial Retribution', buffs: ['Purity'], debuffDep: ['Exposed'], types: ['Holy'], allTypes: ['Holy', 'Area', 'Burst', 'Magical']}],
    ['Frost Beam', {name: 'Frost Beam', buffs: ['IcyVeins'], debuffDep: ['Slow'], types: ['Ice'], allTypes: ['Ice', 'Lasting', 'Frontal', 'Magical']}],
    ['Ice Shield', {name: 'Ice Shield', debuffs: ['Slow', 'Fragility'], types: ['Ice'], allTypes: ['Ice', 'Lasting', 'Aura', 'Magical']}],

    ['Shoot', {name: 'Shoot', buffs: ['Aptitude'], types: ['Projectile'], allTypes: ['Projectile', 'Missile', 'Frontal', 'Physical']}],
    ['Rain Of Arrows', {name: 'Rain Of Arrows', buffs: ['Aptitude'], buffDep: ['Aptitude'], types: ['Projectile'], allTypes: ['Projectile', 'Lasting', 'Area', 'Physical']}],
    ['Explosive Arrows', {name: 'Explosive Arrows', traits: ['Devastating'], debuffs: ['Bleed'], types: ['Bomb'], allTypes: ['Bomb', 'Missile', 'Frontal', 'Burst', 'Physical']}],
    ['Cluster Bomb', {name: 'Cluster Bomb', debuffs: ['Bleed'], types: ['Bomb'], allTypes: ['Bomb', 'Area', 'Frontal', 'Burst', 'Physical']}],
    ['Obscure Arrow', {name: 'Obscure Arrow', buffs: ['Aptitude'], debuffs: ['Doom'], types: ['Shadow', 'Projectile'], allTypes: ['Shadow', 'Projectile', 'Missile', 'Frontal', 'Magical', 'Physical']}],
    ['Void Trap', {name: 'Void Trap', debuffs: ['Doom', 'Weakness'], types: ['Shadow', 'Bomb'], allTypes: ['Shadow', 'Bomb', 'Lasting', 'Static', 'Physical']}],
    ['Noxious Shot', {name: 'Noxious Shot', buffs: ['Aptitude'], debuffs: ['Poison'], types: ['Nature'], allTypes: ['Nature', 'Missile', 'Frontal', 'Physical']}],
    ['Venomous Volley', {name: 'Venomous Volley', debuffs: ['Poison', 'Weakness'], types: ['Nature'], allTypes: ['Nature', 'Missile', 'Frontal', 'Burst' ,'Physical']}],

    ['Blades Of Light', {name: 'Blades Of Light', buffs: ['Purity', 'Prowess'], types: ['Holy', 'Swing'], allTypes: ['Holy', 'Swing', 'Frontal', 'Physical']}],
    ['Holy Fire', {name: 'Holy Fire', buffs: ['Purity'], buffDep: ['Purity'], types: ['Holy'], allTypes: ['Holy', 'Missile', 'Frontal', 'Burst', 'Physical']}],
    ['Heroic Strike', {name: 'Heroic Strike', buffs: ['Purity', 'Finesse'], types: ['Swing'], allTypes: ['Swing', 'Frontal', 'Physical']}],
    ['Hammer Of Justice', {name: 'Hammer Of Justice', buffs: ['Purity', 'Finesse'], traits: ['Piercing'], types: ['Holy', 'Swing'], allTypes: ['Holy', 'Swing', 'Missile', 'Frontal', 'Physical']}],
    ['Radiant Light', {name: 'Radiant Light', buffs: ['Prowess', 'Radiance'], types: ['Arcane'], allTypes: ['Arcane', 'Lasting', 'Frontal', 'Physical']}],
    ['Arcane Mace', {name: 'Arcane Mace', buffs: ['Radiance'], buffDep: ['Radiance'], types: ['Arcane', 'Slam'], allTypes: ['Arcane', 'Slam', 'Area', 'Frontal', 'Magical']}],
    ['Fissure Strike', {name: 'Fissure Strike', buffs: ['Prowess', 'Resilience'], types: ['Slam'], allTypes: ['Slam', 'Missile', 'Burst', 'Physical']}],
    ['Staggering Blow', {name: 'Staggering Blow', buffs: ['Prowess'], buffDep: ['Prowess'], types: ['Slam'], allTypes: ['Slam', 'Frontal', 'Physical']}],

    ['Chaotic Missile', {name: 'Chaotic Missile', traits: ['Chaotic', 'Piercing'], types: ['Chaos'], allTypes: ['Chaos', 'Missile', 'Frontal', 'Magical']}],
    ['Unchained Chaos', {name: 'Unchained Chaos', traits: ['Chaotic'], debuffs: ['Disarray'], types: ['Chaos'], allTypes: ['Chaos', 'Missile', 'Chain', 'Magical']}],
    ['Infected Shot', {name: 'Infected Shot', debuffs: ['Poison'], types: ['Nature'], allTypes: ['Nature', 'Missile', 'Burst', 'Magical']}],
    ['Corrosion', {name: 'Corrosion', debuffs: ['Poison'], debuffDep: ['Poison'], types: ['Nature'], allTypes: ['Nature', 'Lasting', 'Aura', 'Magical']}],
    ['Orbs Of Destruction', {name: 'Orbs Of Destruction', debuffs: ['Burn'], debuffDep: ['Burn'], types: ['Fire'], allTypes: ['Fire', 'Missile', 'Frontal', 'Magical']}],
    ['Volcano Eruption', {name: 'Volcano Eruption', debuffs: ['Burn'], types: ['Fire'], allTypes: ['Fire', 'Static', 'Summon', 'Magical']}],
    ['Ripple Of Light', {name: 'Ripple Of Light', buffs: ['Purity'], traits: ['Brutal'], types: ['Holy'], allTypes: ['Holy', 'Area', 'Burst', 'Magical']}],
    ['Sanctified Orb', {name: 'Sanctified Orb', buffs: ['Purity'], debuffs: ['Dazed'], types: ['Holy'], allTypes: ['Holy', 'Missile', 'Lasting', 'Frontal', 'Magical']}],

    ['Venomous Strike', {name: 'Venomous Strike', buffs: ['Finesse'], debuffs: ['Poison'], types: ['Nature', 'Swing'], allTypes: ['Nature', 'Swing', 'Frontal', 'Physical']}],
    ['Plague Viper', {name: 'Plague Viper', traits: ['Cunning'], debuffs: ['Poison', 'Weakness'], types: ['Nature'], allTypes: ['Nature', 'Summon', 'Magical', 'Physical']}],
    ['Wild Strike', {name: 'Wild Strike', buffs: ['Finesse'], types: ['Nature', 'Swing'], allTypes: ['Nature', 'Swing', 'Frontal', 'Physical']}],
    ['Summon Swamp Boar', {name: 'Summon Swamp Boar', debuffs: ['Fragility'], types: ['Nature', 'Swing'], allTypes: ['Nature', 'Swing', 'Summon', 'Magical', 'Physical']}],
    ['Brutal Slam', {name: 'Brutal Slam', buffs: ['Prowess'], types: ['Slam'], allTypes: ['Slam', 'Area', 'Frontal', 'Physical']}],
    ['Summon Cave Bear', {name: 'Summon Cave Bear', traits: ['Taunt'], types: ['Nature', 'Slam'], allTypes: ['Nature', 'Slam', 'Summon', 'Physical']}],
    ['Spider Cocoon', {name: 'Spider Cocoon', debuffs: ['Bleed'], types: ['Bomb'], allTypes: ['Bomb', 'Lasting', 'Static', 'Summon', 'Physical']}],
    ['Summon Spider Queen', {name: 'Summon Spider Queen', traits: ['Cunning'], debuffs: ['Bleed', 'Weakness'], types: ['Bomb'], allTypes: ['Bomb', 'Summon', 'Magical', 'Physical']}],

    ['Sinister Strike', {name: 'Sinister Strike', buffs: ['Form', 'Haste'], traits: ['Ambush'], debuffs: ['Bleed'], types: ['Thrust'], allTypes: ['Thrust', 'Frontal', 'Physical']}],
    ['Eviscerate', {name: 'Eviscerate', buffs: ['Form', 'Haste'], traits: ['Ambush'], debuffDep: ['Bleed'], debuffs: ['Bleed'], types: ['Thrust'], allTypes: ['Thrust', 'Frontal', 'Physical']}],
    ['Twin Daggers', {name: 'Twin Daggers', buffs: ['Finesse', 'Haste'], traits: ['Ambush'], debuffs: ['Bleed'], types: ['Swing'], allTypes: ['Swing', 'Frontal', 'Physical']}],
    ['Backstab', {name: 'Backstab', buffs: ['Finesse', 'Haste'], traits: ['Ambush'], types: ['Swing'], allTypes: ['Swing', 'Frontal', 'Physical']}],
    ['Debilitating Bomb', {name: 'Debilitating Bomb', debuffs: ['Bleed'], types: ['Bomb'], allTypes: ['Bomb', 'Missile', 'Frontal', 'Physical']}],
    ['Fan Of Bombs', {name: 'Fan Of Bombs', buffs: ['Finesse'], debuffs: ['Bleed', 'Fragility'], types: ['Swing', 'Bomb'], allTypes: ['Swing', 'Bomb', 'Area', 'Burst', 'Physical']}],
    ['Shadow Stab', {name: 'Shadow Stab', buffs: ['Form'], traits: ['Ambush'], debuffs: ['Doom'], types: ['Shadow', 'Thrust'], allTypes: ['Shadow', 'Thrust', 'Frontal', 'Physical']}],
    ['Reap', {name: 'Reap', traits: ['Ambush'], debuffs: ['Doom'], debuffDep: ['Doom'], types: ['Shadow', 'Swing'], allTypes: ['Shadow', 'Swing', 'Frontal', 'Physical']}],

    ['Lightning Beam', {name: 'Lightning Beam', debuffs: ['Dazed'], types: ['Electric'], allTypes: ['Electric', 'Lasting', 'Frontal', 'Magical']}],
    ['Call Lightning', {name: 'Call Lightning', buffs: ['Electrified'], debuffDep: ['Dazed'], types: ['Electric'], allTypes: ['Electric', 'Area', 'Magical']}],
    ['Severe Cold', {name: 'Severe Cold', debuffs: ['Disoriented', 'Slow'], types: ['Ice'], allTypes: ['Ice', 'Missile', 'Frontal', 'Magical']}],
    ['Freezing Blow', {name: 'Freezing Blow', buffs: ['IcyVeins'], debuffs: ['Slow'], types: ['Ice', 'Blast'], allTypes: ['Ice', 'Blast', 'Area', 'Frontal', 'Magical']}],
    ['Ray Of Fire', {name: 'Ray Of Fire', buffs: ['Haste'], debuffs: ['Burn'], types: ['Fire'], allTypes: ['Fire', 'Lasting', 'Aura', 'Magical']}],
    ['Heat Explosion', {name: 'Heat Explosion', debuffs: ['Burn'], debuffDep: ['Burn'], types: ['Fire'], allTypes: ['Fire', 'Area', 'Burst', 'Magical']}],
    ['Contaminated Cut', {name: 'Contaminated Cut', debuffDep: ['Poison'], types: ['Nature'], allTypes: ['Nature', 'Frontal', 'Magical', 'Physical']}],
    ['Outbreak', {name: 'Outbreak', debuffs: ['Poison'], types: ['Nature'], allTypes: ['Nature', 'Missile', 'Burst', 'Magical', 'Physical']}],

    ['Thrust', {name: 'Thrust', buffs: ['Form', 'Resilience'], types: ['Thrust'], allTypes: ['Thrust', 'Frontal', 'Physical']}],
    ['Shield Bash', {name: 'Shield Bash', buffs: ['Form'], types: ['Thrust'], allTypes: ['Thrust', 'Frontal', 'Physical']}],
    ['Jupiters Spear', {name: 'Jupiters Spear', buffs: ['Electrified'], debuffs: ['Distracted'], types: ['Electric', 'Thrust'], allTypes: ['Electric', 'Thrust', 'Frontal', 'Chain', 'Physical']}],
    ['Summon Infantry', {name: 'Summon Infantry', traits: ['Cunning'], debuffs: ['Dazed'], types: ['Electric'], allTypes: ['Electric', 'Summon', 'Magical', 'Physical']}],
    ['Corrosive Spear', {name: 'Corrosive Spear', buffs: ['Vigor'], debuffs: ['Poison'], types: ['Nature'], allTypes: ['Nature', 'Missile', 'Frontal', 'Physical']}],
    ['Purging Slam', {name: 'Purging Slam', buffs: ['Vigor'], debuffDep: ['Poison'], types: ['Nature', 'Slam'], allTypes: ['Nature', 'Slam', 'Frontal', 'Physical']}],
    ['Piercing Flames', {name: 'Piercing Flames', debuffs: ['Burn', 'Shattered'], debuffDep: ['Burn'], types: ['Fire'], allTypes: ['Fire', 'Frontal', 'Burst', 'Physical']}],
    ['Incinerating Spear', {name: 'Incinerating Spear', buffs: ['Form'], debuffs: ['Burn'], types: ['Fire'], allTypes: ['Fire', 'Missile', 'Frontal', 'Magical', 'Physical']}],

    ['Summon Skeletal Warrior', {name: 'Summon Skeletal Warrior', traits: ['Cunning'], debuffs: ['Crippled'], types: ['Shadow'], allTypes: ['Shadow', 'Summon', 'Magical', 'Physical']}],
    ['Shadow Nova', {name: 'Shadow Nova', debuffs: ['Doom'], types: ['Shadow'], allTypes: ['Shadow', 'Area', 'Burst', 'Magical']}],
    ['Spectral Guardian', {name: 'Spectral Guardian', buffs: ['Radiance'], types: ['Arcane'], allTypes: ['Arcane', 'Area', 'Burst', 'Magical']}],
    ['Soul Release', {name: 'Soul Release', buffs: ['Radiance'], traits: ['Piercing'], types: ['Arcane'], allTypes: ['Arcane', 'Missile', 'Frontal', 'Magical', 'Physical']}],
    ['Summon Plague Rats', {name: 'Summon Plague Rats', debuffs: ['Poison', 'Weakness'], types: ['Nature'], allTypes: ['Nature', 'Summon', 'Magical', 'Physical']}],
    ['Putrefy', {name: 'Putrefy', debuffs: ['Poison'], types: ['Nature'], allTypes: ['Nature', 'Area', 'Burst', 'Magical']}],
    ['Murder Of Crows', {name: 'Murder Of Crows', traits: ['Chaotic'], types: ['Chaos'], allTypes: ['Chaos', 'Missile', 'Frontal', 'Magical', 'Physical']}],
    ['Carrion Crows', {name: 'Carrion Crows', traits: ['Chaotic'], debuffs: ['Disarray'], types: ['Chaos'], allTypes: ['Chaos', 'Missile', 'Frontal', 'Magical', 'Physical']}],

    ['Obliterate', {name: 'Obliterate', buffs: ['Finesse'], debuffs: ['Doom'], types: ['Shadow', 'Swing'], allTypes: ['Shadow', 'Swing', 'Frontal', 'Magical', 'Physical']}],
    ['Ray Of Doom', {name: 'Ray Of Doom', debuffs: ['Doom'], types: ['Shadow'], allTypes: ['Shadow', 'Lasting', 'Aura', 'Magical']}],
    ['Festering Strike', {name: 'Festering Strike', debuffs: ['Poison', 'Weakness'], types: ['Nature', 'Swing'], allTypes: ['Nature', 'Swing', 'Area', 'Magical', 'Physical']}],
    ['Lethal Blade', {name: 'Lethal Blade', debuffDep: ['Poison'], types: ['Nature'], allTypes: ['Nature', 'Missile', 'Frontal', 'Physical']}],
    ['Ravaging Strike', {name: 'Ravaging Strike', buffs: ['Bulwark', 'Finesse'], types: ['Swing'], allTypes: ['Swing', 'Area', 'Frontal', 'Physical']}],
    ['Carnage', {name: 'Carnage', buffs: ['Bulwark', 'Finesse'], types: ['Swing'], allTypes: ['Swing', 'Missile', 'Area', 'Burst', 'Physical']}],
    ['Frost Strike', {name: 'Frost Strike', buffs: ['IcyVeins'], debuffs: ['Fragility'], types: ['Ice', 'Swing'], allTypes: ['Ice', 'Swing', 'Missile', 'Frontal', 'Physical']}],
    ['Glacial Affinity', {name: 'Glacial Affinity', debuffDep: ['Slow'], types: ['Ice'], allTypes: ['Ice', 'Empowering', 'Lasting', 'Area', 'Physical']}],

    ['Massive Slam', {name: 'Massive Slam', buffs: ['Prowess'], debuffDep: ['Shattered'], types: ['Slam'], allTypes: ['Slam', 'Frontal', 'Physical']}],
    ['Spinning Staff', {name: 'Spinning Staff', buffs: ['Prowess'], debuffs: ['Shattered'], types: ['Slam'], allTypes: ['Slam', 'Missile', 'Frontal', 'Physical']}],
    ['Tempestuous Slash', {name: 'Tempestuous Slash', buffs: ['Electrified', 'Form'], types: ['Electric'], allTypes: ['Electric', 'Missile', 'Frontal', 'Physical']}],
    ['Nimbus Lightning', {name: 'Nimbus Lightning', buffs: ['Electrified'], debuffs: ['Dazed'], types: ['Electric'], allTypes: ['Electric', 'Missile', 'Frontal', 'Magical']}],
    ['Gunpowder Strike', {name: 'Gunpowder Strike', debuffs: ['Bleed', 'Weakness'], debuffDep: ['Bleed'], types: ['Bomb'], allTypes: ['Bomb', 'Frontal', 'Physical']}],
    ['Trickster Decoy', {name: 'Trickster Decoy', debuffs: ['Bleed'], types: ['Bomb'], allTypes: ['Bomb', 'Static', 'Summon', 'Physical']}],
    ['Fracturing Blow', {name: 'Fracturing Blow', buffs: ['Colossal'], types: ['Earth'], allTypes: ['Earth', 'Frontal', 'Physical']}],
    ['Rock Crushing', {name: 'Rock Crushing', buffs: ['Colossal', 'Resilience'], types: ['Earth'], allTypes: ['Earth', 'Area', 'Magical']}],

    ['Burst Of Lead', {name: 'Burst Of Lead', buffs: ['Aptitude'], traits: ['Brutal'], debuffs: ['Dazed'], types: ['Projectile'], allTypes: ['Projectile', 'Lasting', 'Area', 'Physical']}],
    ['Guided Missiles', {name: 'Guided Missiles', buffs: ['Aptitude'], traits: ['Impactful'], types: ['Projectile'], allTypes: ['Projectile', 'Missile', 'Burst', 'Magical']}],
    ['EZ Sentry', {name: 'EZ Sentry', buffs: ['Ammunition'], traits: ['Cunning'], debuffs: ['Bleed'], types: ['Blast'], allTypes: ['Blast', 'Static', 'Summon', 'Physical']}],
    ['EZ Mechanical Spider', {name: 'EZ Mechanical Spider', buffs: ['Ammunition'], traits: ['Cunning'], debuffs: ['Shattered'], types: ['Blast'], allTypes: ['Blast', 'Summon', 'Magical', 'Physical']}],
    ['Energizer', {name: 'Energizer', buffs: ['Electrified'], buffDep: ['Electrified'], types: ['Electric'], allTypes: ['Electric', 'Frontal', 'Physical']}],
    ['Power Generator', {name: 'Power Generator', buffs: ['Electrified'], debuffs: ['Dazed'], types: ['Electric'], allTypes: ['Electric', 'Static', 'Summon', 'Physical']}],
    ['QT Bombuddy 1000', {name: 'QT Bombuddy 1000', traits: ['Impactful'], debuffDep: ['Bleed'], types: ['Bomb'], allTypes: ['Bomb', 'Summon', 'Physical']}],
    ['QT Land Surprise', {name: 'QT Land Surprise', debuffs: ['Bleed'], types: ['Bomb'], allTypes: ['Bomb', 'Area', 'Burst', 'Physical']}],

    ['Glacial Trident', {name: 'Glacial Trident', buffs: ['IcyVeins'], debuffs: ['Slow'], types: ['Ice', 'Thrust'], allTypes: ['Ice', 'Thrust', 'Frontal', 'Chain', 'Physical']}],
    ['Frozen Shard', {name: 'Frozen Shard', debuffs: ['Slow'], buffDep: ['IcyVeins'], types: ['Ice'], allTypes: ['Ice', 'Lasting', 'Area', 'Physical']}],
    ['Tidal Thrust', {name: 'Tidal Thrust', buffs: ['Form'], types: ['Thrust'], allTypes: ['Thrust', 'Frontal', 'Physical']}],
    ['Incisive Strike', {name: 'Incisive Strike', traits: ['Piercing'], types: ['Thrust'], allTypes: ['Thrust', 'Missile', 'Frontal', 'Magical', 'Physical']}],
    ['Sanctified Throw', {name: 'Sanctified Throw', buffs: ['Purity'], traits: ['Devastating'], debuffs: ['Dazed'], types: ['Holy'], allTypes: ['Holy', 'Missile', 'Frontal', 'Magical', 'Physical']}],
    ['Holy Frenzy', {name: 'Holy Frenzy', buffs: ['Purity'], debuffs: ['Dazed'], types: ['Holy'], allTypes: ['Holy', 'Lasting', 'Area', 'Frontal', 'Physical']}],
    ['Abyssal Fissure', {name: 'Abyssal Fissure', buffs: ['Colossal', 'Form'], types: ['Earth'], allTypes: ['Earth', 'Frontal', 'Physical']}],
    ['Fury Of The Depths', {name: 'Fury Of The Depths', buffs: ['Resilience'], types: ['Earth'], allTypes: ['Earth', 'Area', 'Burst', 'Magical']}],

    ['Uncontrolled Arrows', {name: 'Uncontrolled Arrows', traits: ['Chaotic'], debuffs: ['Disarray'], types: ['Chaos'], allTypes: ['Chaos', 'Missile', 'Frontal', 'Magical', 'Physical']}],
    ['Madness Shot', {name: 'Madness Shot', debuffs: ['Disarray'], types: ['Chaos'], allTypes: ['Chaos', 'Frontal', 'Magical', 'Physical']}],
    ['Quick blast', {name: 'Quick blast', buffs: ['Ammunition'], types: ['Blast'], allTypes: ['Blast', 'Frontal', 'Burst', 'Physical']}],
    ['Ammo Overload', {name: 'Ammo Overload', types: ['Blast'], allTypes: ['Blast', 'Frontal', 'Burst', 'Physical']}],
    ['Hellspawn Grenade', {name: 'Hellspawn Grenade', traits: ['Impactful'], debuffs: ['Bleed'], types: ['Bomb'], allTypes: ['Bomb', 'Area', 'Chain', 'Physical']}],
    ['Dreadful Grenade', {name: 'Dreadful Grenade', debuffs: ['Weakness'], debuffDep: ['Bleed'], types: ['Bomb'], allTypes: ['Bomb', 'Lasting', 'Frontal', 'Physical']}],
    ['Shadow Spiral', {name: 'Shadow Spiral', debuffs: ['Doom', 'Disoriented'], types: ['Shadow'], allTypes: ['Shadow', 'Missile', 'Frontal', 'Physical']}],
    ['Cursed Rune', {name: 'Cursed Rune', debuffs: ['Doom', 'Crippled'], types: ['Shadow'], allTypes: ['Shadow', 'Lasting', 'Area', 'Physical']}],

    ['Plunder Shot', {name: 'Plunder Shot', buffs: ['Cursed', 'Ammunition'], types: ['Blast'], allTypes: ['Blast', 'Missile', 'Frontal', 'Physical']}],
    ['Gunpowder Burst', {name: 'Gunpowder Burst', buffs: ['Cursed'], traits: ['Gunpowder'], types: ['Blast'], allTypes: ['Blast', 'Frontal', 'Burst', 'Physical']}],
    ['Sharktooth', {name: 'Sharktooth', buffs: ['Form', 'Cursed'], debuffs: ['Exposed'], types: ['Thrust'], allTypes: ['Thrust', 'Frontal', 'Physical']}],
    ['Shiver Of Sharks', {name: 'Shiver Of Sharks', buffs: ['Cursed'], traits: ['Devastating'], types: ['Thrust'], allTypes: ['Thrust', 'Area', 'Magical']}],
    ['Cannon Barrage', {name: 'Cannon Barrage', buffs: ['Cursed'], debuffs: ['Bleed', 'Disoriented'], types: ['Bomb'], allTypes: ['Bomb', 'Area', 'Frontal', 'Burst', 'Physical']}],
    ['Fleet Strike', {name: 'Fleet Strike', buffs: ['Cursed'], debuffs: ['Bleed'], traits: ['Impactful'], types: ['Bomb'], allTypes: ['Bomb', 'Area', 'Burst', 'Magical']}],
    ['Cursed Shot', {name: 'Cursed Shot', buffs: ['Aptitude', 'Cursed'], debuffs: ['Dazed'], types: ['Projectile'], allTypes: ['Projectile', 'Missile', 'Frontal', 'Magical', 'Physical']}],
    ['Ghostly Burst', {name: 'Ghostly Burst', buffs: ['Aptitude', 'Cursed'], debuffDep: ['Dazed'], types: ['Projectile'], allTypes: ['Projectile', 'Missile', 'Frontal', 'Magical', 'Physical']}],

    ['Vine Whip', {name: 'Vine Whip', buffs: ['Ancestry'], debuffs: ['Poison'], types: ['Nature'], allTypes: ['Nature', 'Swing', 'Frontal', 'Physical']}],
    ['Poisonous Thorn', {name: 'Poisonous Thorn', buffs: ['Ancestry'], debuffs: ['Poison'], types: ['Nature'], allTypes: ['Nature', 'Thrust', 'Frontal', 'Physical']}],
    ['Arcane Reaping', {name: 'Arcane Reaping', buffs: ['Radiance', 'Ancestry'], debuffs: ['Fragility'], types: ['Arcane'], allTypes: ['Arcane', 'Swing', 'Frontal', 'Magical']}],
    ['Ancestral Empowerment', {name: 'Ancestral Empowerment', buffs: ['Radiance', 'Ancestry'], types: ['Arcane'], allTypes: ['Arcane', 'Static', 'Summon', 'Magical']}],
    ['Flaming Spiral', {name: 'Flaming Spiral', buffs: ['Ancestry'], debuffs: ['Weakness', 'Burn'], types: ['Fire'], allTypes: ['Fire', 'Swing', 'Area', 'Magical']}],
    ['Volcanic Effigy', {name: 'Volcanic Effigy', buffs: ['Ancestry'], debuffs: ['Burn'], traits: ['Fortitude'], types: ['Fire'], allTypes: ['Fire', 'Static', 'Summon', 'Magical']}],
    ['Earthbreaker', {name: 'Earthbreaker', buffs: ['Ancestry', 'Colossal'], debuffs: ['Brittle'], types: ['Earth'], allTypes: ['Earth', 'Area', 'Frontal', 'Physical']}],
    ['Quicksand', {name: 'Quicksand', buffs: ['Ancestry'], debuffs: ['Brittle'], debuffDep: ['Brittle'], traits: ['Fortitude'], types: ['Earth'], allTypes: ['Earth', 'Static', 'Summon', 'Physical']}],

    ['Resonating Crystals', {name: 'Resonating Crystals', buffs: ['Radiance'], debuffDep: ['Brittle'], types: ['Arcane'], allTypes: ['Arcane', 'Lasting', 'Aura', 'Magical']}],
    ['Crystal Shard', {name: 'Crystal Shard', buffs: ['Radiance'], debuffs: ['Brittle'], traits: ['Piercing'], types: ['Arcane'], allTypes: ['Arcane', 'Missile', 'Aura', 'Magical']}],
    ['Unstable Reactor', {name: 'Unstable Reactor', buffs: ['Ammunition'], traits: ['Brutal'], types: ['Blast'], allTypes: ['Blast', 'Lasting', 'Aura', 'Magical']}],
    ['Shrapnel Spiral', {name: 'Shrapnel Spiral', buffs: ['Ammunition'], debuffs: ['Shattered'], types: ['Blast'], allTypes: ['Blast', 'Missile', 'Burst', 'Physical']}],
    ['Blazing Ray', {name: 'Blazing Ray', debuffs: ['Burn', 'Shattered'], types: ['Fire'], allTypes: ['Fire', 'Lasting', 'Frontal', 'Magical']}],
    ['Ember Discharge', {name: 'Ember Discharge', debuffDep: ['Burn'], types: ['Fire'], allTypes: ['Fire', 'Frontal', 'Burst', 'Magical']}],
    ['Lightning Shield', {name: 'Lightning Shield', buffs: ['Electrified'], debuffs: ['Dazed'], types: ['Electric'], allTypes: ['Electric', 'Lasting', 'Aura', 'Magical']}],
    ['Lightning Coil', {name: 'Lightning Coil', buffs: ['Electrified'], traits: ['Cunning'], types: ['Electric'], allTypes: ['Electric', 'Static', 'Summon', 'Physical']}],

    ['Slice And Dice', {name: 'Slice And Dice', buffs: ['Finesse'], debuffs: ['Condemned'], buffDep: ['Finesse'], types: ['Swing'], allTypes: ['Swing', 'Frontal', 'Physical']}],
    ['Ravenous Cut', {name: 'Ravenous Cut', buffs: ['Finesse'], debuffs: ['Condemned'], types: ['Swing'], allTypes: ['Swing', 'Missile', 'Frontal', 'Physical']}],
    ['Shadow Slice', {name: 'Shadow Slice', debuffs: ['Doom', 'Condemned'], types: ['Shadow'], allTypes: ['Shadow', 'Frontal', 'Physical']}],
    ['Nightfang', {name: 'Nightfang', debuffs: ['Condemned'], debuffDep: ['Doom'], types: ['Shadow'], allTypes: ['Shadow', 'Thrust', 'Frontal', 'Physical']}],
    ['Echoing Rupture', {name: 'Echoing Rupture', buffs: ['Prowess'], debuffs: ['Disoriented', 'Condemned'], types: ['Slam'], allTypes: ['Slam', 'Missile', 'Frontal', 'Physical']}],
    ['Blade Impale', {name: 'Blade Impale', buffs: ['Resilience'], debuffs: ['Condemned', 'Stun'], types: ['Slam'], allTypes: ['Slam', 'Area', 'Physical']}],
    ['Molten Fang', {name: 'Molten Fang', buffs: ['Haste'], debuffs: ['Condemned', 'Burn'], types: ['Fire'], allTypes: ['Fire', 'Frontal', 'Magical', 'Physical']}],
    ['Ignition Spiral', {name: 'Ignition Spiral', debuffs: ['Condemned'], debuffDep: ['Burn'], types: ['Fire'], allTypes: ['Fire', 'Area', 'Magical', 'Physical']}],

    //ALL SKILLS --------------------------------------------------------------------------------------
    ['Piercing Shout', {name: 'Piercing Shout', debuffs: ['Shattered'], types: ['Thrust'], allTypes: ['Thrust', 'Empowering', 'Lasting', 'Area', 'Physical']}],
    ['Savage Strike', {name: 'Savage Strike', buffs: ['Finesse'], types: ['Swing'], allTypes: ['Swing', 'Frontal', 'Physical']}],
    ['Scent Of Blood', {name: 'Scent Of Blood', buffDep: ['Finesse'], types: ['Swing'], allTypes: ['Swing', 'Empowering', 'Lasting', 'Physical']}],
    ['Armor Shatter', {name: 'Armor Shatter', buffs: ['Prowess'], debuffs: ['Shattered'], types: ['Slam'], allTypes: ['Slam', 'Area', 'Burst', 'Physical']}],
    ['Bladestorm', {name: 'Bladestorm', types: ['Swing'], allTypes: ['Swing', 'Lasting', 'Area', 'Physical']}],
    ['Bloody Saw', {name: 'Bloody Saw', buffs: ['Finesse'], debuffs: ['Bleed'], types: ['Swing'], allTypes: ['Swing', 'Lasting', 'Area', 'Physical']}],
    ['Body Slam', {name: 'Body Slam', buffs: ['Prowess'], types: ['Slam'], allTypes: ['Slam', 'Frontal', 'Physical']}],
    ['Chain Lightning', {name: 'Chain Lightning', buffs: ['Electrified'], debuffs: ['Distracted'], types: ['Electric'], allTypes: ['Electric', 'Chain', 'Burst', 'Magical']}],
    ['Chromatic Bolt', {name: 'Chromatic Bolt', types: [], allTypes: ['Arcane', 'Chaos', 'Ice', 'Nature', 'Fire', 'Electric', 'Shadow', 'Holy', 'Earth', 'Projectile', 'Bomb', 'Blast', 'Missile', 'Frontal', 'Magical', 'Physical']}],
    ['Double Slash', {name: 'Double Slash', buffs: ['Bulwark', 'Finesse'], debuffs: ['Debilitated'], types: ['Swing'], allTypes: ['Swing', 'Frontal', 'Physical']}],
    ['Earth bolt', {name: 'Earth bolt', buffs: ['Colossal'], types: ['Earth'], allTypes: ['Earth', 'Missile', 'Frontal', 'Magical', 'Physical']}],
    ['Earthquake', {name: 'Earthquake', buffs: ['Colossal'], debuffs: ['Brittle'], types: ['Earth'], allTypes: ['Earth', 'Lasting', 'Area', 'Magical']}],
    ['Earth Shield', {name: 'Earth Shield', buffs: ['Resilience'], types: ['Earth'], allTypes: ['Earth', 'Lasting', 'Aura', 'Magical', 'Physical']}],
    ['Flurry', {name: 'Flurry', buffs: ['Form'], debuffs: ['Bleed'], types: ['Thrust'], allTypes: ['Thrust', 'Lasting', 'Area', 'Frontal', 'Physical']}],
    ['Ground Break', {name: 'Ground Break', buffs: ['Prowess'], traits: ['Piercing'], types: ['Slam'], allTypes: ['Slam', 'Missile', 'Burst', 'Physical']}],
    ['Heartrending Strike', {name: 'Heartrending Strike', buffs: ['Bulwark', 'Finesse'], debuffs: ['Fragility'], types: ['Swing'], allTypes: ['Swing', 'Area', 'Frontal', 'Physical', 'Seasonal']}],
    ['Lightning bolt', {name: 'Lightning bolt', buffs: ['Electrified'], traits: ['Devastating'], types: ['Electric'], allTypes: ['Electric', 'Missile', 'Magical', 'Physical']}],
    ['Lightning Surge', {name: 'Lightning Surge', debuffs: ['Dazed'], types: ['Electric'], allTypes: ['Electric', 'Empowering', 'Lasting', 'Physical']}],
    ['On Guard', {name: 'On Guard', buffs: ['Bulwark', 'Form'], debuffs: ['Exposed'], types: ['Thrust'], allTypes: ['Thrust', 'Area', 'Physical']}],
    ['Power Conductor', {name: 'Power Conductor', buffs: ['Electrified'], debuffs: ['Dazed'], types: ['Electric'], allTypes: ['Electric', 'Static', 'Summon', 'Physical']}],
    ['Quick Strike', {name: 'Quick Strike', buffs: ['Form', 'Haste'], types: ['Thrust'], allTypes: ['Thrust', 'Frontal', 'Physical']}],
    ['Resonant Slam', {name: 'Resonant Slam', buffs: ['Prowess', 'Resilience'], traits: ['Brutal'], types: ['Slam'], allTypes: ['Slam', 'Area', 'Burst', 'Physical']}],
    ['Rolling Boulder', {name: 'Rolling Boulder', debuffs: ['Stun'], types: ['Earth'], allTypes: ['Earth', 'Area', 'Magical']}],
    ['Seismic Shock', {name: 'Seismic Shock', buffs: ['Prowess', 'Resilience'], types: ['Slam'], allTypes: ['Slam', 'Frontal', 'Physical']}],
    ['Sharp Spear', {name: 'Sharp Spear', buffs: ['Haste', 'Form'], traits: ['Piercing'], types: ['Thrust'], allTypes: ['Thrust', 'Missile', 'Frontal', 'Physical']}],
    ['Shockwave Totem', {name: 'Shockwave Totem', debuffs: ['Dazed'], types: ['Earth'], allTypes: ['Earth', 'Static', 'Summon', 'Physical']}],
    ['Spear Trap', {name: 'Spear Trap', buffs: ['Form'], debuffs: ['Exposed'], types: ['Thrust'], allTypes: ['Thrust', 'Lasting', 'Area', 'Magical']}],
    ['Subdue', {name: 'Subdue', buffDep: ['Finesse'], types: ['Swing'], allTypes: ['Swing', 'Frontal', 'Physical']}],
    ['Sugar Rush', {name: 'Sugar Rush', types: ['Thrust'], allTypes: ['Thrust', 'Empowering', 'Lasting', 'Physical', 'Seasonal']}],
    ['Thunder strike', {name: 'Thunder strike', buffs: ['Electrified'], debuffs: ['Stun'], types: ['Electric'], allTypes: ['Electric', 'Area', 'Magical']}],
    ['Titans Cleaver', {name: 'Titans Cleaver', buffs: ['Finesse'], types: ['Swing'], allTypes: ['Swing', 'Frontal', 'Physical']}],
    ['Conflagrate', {name: 'Conflagrate', debuffDep: ['Burn'], types: ['Fire'], allTypes: ['Fire', 'Area', 'Burst', 'Magical']}],
    ['Fire Wall', {name: 'Fire Wall', debuffs: ['Burn', 'Weakness'], types: ['Fire'], allTypes: ['Fire', 'Lasting', 'Area', 'Magical']}],
    ['Meteor Shower', {name: 'Meteor Shower', debuffDep: ['Burn'], types: ['Fire'], allTypes: ['Fire', 'Area', 'Burst', 'Magical']}],
    ['Arcane Beam', {name: 'Arcane Beam', debuffs: ['Brittle'], types: ['Arcane'], allTypes: ['Arcane', 'Lasting', 'Frontal', 'Magical']}],
    ['Arcane Disc', {name: 'Arcane Disc', buffs: ['Radiance'], traits: ['Piercing'], types: ['Arcane'], allTypes: ['Arcane', 'Missile', 'Frontal', 'Magical']}],
    ['Arcane Power', {name: 'Arcane Power', types: ['Arcane'], allTypes: ['Arcane', 'Empowering', 'Lasting', 'Area', 'Magical']}],
    ['Arcane Sparks', {name: 'Arcane Sparks', buffs: ['Radiance'], traits: ['Piercing'], types: ['Arcane'], allTypes: ['Arcane', 'Missile', 'Burst', 'Magical']}],
    ['Bloodlust', {name: 'Bloodlust', types: ['Chaos'], allTypes: ['Chaos', 'Empowering', 'Lasting', 'Area', 'Physical']}],
    ['Chaos Bolt', {name: 'Chaos Bolt', traits: ['Chaotic', 'Precise'], types: ['Chaos'], allTypes: ['Chaos', 'Missile', 'Frontal', 'Magical', 'Physical']}],
    ['Chaotic Explosion', {name: 'Chaotic Explosion', traits: ['Chaotic', 'Impactful'], types: ['Chaos'], allTypes: ['Chaos', 'Frontal', 'Magical', 'Physical']}],
    ['Combustion', {name: 'Combustion', debuffs: ['Burn'], types: ['Fire'], allTypes: ['Fire', 'Lasting', 'Area', 'Magical']}],
    ['Death Claw', {name: 'Death Claw', traits: ['Chaotic'], types: ['Chaos'], allTypes: ['Chaos', 'Area', 'Burst', 'Magical']}],
    ['Death Vortex', {name: 'Death Vortex', debuffs: ['Doom'], types: ['Shadow'], allTypes: ['Shadow', 'Lasting', 'Area', 'Magical']}],
    ['Fire bolt', {name: 'Fire bolt', debuffs: ['Burn', 'Weakness'], types: ['Fire'], allTypes: ['Fire', 'Missile', 'Frontal', 'Magical', 'Physical']}],
    ['Flamethrower', {name: 'Flamethrower', debuffs: ['Burn'], types: ['Fire'], allTypes: ['Fire', 'Lasting', 'Frontal', 'Magical']}],
    ['Flame Wave', {name: 'Flame Wave', debuffs: ['Burn', 'Shattered'], types: ['Fire'], allTypes: ['Fire', 'Area', 'Burst', 'Magical']}],
    ['Frenzied Bunnies', {name: 'Frenzied Bunnies', debuffs: ['Disarray'], types: ['Chaos'], allTypes: ['Chaos', 'Summon', 'Magical', 'Physical', 'Seasonal']}],
    ['Magic Missiles', {name: 'Magic Missiles', debuffs: ['Fragility'], types: ['Arcane'], allTypes: ['Arcane', 'Missile', 'Frontal', 'Burst', 'Magical']}],
    ['Meteor', {name: 'Meteor', debuffs: ['Burn', 'Stun'], types: ['Fire'], allTypes: ['Fire', 'Area', 'Magical']}],
    ['Shadow Bolt', {name: 'Shadow Bolt', buffs: ['Aptitude'], debuffs: ['Doom'], types: ['Shadow'], allTypes: ['Shadow', 'Missile', 'Magical', 'Physical']}],
    ['Shadow orb', {name: 'Shadow orb', debuffs: ['Doom', 'Disoriented'], types: ['Shadow'], allTypes: ['Shadow', 'Missile', 'Lasting', 'Frontal', 'Magical']}],
    ['Shadow Spikes', {name: 'Shadow Spikes', debuffDep: ['Doom'], types: ['Shadow'], allTypes: ['Shadow', 'Missile', 'Burst', 'Physical']}],
    ['Summon Chaos Golem', {name: 'Summon Chaos Golem', traits: ['Taunt'], debuffs: ['Disarray', 'Stun'], types: ['Chaos'], allTypes: ['Chaos', 'Summon', 'Magical', 'Physical']}],
    ['Void', {name: 'Void', debuffs: ['Doom'], types: ['Shadow'], allTypes: ['Shadow', 'Lasting', 'Area', 'Magical']}],
    ['Bear Trap', {name: 'Bear Trap', debuffs: ['Bleed', 'Weakness'], types: ['Bomb'], allTypes: ['Bomb', 'Lasting', 'Static', 'Physical']}],
    ['Shrapnel Mine', {name: 'Shrapnel Mine', debuffs: ['Bleed'], types: ['Bomb'], allTypes: ['Bomb', 'Lasting', 'Static', 'Physical']}],
    ['Weakening Grenade', {name: 'Weakening Grenade', traits: ['Impactful'], debuffs: ['Bleed', 'Disoriented'], types: ['Bomb'], allTypes: ['Bomb', 'Area', 'Burst', 'Physical']}],
    ['Acid Rain', {name: 'Acid Rain', debuffs: ['Poison'], types: ['Nature'], allTypes: ['Nature', 'Area', 'Frontal', 'Physical']}],
    ['Bladed Chakram', {name: 'Bladed Chakram', buffs: ['Aptitude'], traits: ['Piercing'], types: ['Projectile'], allTypes: ['Projectile', 'Missile', 'Frontal', 'Physical']}],
    ['Bomb Barrage', {name: 'Bomb Barrage', debuffs: ['Bleed'], types: ['Bomb'], allTypes: ['Bomb', 'Missile', 'Frontal', 'Burst', 'Physical']}],
    ['Camors Arrow', {name: 'Camors Arrow', debuffs: ['Fragility', 'Stun'], types: ['Projectile'], allTypes: ['Projectile', 'Area', 'Physical', 'Seasonal']}],
    ['Egg Shooter', {name: 'Egg Shooter', debuffs: ['Dazed'], types: ['Projectile'], allTypes: ['Projectile', 'Missile', 'Frontal', 'Physical', 'Seasonal']}],
    ['Explosive Shot', {name: 'Explosive Shot', buffs: ['Ammunition'], debuffs: ['Shattered'], types: ['Blast'], allTypes: ['Blast', 'Missile', 'Frontal', 'Physical']}],
    ['Explosive Trap', {name: 'Explosive Trap', debuffs: ['Bleed', 'Disoriented'], types: ['Bomb'], allTypes: ['Bomb', 'Lasting', 'Static', 'Physical']}],
    ['Frag Shot', {name: 'Frag Shot', buffs: ['Aptitude'], debuffs: ['Dazed'], types: ['Projectile'], allTypes: ['Projectile', 'Missile', 'Frontal', 'Physical']}],
    ['Heartbreak Orbs', {name: 'Heartbreak Orbs', buffs: ['Aptitude'], traits: ['Precise'], types: ['Projectile'], allTypes: ['Projectile', 'Missile', 'Frontal', 'Physical', 'Seasonal']}],
    ['Mine Field', {name: 'Mine Field', debuffs: ['Bleed'], types: ['Bomb'], allTypes: ['Bomb', 'Lasting', 'Static', 'Physical']}],
    ['Napalm Blast', {name: 'Napalm Blast', buffs: ['Ammunition'], debuffs: ['Shattered'], types: ['Blast'], allTypes: ['Blast', 'Area', 'Frontal', 'Physical']}],
    ['Pestilence', {name: 'Pestilence', debuffs: ['Poison'], debuffDep: ['Poison'], types: ['Nature'], allTypes: ['Nature', 'Chain', 'Burst', 'Magical']}],
    ['Poison Bolt', {name: 'Poison Bolt', debuffs: ['Poison'], types: ['Nature'], allTypes: ['Nature', 'Missile', 'Frontal', 'Magical', 'Physical']}],
    ['Poison Cloud', {name: 'Poison Cloud', debuffs: ['Poison', 'Weakness'], types: ['Nature'], allTypes: ['Nature', 'Lasting', 'Area', 'Physical']}],
    ['Poison Puddle', {name: 'Poison Puddle', debuffs: ['Poison', 'Debilitated'], types: ['Nature'], allTypes: ['Nature', 'Lasting', 'Area', 'Physical']}],
    ['Rapid Barrage', {name: 'Rapid Barrage', buffs: ['Ammunition'], types: ['Blast'], allTypes: ['Blast', 'Lasting', 'Frontal', 'Physical']}],
    ['Shrapnel Bomb', {name: 'Shrapnel Bomb', debuffDep: ['Bleed'], types: ['Bomb'], allTypes: ['Bomb', 'Area', 'Frontal', 'Burst', 'Physical']}],
    ['Shrapnel Shot', {name: 'Shrapnel Shot', buffs: ['Ammunition'], debuffs: ['Bleed'], types: ['Blast'], allTypes: ['Blast', 'Missile', 'Frontal', 'Physical']}],
    ['Spread Shot', {name: 'Spread Shot', buffs: ['Aptitude'], debuffs: ['Dazed'], types: ['Projectile'], allTypes: ['Projectile', 'Missile', 'Frontal', 'Burst', 'Physical']}],
    ['Storm Of Arrows', {name: 'Storm Of Arrows', types: ['Projectile'], allTypes: ['Projectile', 'Missile', 'Lasting', 'Physical']}],
    ['Suction Bomb', {name: 'Suction Bomb', debuffs: ['Bleed'], types: ['Bomb'], allTypes: ['Bomb', 'Area', 'Frontal', 'Physical']}],
    ['Summon Ballista', {name: 'Summon Ballista', traits: ['Piercing', 'Cunning'], types: ['Projectile'], allTypes: ['Projectile', 'Static', 'Summon', 'Physical']}],
    ['Surprise Gift', {name: 'Surprise Gift', debuffs: ['Bleed', 'Weakness'], types: ['Bomb'], allTypes: ['Bomb', 'Lasting', 'Static', 'Physical', 'Seasonal']}],
    ['Weakening Shot', {name: 'Weakening Shot', buffs: ['Ammunition'], debuffs: ['Exposed'], types: ['Blast'], allTypes: ['Blast', 'Area', 'Frontal', 'Physical']}],
    ['Arcane Assault', {name: 'Arcane Assault', buffs: ['Radiance'], debuffDep: ['Fragility'], types: ['Arcane', 'Thrust'], allTypes: ['Arcane', 'Thrust', 'Frontal', 'Magical', 'Physical']}],
    ['Arcane Blade', {name: 'Arcane Blade', buffs: ['Finesse', 'Radiance'], types: ['Arcane', 'Swing'], allTypes: ['Arcane', 'Swing', 'Frontal', 'Magical', 'Physical']}],
    ['Arcane Rift', {name: 'Arcane Rift', debuffs: ['Fragility'], types: ['Arcane'], allTypes: ['Arcane', 'Lasting', 'Area', 'Magical']}],
    ['Avalanche', {name: 'Avalanche', debuffs: ['Fragility', 'Slow'], types: ['Ice'], allTypes: ['Ice', 'Area', 'Frontal', 'Physical', 'Seasonal']}],
    ['Blizzard', {name: 'Blizzard', debuffs: ['Slow'], types: ['Ice'], allTypes: ['Ice', 'Lasting', 'Area', 'Magical']}],
    ['Frost Bolt', {name: 'Frost Bolt', buffs: ['IcyVeins'], types: ['Ice'], allTypes: ['Ice', 'Missile', 'Frontal', 'Magical', 'Physical']}],
    ['Frost Totem', {name: 'Frost Totem', traits: ['Cunning'], debuffs: ['Slow'], types: ['Ice'], allTypes: ['Ice', 'Summon', 'Static', 'Physical']}],
    ['Glacier', {name: 'Glacier', debuffs: ['Disoriented', 'Slow'], types: ['Ice'], allTypes: ['Ice', 'Area', 'Magical']}],
    ['Ice Vortex', {name: 'Ice Vortex', debuffs: ['Slow'], debuffDep: ['Slow'], types: ['Ice'], allTypes: ['Ice', 'Lasting', 'Area', 'Magical']}],
    ['Summon Helper Elves', {name: 'Summon Helper Elves', traits: ['Cunning'], debuffs: ['Slow'], types: ['Ice'], allTypes: ['Ice', 'Summon', 'Magical', 'Physical', 'Seasonal']}],
    ['Arcane Conjuration', {name: 'Arcane Conjuration', buffs: ['Radiance'], debuffs: ['Brittle'], types: ['Arcane'], allTypes: ['Arcane', 'Area', 'Magical']}],
    ['Arcane Orb', {name: 'Arcane Orb', buffs: ['Finesse', 'Radiance'], types: ['Arcane'], allTypes: ['Arcane', 'Missile', 'Lasting', 'Frontal', 'Magical']}],
    ['Arcane shield', {name: 'Arcane shield', types: ['Arcane'], allTypes: ['Arcane', 'Empowering', 'Lasting', 'Magical']}],
    ['Holy Beam', {name: 'Holy Beam', buffs: ['Purity', 'Prowess'], types: ['Holy'], allTypes: ['Holy', 'Frontal', 'Physical']}],
    ['Light Beam', {name: 'Light Beam', debuffs: ['Exposed'], types: ['Holy'], allTypes: ['Holy', 'Lasting', 'Frontal', 'Magical']}],
    ['Living Weapons', {name: 'Living Weapons', debuffs: ['Dazed'], types: ['Holy'], allTypes: ['Holy', 'Summon', 'Magical', 'Physical']}],
    ['Might', {name: 'Might', types: ['Holy'], allTypes: ['Holy', 'Empowering', 'Lasting', 'Area', 'Physical']}],
    ['Smite', {name: 'Smite', buffs: ['Purity'], types: ['Holy'], allTypes: ['Holy', 'Empowering', 'Lasting', 'Area', 'Physical']}],
    ['Ricochet Shot', {name: 'Ricochet Shot', buffs: ['Aptitude'], traits: ['Piercing'], types: ['Projectile'], allTypes: ['Projectile', 'Missile', 'Frontal', 'Physical']}],
    ['Sniper Shot', {name: 'Sniper Shot', traits: ['Devastating', 'Precise'], types: ['Projectile'], allTypes: ['Projectile', 'Missile', 'Frontal', 'Physical']}],
    ['Split Shot', {name: 'Split Shot', buffs: ['Aptitude'], debuffs: ['Dazed'], types: ['Projectile'], allTypes: ['Projectile', 'Missile', 'Frontal', 'Physical']}],
    ['Beacon Of Light', {name: 'Beacon Of Light', buffs: ['Purity'], debuffs: ['Exposed'], types: ['Holy'], allTypes: ['Holy', 'Lasting', 'Aura', 'Physical']}],
    ['Penance', {name: 'Penance', buffs: ['Purity'], debuffs: ['Dazed'], types: ['Holy'], allTypes: ['Holy', 'Missile', 'Chain', 'Physical']}],
    ['Templars Verdict', {name: 'Templars Verdict', buffs: ['Purity'], traits: ['Devastating'], types: ['Holy', 'Swing'], allTypes: ['Holy', 'Swing', 'Aura', 'Physical']}],
    ['Chaos Totem', {name: 'Chaos Totem', traits: ['Cunning'], debuffs: ['Disarray'], types: ['Chaos'], allTypes: ['Chaos', 'Static', 'Summon', 'Magical']}],
    ['Chaos Wave', {name: 'Chaos Wave', traits: ['Brutal', 'Chaotic'], types: ['Chaos'], allTypes: ['Chaos', 'Area', 'Burst', 'Magical']}],
    ['Manifestations Of Chaos', {name: 'Manifestations Of Chaos', traits: ['Chaotic'], debuffDep: ['Disarray'], types: ['Chaos'], allTypes: ['Chaos', 'Missile', 'Burst', 'Magical']}],
    ['Bestial Wrath', {name: 'Bestial Wrath', types: ['Nature'], allTypes: ['Nature', 'Empowering', 'Lasting', 'Area', 'Physical']}],
    ['Summon Battle Moose', {name: 'Summon Battle Moose', traits: ['Taunt'], debuffs: ['Stun'], types: ['Nature', 'Slam'], allTypes: ['Nature', 'Slam', 'Summon', 'Physical']}],
    ['Summon War Tiger', {name: 'Summon War Tiger', traits: ['Cunning'], debuffs: ['Bleed'], types: ['Nature', 'Swing'], allTypes: ['Nature', 'Swing', 'Summon', 'Physical']}],
    ['Rupture', {name: 'Rupture', buffs: ['Form'], debuffs: ['Stun'], types: ['Thrust'], allTypes: ['Thrust', 'Frontal', 'Physical']}],
    ['Shadow Step', {name: 'Shadow Step', debuffs: ['Doom'], types: ['Shadow'], allTypes: ['Shadow', 'Area', 'Physical']}],
    ['Smoke Bomb', {name: 'Smoke Bomb', traits: ['Ambush'], debuffs: ['Disoriented'], types: ['Shadow', 'Bomb'], allTypes: ['Shadow', 'Bomb', 'Lasting', 'Frontal', 'Physical']}],
    ['Summon Assassin Enclave', {name: 'Summon Assassin Enclave', traits: ['Cunning'], debuffs: ['Bleed'], types: ['Thrust'], allTypes: ['Thrust', 'Summon', 'Magical', 'Physical']}],
    ['Frozen Warhammer', {name: 'Frozen Warhammer', buffs: ['Prowess', 'IcyVeins'], debuffDep: ['Slow'], types: ['Ice', 'Slam'], allTypes: ['Ice', 'Slam', 'Area', 'Frontal', 'Magical']}],
    ['Lava Shield', {name: 'Lava Shield', debuffs: ['Burn', 'Shattered'], types: ['Fire'], allTypes: ['Fire', 'Lasting', 'Aura', 'Magical']}],
    ['Tornado', {name: 'Tornado', buffs: ['Electrified'], traits: ['Devastating'], types: ['Electric'], allTypes: ['Electric', 'Lasting', 'Aura', 'Magical']}],
    ['Intimidating Shout', {name: 'Intimidating Shout', debuffs: ['Distracted'], types: ['Thrust'], allTypes: ['Thrust', 'Empowering', 'Lasting', 'Area', 'Physical']}],
    ['Shield Wall', {name: 'Shield Wall', types: ['Thrust'], allTypes: ['Thrust', 'Empowering', 'Lasting', 'Area', 'Physical']}],
    ['Storm Of Spears', {name: 'Storm Of Spears', buffDep: ['Form'], types: ['Thrust'], allTypes: ['Thrust', 'Missile', 'Lasting', 'Physical']}],
    ['Summon Putrid Hounds', {name: 'Summon Putrid Hounds', traits: ['Cunning'], debuffDep: ['Poison'], types: ['Nature'], allTypes: ['Nature', 'Summon', 'Magical', 'Physical']}],
    ['Summon Skeletal Archer', {name: 'Summon Skeletal Archer', traits: ['Cunning'], types: ['Shadow'], allTypes: ['Shadow', 'Summon', 'Magical', 'Physical']}],
    ['Summon Skeletal Mage', {name: 'Summon Skeletal Mage', debuffs: ['Doom'], types: ['Shadow'], allTypes: ['Shadow', 'Summon', 'Magical', 'Physical']}],
    ['Contagion', {name: 'Contagion', debuffDep: ['Poison'], types: ['Nature'], allTypes: ['Nature', 'Area', 'Burst', 'Magical', 'Physical']}],
    ['Path Of Decay', {name: 'Path Of Decay', debuffs: ['Poison'], types: ['Nature'], allTypes: ['Nature', 'Lasting', 'Area', 'Magical']}],
    ['Shadow Grasp', {name: 'Shadow Grasp', debuffDep: ['Doom'], types: ['Shadow', 'Swing'], allTypes: ['Shadow', 'Swing', 'Area', 'Magical', 'Physical']}],
    ['Electric Strike', {name: 'Electric Strike', buffs: ['Electrified'], types: ['Electric'], allTypes: ['Electric', 'Frontal', 'Physical']}],
    ['Expansive Throw', {name: 'Expansive Throw', buffs: ['Prowess'], buffDep: ['Prowess'], types: ['Slam'], allTypes: ['Slam', 'Missile', 'Frontal', 'Magical']}],
    ['Whirling Defense', {name: 'Whirling Defense', buffs: ['Prowess', 'Resilience'], traits: ['Brutal'], types: ['Slam'], allTypes: ['Slam', 'Lasting', 'Area', 'Physical']}],
    ['Ammo Box', {name: 'Ammo Box', buffs: ['Ammunition'], types: ['Blast'], allTypes: ['Blast', 'Static', 'Summon', 'Physical']}],
    ['Heavy Artillery', {name: 'Heavy Artillery', traits: ['Impactful'], debuffs: ['Bleed', 'Weakness'], types: ['Bomb'], allTypes: ['Bomb', 'Static', 'Summon', 'Magical']}],
    ['Portable Nuke', {name: 'Portable Nuke', traits: ['Devastating'], debuffs: ['Disoriented', 'Stun'], types: ['Bomb'], allTypes: ['Bomb', 'Area', 'Frontal', 'Physical']}],
    ['Jawstorm', {name: 'Jawstorm', buffs: ['IcyVeins'], debuffs: ['Fragility'], types: ['Ice'], allTypes: ['Ice', 'Lasting', 'Area', 'Magical']}],
    ['Precision Wave', {name: 'Precision Wave', types: ['Thrust'], allTypes: ['Thrust', 'Empowering', 'Lasting', 'Physical']}],
    ['Sea Current', {name: 'Sea Current', buffs: ['IcyVeins'], traits: ['Brutal'], debuffs: ['Slow'], types: ['Ice'], allTypes: ['Ice', 'Missile', 'Burst', 'Magical']}],
    ['Chaotic Surge', {name: 'Chaotic Surge', debuffs: ['Disarray'], types: ['Chaos'], allTypes: ['Chaos', 'Empowering', 'Lasting', 'Physical']}],
    ['Demonic Breath', {name: 'Demonic Breath', debuffs: ['Stun', 'Disarray'], types: ['Chaos'], allTypes: ['Chaos', 'Area', 'Frontal', 'Physical']}],
    ['Twin Impact', {name: 'Twin Impact', buffs: ['Aptitude'], debuffs: ['Fragility'], types: ['Projectile'], allTypes: ['Projectile', 'Missile', 'Frontal', 'Physical']}],
    ['Krakens Rum', {name: 'Krakens Rum', buffs: ['Cursed'], debuffs: ['Fragility'], types: ['Projectile'], allTypes: ['Projectile', 'Empowering', 'Lasting', 'Physical']}],
    ['Powder Keg', {name: 'Powder Keg', buffs: ['Cursed'], debuffs: ['Stun', 'Bleed'], types: ['Bomb'], allTypes: ['Bomb', 'Area', 'Magical']}],
    ['Eldritch Grasp', {name: 'Eldritch Grasp', buffs: ['Cursed'], buffDep: ['Cursed'], types: ['Swing'], allTypes: ['Swing', 'Area', 'Physical']}],
    ['Bull Charge', {name: 'Bull Charge', buffs: ['Ancestry', 'Purity'], debuffs: ['Dazed'], types: ['Holy'], allTypes: ['Holy', 'Missile', 'Frontal', 'Magical']}],
    ['Cobra Totem', {name: 'Cobra Totem', buffs:['Ancestry'], traits: ['Fortitude'], debuffs: ['Poison', 'Weakness'], types: ['Nature'], allTypes: ['Nature', 'Static', 'Summon', 'Physical']}],
    ['Stone Spiral', {name: 'Stone Spiral', buffs: ['Ancestry', 'Colossal'], traits: ['Fortitude'], types: ['Earth'], allTypes: ['Earth', 'Static', 'Summon', 'Physical']}],
    ['Chromatic Slash', {name: 'Chromatic Slash', types: [], allTypes: ['Arcane', 'Chaos', 'Ice', 'Nature', 'Fire', 'Electric', 'Shadow', 'Holy', 'Earth', 'Swing', 'Thrust', 'Slam', 'Frontal', 'Magical', 'Physical']}],
    ['Flame Syphon', {name: 'Flame Syphon', debuffs: ['Burn', 'Weakness'], types: ['Fire'], allTypes: ['Fire', 'Lasting', 'Frontal', 'Physical']}],
    ['High Voltage', {name: 'High Voltage', buffs: ['Electrified'], debuffs: ['Dazed'], traits: ['Devastating'], types: ['Electric'], allTypes: ['Electric', 'Lasting', 'Frontal', 'Physical']}],
    ['Ice Resonance', {name: 'Ice Resonance', buffs: ['IcyVeins'], debuffs: ['Slow'], types: ['Ice'], allTypes: ['Ice', 'Lasting', 'Frontal', 'Magical']}],
    ['Last Stand', {name: 'Last Stand', buffs: ['Finesse'], debuffs: ['Condemned', 'Fragility'], types: ['Swing'], allTypes: ['Swing', 'Lasting', 'Aura', 'Magical']}],
    ['Ruthlessness', {name: 'Ruthlessness', debuffDep: ['Condemned'], types: ['Shadow'], allTypes: ['Shadow', 'Empowering', 'Lasting', 'Area', 'Physical']}],
    ['Scorching Katana', {name: 'Scorching Katana', debuffs: ['Burn', 'Condemned'], debuffDep: ['Burn'], types: ['Fire'], allTypes: ['Fire', 'Missile', 'Magical', 'Physical']}],
]);