export const allSkills = new Map ([
    // ALL WEAPONS-----------------------------------------------------------------------------------

    ['Whirlwind', {name: 'Whirlwind', buffs: ['Bulwark', 'Finesse'], traits: [], debuffs: [], types: ['Swing']}],
    ['Throw Axe', {name: 'Throw Axe', buffs: ['Finesse'], traits: ['Piercing'], debuffs: [], types: ['Swing']}],
    ['Shockwave', {name: 'Shockwave', buffs: ['Colossal', 'Resilience'], traits: [], debuffs: [], types: ['Earth']}],
    ['Demolish', {name: 'Demolish', buffs: ['Colossal'], traits: ['Brutal'], debuffs: [], types: ['Earth']}],
    ['Thundering Slash', {name: 'Thundering Slash', buffs: ['Electrified'], traits: [], debuffs: [], types: ['Electric', 'Swing']}],
    ['Thunder Clap', {name: 'Thunder Clap', buffs: ['Electrified', 'Prowess'], traits: ['Brutal'], debuffs: [], types: ['Electric', 'Slam']}],
    ['Heavy Strike', {name: 'Heavy Strike', buffs: ['Prowess', 'Resilience'], traits: [], debuffs: ['Bleed'], types: ['Slam']}],
    ['Ground Slam', {name: 'Ground Slam', buffs: ['Prowess'], traits: [], debuffs: [], types: ['Slam']}],

    ['Fire Slash', {name: 'Fire Slash', buffs: ['Haste'], traits: [], debuffs: ['Burn'], types: ['Fire']}],
    ['Fire Walk', {name: 'Fire Walk', buffs: [], traits: [], debuffs: ['Burn'], types: ['Fire']}],
    ['Lightning Field', {name: 'Lightning Field', buffs: ['Electrified'], traits: [], debuffs: ['Dazed'], types: ['Electric']}],
    ['Overcharged Blast', {name: 'Overcharged Blast', buffs: ['Electrified'], traits: [], debuffs: [], types: ['Electric', 'Blast']}],
    ['Chaotic Inferno', {name: 'Chaotic Inferno', buffs: [], traits: [], debuffs: ['Disarray'], types: ['Chaos']}],
    ['Chaos Eruption', {name: 'Chaos Eruption', buffs: [], traits: ['Chaotic'], debuffs: [], types: ['Chaos']}],
    ['Dark Swarm', {name: 'Dark Swarm', buffs: [], traits: [], debuffs: ['Disoriented', 'Doom'], types: ['Shadow']}],
    ['Gathering Shadows', {name: 'Gathering Shadows', buffs: [], traits: [], debuffs: ['Doom'], types: ['Shadow']}],

    ['Mortar Shot', {name: 'Mortar Shot', buffs: [], traits: [], debuffs: ['Bleed'], types: ['Bomb']}],
    ['Bombardment', {name: 'Bombardment', buffs: [], traits: [], debuffs: ['Bleed'], types: ['Bomb']}],
    ['Buckshot', {name: 'Buckshot', buffs: ['Ammunition'], traits: ['Brutal'], debuffs: [], types: ['Blast']}],
    ['Power Blast', {name: 'Power Blast', buffs: ['Ammunition'], traits: ['Devastating'], debuffs: [], types: ['Blast']}],
    ['Pesticide Burst', {name: 'Pesticide Burst', buffs: [], traits: [], debuffs: ['Poison'], types: ['Nature']}],
    ['Threshing Blast', {name: 'Threshing Blast', buffs: ['Ammunition'], traits: [], debuffs: ['Poison'], types: ['Nature']}],
    ['Bolt Barrage', {name: 'Bolt Barrage', buffs: ['Aptitude'], traits: [], debuffs: [], types: ['Projectile']}],
    ['Cyclone Shot', {name: 'Cyclone Shot', buffs: ['Aptitude'], traits: [], debuffs: [], types: ['Projectile']}],

    ['Arcane Slash', {name: 'Arcane Slash', buffs: ['Finesse', 'Radiance'], traits: [], debuffs: [], types: ['Arcane', 'Swing']}],
    ['Arcane Overload', {name: 'Arcane Overload', buffs: ['Radiance'], traits: [], debuffs: [], types: ['Arcane', 'Swing']}],
    ['Slash', {name: 'Slash', buffs: ['Bulwark', 'Finesse'], traits: [], debuffs: [], types: ['Swing']}],
    ['Uppercut', {name: 'Uppercut', buffs: [], traits: [], debuffs: ['Stun'], types: ['Swing']}],
    ['Arctic Assault', {name: 'Arctic Assault', buffs: ['IcyVeins'], traits: [], debuffs: ['Disoriented'], types: ['Ice', 'Thrust']}],
    ['Frozen Blade', {name: 'Frozen Blade', buffs: ['IcyVeins'], traits: ['Devastating'], debuffs: [], types: ['Ice', 'Swing']}],
    ['Firestorm', {name: 'Firestorm', buffs: ['Haste'], traits: [], debuffs: ['Burn'], types: ['Fire', 'Swing']}],
    ['Fiery Blades', {name: 'Fiery Blades', buffs: [], traits: ['Cunning'], debuffs: ['Burn'], types: ['Fire', 'Swing']}],

    ['Arcane Missiles', {name: 'Arcane Missiles', buffs: ['Radiance'], traits: [], debuffs: ['Brittle'], types: ['Arcane']}],
    ['Arcane Explosion', {name: 'Arcane Explosion', buffs: ['Radiance'], traits: [], debuffs: ['Brittle'], types: ['Arcane']}],
    ['Fiery Missiles', {name: 'Fiery Missiles', buffs: [], traits: [], debuffs: ['Burn'], types: ['Fire']}],
    ['Fire Pillar', {name: 'Fire Pillar', buffs: [], traits: [], debuffs: ['Burn', 'Weakness'], types: ['Fire']}],
    ['Sacred Orb', {name: 'Sacred Orb', buffs: ['Purity'], traits: [], debuffs: ['Exposed'], types: ['Holy']}],
    ['Celestial Retribution', {name: 'Celestial Retribution', buffs: ['Purity'], traits: [], debuffs: ['Exposed'], types: ['Holy']}],
    ['Frost Beam', {name: 'Frost Beam', buffs: ['IcyVeins'], traits: [], debuffs: [], types: ['Ice']}],
    ['Ice Shield', {name: 'Ice Shield', buffs: [], traits: [], debuffs: ['Slow', 'Fragility'], types: ['Ice']}],

    ['Shoot', {name: 'Shoot', buffs: ['Aptitude'], traits: [], debuffs: [], types: ['Projectile']}],
    ['Rain Of Arrows', {name: 'Rain Of Arrows', buffs: ['Aptitude'], traits: [], debuffs: [], types: ['Projectile']}],
    ['Explosive Arrows', {name: 'Explosive Arrows', buffs: [], traits: ['Devastating'], debuffs: ['Bleed'], types: ['Bomb']}],
    ['Cluster Bomb', {name: 'Cluster Bomb', buffs: [], traits: [], debuffs: ['Bleed'], types: ['Bomb']}],
    ['Obscure Arrow', {name: 'Obscure Arrow', buffs: ['Aptitude'], traits: [], debuffs: ['Doom'], types: ['Shadow', 'Projectile']}],
    ['Void Trap', {name: 'Void Trap', buffs: [], traits: [], debuffs: ['Doom', 'Weakness'], types: ['Shadow', 'Bomb']}],
    ['Noxious Shot', {name: 'Noxious Shot', buffs: ['Aptitude'], traits: [], debuffs: ['Poison'], types: ['Nature']}],
    ['Venomous Volley', {name: 'Venomous Volley', buffs: [], traits: [], debuffs: ['Poison', 'Weakness'], types: ['Nature']}],

    ['Blades Of Light', {name: 'Blades Of Light', buffs: ['Purity', 'Prowess'], traits: [], debuffs: [], types: ['Holy', 'Swing']}],
    ['Holy Fire', {name: 'Holy Fire', buffs: ['Purity'], traits: [], debuffs: [], types: ['Holy']}],
    ['Heroic Strike', {name: 'Heroic Strike', buffs: ['Purity', 'Finesse'], traits: [], debuffs: [], types: ['Swing']}],
    ['Hammer Of Justice', {name: 'Hammer Of Justice', buffs: ['Purity', 'Finesse'], traits: ['Piercing'], debuffs: [], types: ['Holy', 'Swing']}],
    ['Radiant Light', {name: 'Radiant Light', buffs: ['Prowess', 'Radiance'], traits: [], debuffs: [], types: ['Arcane']}],
    ['Arcane Mace', {name: 'Arcane Mace', buffs: ['Radiance'], traits: [], debuffs: [], types: ['Arcane', 'Slam']}],
    ['Fissure Strike', {name: 'Fissure Strike', buffs: ['Prowess', 'Resilience'], traits: [], debuffs: [], types: ['Slam']}],
    ['Staggering Blow', {name: 'Staggering Blow', buffs: ['Prowess'], traits: [], debuffs: [], types: ['Slam']}],

    ['Chaotic Missile', {name: 'Chaotic Missile', buffs: [], traits: ['Chaotic', 'Piercing'], debuffs: [], types: ['Chaos']}],
    ['Unchained Chaos', {name: 'Unchained Chaos', buffs: [], traits: ['Chaotic'], debuffs: ['Disarray'], types: ['Chaos']}],
    ['Infected Shot', {name: 'Infected Shot', buffs: [], traits: [], debuffs: ['Poison'], types: ['Nature']}],
    ['Corrosion', {name: 'Corrosion', buffs: [], traits: [], debuffs: ['Poison'], types: ['Nature']}],
    ['Orbs Of Destruction', {name: 'Orbs Of Destruction', buffs: [], traits: [], debuffs: ['Burn'], types: ['Fire']}],
    ['Volcano Eruption', {name: 'Volcano Eruption', buffs: [], traits: [], debuffs: ['Burn'], types: ['Fire']}],
    ['Ripple Of Light', {name: 'Ripple Of Light', buffs: ['Purity'], traits: ['Brutal'], debuffs: [], types: ['Holy']}],
    ['Sanctified Orb', {name: 'Sanctified Orb', buffs: ['Purity'], traits: [], debuffs: ['Dazed'], types: ['Holy']}],

    ['Venomous Strike', {name: 'Venomous Strike', buffs: ['Finesse'], traits: [], debuffs: ['Poison'], types: ['Nature', 'Swing']}],
    ['Cobra Totem', {name: 'Cobra Totem', buffs: [], traits: ['Cunning'], debuffs: ['Poison', 'Weakness'], types: ['Nature']}],
    ['Wild Strike', {name: 'Wild Strike', buffs: ['Finesse'], traits: [], debuffs: [], types: ['Nature', 'Swing']}],
    ['Summon Swamp Boar', {name: 'Summon Swamp Boar', buffs: [], traits: [], debuffs: ['Fragility'], types: ['Nature', 'Swing']}],
    ['Brutal Slam', {name: 'Brutal Slam', buffs: ['Prowess'], traits: [], debuffs: [], types: ['Slam']}],
    ['Summon Cave Bear', {name: 'Summon Cave Bear', buffs: [], traits: ['Taunt'], debuffs: [], types: ['Nature', 'Slam']}],
    ['Spider Cocoon', {name: 'Spider Cocoon', buffs: [], traits: [], debuffs: ['Bleed'], types: ['Bomb']}],
    ['Summon Spider Queen', {name: 'Summon Spider Queen', buffs: [], traits: ['Cunning'], debuffs: ['Bleed', 'Weakness'], types: ['Bomb']}],

    ['Sinister Strike', {name: 'Sinister Strike', buffs: ['Form', 'Haste'], traits: ['Ambush'], debuffs: ['Bleed'], types: ['Thrust']}],
    ['Eviscerate', {name: 'Eviscerate', buffs: ['Form', 'Haste'], traits: ['Ambush'], debuffs: ['Bleed'], types: ['Thrust']}],
    ['Twin Daggers', {name: 'Twin Daggers', buffs: ['Finesse', 'Haste'], traits: ['Ambush'], debuffs: ['Bleed'], types: ['Swing']}],
    ['Backstab', {name: 'Backstab', buffs: ['Finesse', 'Haste'], traits: ['Ambush'], debuffs: [], types: ['Swing']}],
    ['Debilitating Bomb', {name: 'Debilitating Bomb', buffs: [], traits: [], debuffs: ['Bleed'], types: ['Bomb']}],
    ['Fan Of Bombs', {name: 'Fan Of Bombs', buffs: ['Finesse'], traits: [], debuffs: ['Bleed', 'Fragility'], types: ['Swing', 'Bomb']}],
    ['Shadow Stab', {name: 'Shadow Stab', buffs: ['Form'], traits: ['Ambush'], debuffs: ['Doom'], types: ['Shadow', 'Thrust']}],
    ['Reap', {name: 'Reap', buffs: [], traits: ['Ambush'], debuffs: ['Doom'], types: ['Shadow', 'Swing']}],

    ['Lightning Beam', {name: 'Lightning Beam', buffs: [], traits: [], debuffs: ['Dazed'], types: ['Electric']}],
    ['Call Lightning', {name: 'Call Lightning', buffs: ['Electrified'], traits: [], debuffs: [], types: ['Electric']}],
    ['Severe Cold', {name: 'Severe Cold', buffs: [], traits: [], debuffs: ['Disoriented', 'Slow'], types: ['Ice']}],
    ['Freezing Blow', {name: 'Freezing Blow', buffs: ['IcyVeins'], traits: [], debuffs: ['Slow'], types: ['Ice', 'Blast']}],
    ['Ray Of Fire', {name: 'Ray Of Fire', buffs: ['Haste'], traits: [], debuffs: ['Burn'], types: ['Fire']}],
    ['Heat Explosion', {name: 'Heat Explosion', buffs: [], traits: [], debuffs: ['Burn'], types: ['Fire']}],
    ['Contaminated Cut', {name: 'Contaminated Cut', buffs: [], traits: [], debuffs: [], types: ['Nature']}],
    ['Outbreak', {name: 'Outbreak', buffs: [], traits: [], debuffs: ['Poison'], types: ['Nature']}],

    ['Thrust', {name: 'Thrust', buffs: ['Form', 'Resilience'], traits: [], debuffs: [], types: ['Thrust']}],
    ['Shield Bash', {name: 'Shield Bash', buffs: ['Form'], traits: [], debuffs: [], types: ['Thrust']}],
    ['Jupiters Spear', {name: 'Jupiters Spear', buffs: ['Electrified'], traits: [], debuffs: ['Distracted'], types: ['Electric', 'Thrust']}],
    ['Summon Infantry', {name: 'Summon Infantry', buffs: [], traits: ['Cunning'], debuffs: ['Dazed'], types: ['Electric']}],
    ['Corrosive Spear', {name: 'Corrosive Spear', buffs: ['Vigor'], traits: [], debuffs: ['Poison'], types: ['Nature']}],
    ['Purging Slam', {name: 'Purging Slam', buffs: ['Vigor'], traits: [], debuffs: [], types: ['Nature', 'Slam']}],
    ['Piercing Flames', {name: 'Piercing Flames', buffs: [], traits: [], debuffs: ['Burn', 'Shattered'], types: ['Fire']}],
    ['Incinerating Spear', {name: 'Incinerating Spear', buffs: ['Form'], traits: [], debuffs: ['Burn'], types: ['Fire']}],

    ['Summon Skeletal Warrior', {name: 'Summon Skeletal Warrior', buffs: [], traits: ['Cunning'], debuffs: ['Crippled'], types: ['Shadow']}],
    ['Shadow Nova', {name: 'Shadow Nova', buffs: [], traits: [], debuffs: ['Doom'], types: ['Shadow']}],
    ['Spectral Guardian', {name: 'Spectral Guardian', buffs: ['Radiance'], traits: [], debuffs: [], types: ['Arcane']}],
    ['Soul Release', {name: 'Soul Release', buffs: ['Radiance'], traits: ['Piercing'], debuffs: [], types: ['Arcane']}],
    ['Summon Plague Rats', {name: 'Summon Plague Rats', buffs: [], traits: [], debuffs: ['Poison', 'Weakness'], types: ['Nature']}],
    ['Putrefy', {name: 'Putrefy', buffs: [], traits: [], debuffs: ['Poison'], types: ['Nature']}],
    ['Murder Of Crows', {name: 'Murder Of Crows', buffs: [], traits: ['Chaotic'], debuffs: [], types: ['Chaos']}],
    ['Carrion Crows', {name: 'Carrion Crows', buffs: [], traits: ['Chaotic'], debuffs: ['Disarray'], types: ['Chaos']}],

    ['Obliterate', {name: 'Obliterate', buffs: ['Finesse'], traits: [], debuffs: ['Doom'], types: ['Shadow', 'Swing']}],
    ['Ray Of Doom', {name: 'Ray Of Doom', buffs: [], traits: [], debuffs: ['Doom'], types: ['Shadow']}],
    ['Festering Strike', {name: 'Festering Strike', buffs: [], traits: [], debuffs: ['Poison', 'Weakness'], types: ['Nature', 'Swing']}],
    ['Lethal Blade', {name: 'Lethal Blade', buffs: [], traits: [], debuffs: [], types: ['Nature']}],
    ['Ravaging Strike', {name: 'Ravaging Strike', buffs: ['Bulwark', 'Finesse'], traits: [], debuffs: [], types: ['Swing']}],
    ['Carnage', {name: 'Carnage', buffs: ['Bulwark', 'Finesse'], traits: [], debuffs: [], types: ['Swing']}],
    ['Frost Strike', {name: 'Frost Strike', buffs: ['IcyVeins'], traits: [], debuffs: ['Fragility'], types: ['Ice', 'Swing']}],
    ['Glacial Affinity', {name: 'Glacial Affinity', buffs: [], traits: [], debuffs: [], types: ['Ice']}],

    ['Massive Slam', {name: 'Massive Slam', buffs: ['Prowess'], traits: [], debuffs: [], types: ['Slam']}],
    ['Spinning Staff', {name: 'Spinning Staff', buffs: ['Prowess'], traits: [], debuffs: ['Shattered'], types: ['Slam']}],
    ['Tempestuous Slash', {name: 'Tempestuous Slash', buffs: ['Electrified', 'Form'], traits: [], debuffs: [], types: ['Electric']}],
    ['Nimbus Lightning', {name: 'Nimbus Lightning', buffs: ['Electrified'], traits: [], debuffs: ['Dazed'], types: ['Electric']}],
    ['Gunpowder Strike', {name: 'Gunpowder Strike', buffs: [], traits: [], debuffs: ['Bleed', 'Weakness'], types: ['Bomb']}],
    ['Trickster Decoy', {name: 'Trickster Decoy', buffs: [], traits: [], debuffs: ['Bleed'], types: ['Bomb']}],
    ['Fracturing Blow', {name: 'Fracturing Blow', buffs: ['Colossal'], traits: [], debuffs: [], types: ['Earth']}],
    ['Rock Crushing', {name: 'Rock Crushing', buffs: ['Colossal', 'Resilience'], traits: [], debuffs: [], types: ['Earth']}],

    ['Burst Of Lead', {name: 'Burst Of Lead', buffs: ['Aptitude'], traits: ['Brutal'], debuffs: ['Dazed'], types: ['Projectile']}],
    ['Guided Missiles', {name: 'Guided Missiles', buffs: ['Aptitude'], traits: ['Impactful'], debuffs: [], types: ['Projectile']}],
    ['EZ Sentry', {name: 'EZ Sentry', buffs: ['Ammunition'], traits: ['Cunning'], debuffs: ['Bleed'], types: ['Blast']}],
    ['EZ Mechanical Spider', {name: 'EZ Mechanical Spider', buffs: ['Ammunition'], traits: ['Cunning'], debuffs: ['Shattered'], types: ['Blast']}],
    ['Energizer', {name: 'Energizer', buffs: ['Electrified'], traits: [], debuffs: [], types: ['Electric']}],
    ['Power Generator', {name: 'Power Generator', buffs: ['Electrified'], traits: [], debuffs: ['Dazed'], types: ['Electric']}],
    ['QT Bombuddy 1000', {name: 'QT Bombuddy 1000', buffs: [], traits: ['Impactful'], debuffs: [], types: ['Bomb']}],
    ['QT Land Surprise', {name: 'QT Land Surprise', buffs: [], traits: [], debuffs: ['Bleed'], types: ['Bomb']}],

    ['Glacial Trident', {name: 'Glacial Trident', buffs: ['IcyVeins'], traits: [], debuffs: ['Slow'], types: ['Ice', 'Thrust']}],
    ['Frozen Shard', {name: 'Frozen Shard', buffs: [], traits: [], debuffs: ['Slow'], types: ['Ice']}],
    ['Tidal Thrust', {name: 'Tidal Thrust', buffs: ['Form'], traits: [], debuffs: [], types: ['Thrust']}],
    ['Incisive Strike', {name: 'Incisive Strike', buffs: [], traits: ['Piercing'], debuffs: [], types: ['Thrust']}],
    ['Sanctified Throw', {name: 'Sanctified Throw', buffs: ['Purity'], traits: ['Devastating'], debuffs: ['Dazed'], types: ['Holy']}],
    ['Holy Frenzy', {name: 'Holy Frenzy', buffs: ['Purity'], traits: [], debuffs: ['Dazed'], types: ['Holy']}],
    ['Abyssal Fissure', {name: 'Abyssal Fissure', buffs: ['Colossal', 'Form'], traits: [], debuffs: [], types: ['Earth']}],
    ['Fury Of The Depths', {name: 'Fury Of The Depths', buffs: ['Resilience'], traits: [], debuffs: [], types: ['Earth']}],

    //ALL SKILLS --------------------------------------------------------------------------------------
    ['Piercing Shout', {name: 'Piercing Shout', buffs: [], traits: [], debuffs: ['Shattered'], types: ['Thrust']}],
    ['Savage Strike', {name: 'Savage Strike', buffs: ['Finesse'], traits: [], debuffs: [], types: ['Swing']}],
    ['Scent Of Blood', {name: 'Scent Of Blood' , buffs: [], traits: [], debuffs: [], types: ['Swing']}],
    ['Armor Shatter', {name: 'Armor Shatter', buffs: ['Prowess'], traits: [], debuffs: ['Shattered'], types: ['Slam']}],
    ['Bladestorm', {name: 'Bladestorm', buffs: [], traits: [], debuffs: [], types: ['Swing']}],
    ['Bloody Saw', {name: 'Bloody Saw', buffs: ['Finesse'], traits: [], debuffs: ['Bleed'], types: ['Swing']}],
    ['Body Slam', {name: 'Body Slam', buffs: ['Prowess'], traits: [], debuffs: [], types: ['Slam']}],
    ['Chain Lightning', {name: 'Chain Lightning', buffs: ['Electrified'], traits: [], debuffs: ['Distracted'], types: ['Electric']}],
    ['Chromatic Bolt', {name: 'Chromatic Bolt', buffs: [], traits: [], debuffs: [], types: []}],
    ['Double Slash', {name: 'Double Slash', buffs: ['Bulwark', 'Finesse'], traits: [], debuffs: ['Debilitated'], types: ['Swing']}],
    ['Earth bolt', {name: 'Earth bolt', buffs: ['Colossal'], traits: [], debuffs: [], types: ['Earth']}],
    ['Earthquake', {name: 'Earthquake', buffs: ['Colossal'], traits: [], debuffs: ['Brittle'], types: ['Earth']}],
    ['Earth Shield', {name: 'Earth Shield', buffs: ['Resilience'], traits: [], debuffs: [], types: ['Earth']}],
    ['Flurry', {name: 'Flurry', buffs: ['Form'], traits: [], debuffs: ['Bleed'], types: ['Thrust']}],
    ['Ground Break', {name: 'Ground Break', buffs: ['Prowess'], traits: ['Piercing'], debuffs: [], types: ['Slam']}],
    ['Heartrending Strike', {name: 'Heartrending Strike', buffs: ['Bulwark', 'Finesse'], traits: [], debuffs: ['Fragility'], types: ['Swing']}],
    ['Lightning bolt', {name: 'Lightning bolt', buffs: ['Electrified'], traits: ['Devastating'], debuffs: [], types: ['Electric']}],
    ['Lightning Surge', {name: 'Lightning Surge', buffs: [], traits: [], debuffs: ['Dazed'], types: ['Electric']}],
    ['On Guard', {name: 'On Guard', buffs: ['Bulwark', 'Form'], traits: [], debuffs: ['Exposed'], types: ['Thrust']}],
    ['Power Conductor', {name: 'Power Conductor', buffs: ['Electrified'], traits: [], debuffs: ['Dazed'], types: ['Electric']}],
    ['Quick Strike', {name: 'Quick Strike', buffs: ['Form', 'Haste'], traits: [], debuffs: [], types: ['Thrust']}],
    ['Resonant Slam', {name: 'Resonant Slam', buffs: ['Prowess', 'Resilience'], traits: ['Brutal'], debuffs: [], types: ['Slam']}],
    ['Rolling Boulder', {name: 'Rolling Boulder', buffs: [], traits: [], debuffs: ['Stun'], types: ['Earth']}],
    ['Seismic Shock', {name: 'Seismic Shock', buffs: ['Prowess', 'Resilience'], traits: [], debuffs: [], types: ['Slam']}],
    ['Sharp Spear', {name: 'Sharp Spear', buffs: ['Haste', 'Form'], traits: ['Piercing'], debuffs: [], types: ['Thrust']}],
    ['Shockwave Totem', {name: 'Shockwave Totem', buffs: [], traits: [], debuffs: ['Dazed'], types: ['Earth']}],
    ['Spear Trap', {name: 'Spear Trap', buffs: ['Form'], traits: [], debuffs: ['Exposed'], types: ['Thrust']}],
    ['Subdue', {name: 'Subdue', buffs: [], traits: [], debuffs: [], types: ['Swing']}],
    ['Sugar Rush', {name: 'Sugar Rush', buffs: [], traits: [], debuffs: [], types: ['Thrust']}],
    ['Thunder strike', {name: 'Thunder strike', buffs: ['Electrified'], traits: [], debuffs: ['Stun'], types: ['Electric']}],
    ['Titans Cleaver', {name: 'Titans Cleaver', buffs: ['Finesse'], traits: [], debuffs: [], types: ['Swing']}],
    ['Conflagrate', {name: 'Conflagrate', buffs: [], traits: [], debuffs: [], types: ['Fire']}],
    ['Fire Wall', {name: 'Fire Wall', buffs: [], traits: [], debuffs: ['Burn', 'Weakness'], types: ['Fire']}],
    ['Meteor Shower', {name: 'Meteor Shower', buffs: [], traits: [], debuffs: [], types: ['Fire']}],
    ['Arcane Beam', {name: 'Arcane Beam', buffs: [], traits: [], debuffs: ['Brittle'], types: ['Arcane']}],
    ['Arcane Disc', {name: 'Arcane Disc', buffs: ['Radiance'], traits: ['Piercing'], debuffs: [], types: ['Arcane']}],
    ['Arcane Power', {name: 'Arcane Power', buffs: [], traits: [], debuffs: [], types: ['Arcane']}],
    ['Arcane Sparks', {name: 'Arcane Sparks', buffs: ['Radiance'], traits: ['Piercing'], debuffs: [], types: ['Arcane']}],
    ['Bloodlust', {name: 'Bloodlust', buffs: [], traits: [], debuffs: [], types: ['Chaos']}],
    ['Chaos Bolt', {name: 'Chaos Bolt', buffs: [], traits: ['Chaotic', 'Precise'], debuffs: [], types: ['Chaos']}],
    ['Chaotic Explosion', {name: 'Chaotic Explosion', buffs: [], traits: ['Chaotic', 'Impactful'], debuffs: [], types: ['Chaos']}],
    ['Combustion', {name: 'Combustion', buffs: [], traits: [], debuffs: ['Burn'], types: ['Fire']}],
    ['Death Claw', {name: 'Death Claw', buffs: [], traits: ['Chaotic'], debuffs: [], types: ['Chaos']}],
    ['Death Vortex', {name: 'Death Vortex', buffs: [], traits: [], debuffs: ['Doom'], types: ['Shadow']}],
    ['Fire bolt', {name: 'Fire bolt', buffs: [], traits: [], debuffs: ['Burn', 'Weakness'], types: ['Fire']}],
    ['Flamethrower', {name: 'Flamethrower', buffs: [], traits: [], debuffs: ['Burn'], types: ['Fire']}],
    ['Flame Wave', {name: 'Flame Wave', buffs: [], traits: [], debuffs: ['Burn', 'Shattered'], types: ['Fire']}],
    ['Frenzied Bunnies', {name: 'Frenzied Bunnies', buffs: [], traits: [], debuffs: ['Disarray'], types: ['Chaos']}],
    ['Magic Missiles', {name: 'Magic Missiles', buffs: [], traits: [], debuffs: ['Fragility'], types: ['Arcane']}],
    ['Meteor', {name: 'Meteor', buffs: [], traits: [], debuffs: ['Burn', 'Stun'], types: ['Fire']}],
    ['Shadow Bolt', {name: 'Shadow Bolt', buffs: ['Aptitude'], traits: [], debuffs: ['Doom'], types: ['Shadow']}],
    ['Shadow orb', {name: 'Shadow orb', buffs: [], traits: [], debuffs: ['Doom'], types: ['Shadow']}],
    ['Shadow Spikes', {name: 'Shadow Spikes', buffs: [], traits: [], debuffs: [], types: ['Shadow']}],
    ['Summon Chaos Golem', {name: 'Summon Chaos Golem', buffs: [], traits: ['Taunt'], debuffs: ['Disarray'], types: ['Chaos']}],
    ['Void', {name: 'Void', buffs: [], traits: [], debuffs: ['Doom'], types: ['Shadow']}],
    ['Bear Trap', {name: 'Bear Trap', buffs: [], traits: [], debuffs: ['Bleed', 'Weakness'], types: ['Bomb']}],
    ['Shrapnel Mine', {name: 'Shrapnel Mine', buffs: [], traits: [], debuffs: ['Bleed'], types: ['Bomb']}],
    ['Weakening Grenade', {name: 'Weakening Grenade', buffs: [], traits: ['Impactful'], debuffs: ['Bleed', 'Disoriented'], types: ['Bomb']}],
    ['Acid Rain', {name: 'Acid Rain', buffs: [], traits: [], debuffs: ['Poison'], types: ['Nature']}],
    ['Bladed Chakram', {name: 'Bladed Chakram', buffs: ['Aptitude'], traits: ['Piercing'], debuffs: [], types: ['Projectile']}],
    ['Bomb Barrage', {name: 'Bomb Barrage', buffs: [], traits: [], debuffs: ['Bleed'], types: ['Bomb']}],
    ['Camors Arrow', {name: 'Camors Arrow', buffs: [], traits: [], debuffs: ['Fragility', 'Stun'], types: ['Projectile']}],
    ['Egg Shooter', {name: 'Egg Shooter', buffs: [], traits: [], debuffs: ['Dazed'], types: ['Projectile']}],
    ['Explosive Shot', {name: 'Explosive Shot', buffs: ['Ammunition'], traits: [], debuffs: ['Shattered'], types: ['Blast']}],
    ['Explosive Trap', {name: 'Explosive Trap', buffs: [], traits: [], debuffs: ['Bleed', 'Disoriented'], types: ['Bomb']}],
    ['Frag Shot', {name: 'Frag Shot', buffs: ['Aptitude'], traits: [], debuffs: ['Dazed'], types: ['Projectile']}],
    ['Heartbreak Orbs', {name: 'Heartbreak Orbs', buffs: ['Aptitude'], traits: ['Precise'], debuffs: [], types: ['Projectile']}],
    ['Mine Field', {name: 'Mine Field', buffs: [], traits: [], debuffs: ['Bleed'], types: ['Bomb']}],
    ['Napalm Blast', {name: 'Napalm Blast', buffs: ['Ammunition'], traits: [], debuffs: ['Shattered'], types: ['Blast']}],
    ['Pestilence', {name: 'Pestilence', buffs: [], traits: [], debuffs: ['Poison'], types: ['Nature']}],
    ['Poison Bolt', {name: 'Poison Bolt', buffs: [], traits: [], debuffs: ['Poison'], types: ['Nature']}],
    ['Poison Cloud', {name: 'Poison Cloud', buffs: [], traits: [], debuffs: ['Poison', 'Weakness'], types: ['Nature']}],
    ['Poison Puddle', {name: 'Poison Puddle', buffs: [], traits: [], debuffs: ['Poison', 'Debilitated'], types: ['Nature']}],
    ['Rapid Barrage', {name: 'Rapid Barrage', buffs: ['Ammunition'], traits: [], debuffs: [], types: ['Blast']}],
    ['Shrapnel Bomb', {name: 'Shrapnel Bomb', buffs: [], traits: [], debuffs: [], types: ['Bomb']}],
    ['Shrapnel Shot', {name: 'Shrapnel Shot', buffs: ['Ammunition'], traits: [], debuffs: ['Bleed'], types: ['Blast']}],
    ['Spread Shot', {name: 'Spread Shot', buffs: ['Aptitude'], traits: [], debuffs: ['Dazed'], types: ['Projectile']}],
    ['Storm Of Arrows', {name: 'Storm Of Arrows', buffs: [], traits: [], debuffs: [], types: ['Projectile']}],
    ['Suction Bomb', {name: 'Suction Bomb', buffs: [], traits: [], debuffs: ['Bleed'], types: ['Bomb']}],
    ['Summon Ballista', {name: 'Summon Ballista', buffs: [], traits: ['Piercing', 'Cunning'], debuffs: [], types: ['Projectile']}],
    ['Surprise Gift', {name: 'Surprise Gift', buffs: [], traits: [], debuffs: ['Bleed', 'Weakness'], types: ['Bomb']}],
    ['Weakening Shot', {name: 'Weakening Shot', buffs: ['Ammunition'], traits: [], debuffs: ['Exposed'], types: ['Blast']}],
    ['Arcane Assault', {name: 'Arcane Assault', buffs: ['Radiance'], traits: [], debuffs: [], types: ['Arcane', 'Thrust']}],
    ['Arcane Blade', {name: 'Arcane Blade', buffs: ['Finesse', 'Radiance'], traits: [], debuffs: [], types: ['Arcane', 'Swing']}],
    ['Arcane Rift', {name: 'Arcane Rift', buffs: [], traits: [], debuffs: ['Fragility'], types: ['Arcane']}],
    ['Avalanche', {name: 'Avalanche', buffs: [], traits: [], debuffs: ['Fragility', 'Slow'], types: ['Ice']}],
    ['Blizzard', {name: 'Blizzard', buffs: [], traits: [], debuffs: ['Slow'], types: ['Ice']}],
    ['Frost Bolt', {name: 'Frost Bolt', buffs: ['IcyVeins'], traits: [], debuffs: [], types: ['Ice']}],
    ['Frost Totem', {name: 'Frost Totem', buffs: [], traits: ['Cunning'], debuffs: ['Slow'], types: ['Ice']}],
    ['Glacier', {name: 'Glacier', buffs: [], traits: [], debuffs: ['Disoriented', 'Slow'], types: ['Ice']}],
    ['Ice Vortex', {name: 'Ice Vortex', buffs: [], traits: [], debuffs: ['Slow'], types: ['Ice']}],
    ['Summon Helper Elves', {name: 'Summon Helper Elves', buffs: [], traits: ['Cunning'], debuffs: ['Slow'], types: ['Ice']}],
    ['Arcane Conjuration', {name: 'Arcane Conjuration', buffs: ['Radiance'], traits: [], debuffs: ['Brittle'], types: ['Arcane']}],
    ['Arcane Orb', {name: 'Arcane Orb', buffs: ['Finesse', 'Radiance'], traits: [], debuffs: [], types: ['Arcane']}],
    ['Arcane shield', {name: 'Arcane shield', buffs: [], traits: [], debuffs: [], types: ['Arcane']}],
    ['Holy Beam', {name: 'Holy Beam', buffs: ['Purity', 'Prowess'], traits: [], debuffs: [], types: ['Holy']}],
    ['Light Beam', {name: 'Light Beam', buffs: [], traits: [], debuffs: ['Exposed'], types: ['Holy']}],
    ['Living Weapons', {name: 'Living Weapons', buffs: [], traits: [], debuffs: ['Dazed'], types: ['Holy']}],
    ['Might', {name: 'Might', buffs: [], traits: [], debuffs: [], types: ['Holy']}],
    ['Smite', {name: 'Smite', buffs: ['Purity'], traits: [], debuffs: [], types: ['Holy']}],
    ['Ricochet Shot', {name: 'Ricochet Shot', buffs: ['Aptitude'], traits: ['Piercing'], debuffs: [], types: ['Projectile']}],
    ['Sniper Shot', {name: 'Sniper Shot', buffs: [], traits: ['Devastating', 'Precise'], debuffs: [], types: ['Projectile']}],
    ['Split Shot', {name: 'Split Shot', buffs: ['Aptitude'], traits: [], debuffs: ['Dazed'], types: ['Projectile']}],
    ['Beacon Of Light', {name: 'Beacon Of Light', buffs: ['Purity'], traits: [], debuffs: ['Exposed'], types: ['Holy']}],
    ['Penance', {name: 'Penance', buffs: ['Purity'], traits: [], debuffs: ['Dazed'], types: ['Holy']}],
    ['Templars Verdict', {name: 'Templars Verdict', buffs: ['Purity'], traits: ['Devastating'], debuffs: [], types: ['Holy', 'Swing']}],
    ['Chaos Totem', {name: 'Chaos Totem', buffs: [], traits: ['Cunning'], debuffs: ['Disarray'], types: ['Chaos']}],
    ['Chaos Wave', {name: 'Chaos Wave', buffs: [], traits: ['Brutal', 'Chaotic'], debuffs: [], types: ['Chaos']}],
    ['Manifestations Of Chaos', {name: 'Manifestations Of Chaos', buffs: [], traits: ['Chaotic'], debuffs: [], types: ['Chaos']}],
    ['Bestial Wrath', {name: 'Bestial Wrath', buffs: [], traits: [], debuffs: [], types: ['Nature']}],
    ['Summon Battle Moose', {name: 'Summon Battle Moose', buffs: [], traits: ['Taunt'], debuffs: ['Stun'], types: ['Nature', 'Slam']}],
    ['Summon War Tiger', {name: 'Summon War Tiger', buffs: [], traits: ['Cunning'], debuffs: ['Bleed'], types: ['Nature', 'Swing']}],
    ['Rupture', {name: 'Rupture', buffs: ['Form'], traits: [], debuffs: ['Stun'], types: ['Thrust']}],
    ['Shadow Step', {name: 'Shadow Step', buffs: [], traits: [], debuffs: ['Doom'], types: ['Shadow']}],
    ['Smoke Bomb', {name: 'Smoke Bomb', buffs: [], traits: ['Ambush'], debuffs: ['Disoriented'], types: ['Shadow', 'Bomb']}],
    ['Summon Assassin Enclave', {name: 'Summon Assassin Enclave', buffs: [], traits: ['Cunning'], debuffs: ['Bleed'], types: ['Thrust']}],
    ['Frozen Warhammer', {name: 'Frozen Warhammer', buffs: ['Prowess', 'IcyVeins'], traits: [], debuffs: [], types: ['Ice', 'Slam']}],
    ['Lava Shield', {name: 'Lava Shield', buffs: [], traits: [], debuffs: ['Burn'], types: ['Fire']}],
    ['Tornado', {name: 'Tornado', buffs: ['Electrified'], traits: ['Devastating'], debuffs: [], types: ['Electric']}],
    ['Intimidating Shout', {name: 'Intimidating Shout', buffs: [], traits: [], debuffs: ['Distracted'], types: ['Thrust']}],
    ['Shield Wall', {name: 'Shield Wall', buffs: [], traits: [], debuffs: [], types: ['Thrust']}],
    ['Storm Of Spears', {name: 'Storm Of Spears', buffs: [], traits: [], debuffs: [], types: ['Thrust']}],
    ['Summon Putrid Hounds', {name: 'Summon Putrid Hounds', buffs: [], traits: ['Cunning'], debuffs: [], types: ['Nature']}],
    ['Summon Skeletal Archer', {name: 'Summon Skeletal Archer', buffs: [], traits: ['Cunning'], debuffs: [], types: ['Shadow']}],
    ['Summon Skeletal Mage', {name: 'Summon Skeletal Mage', buffs: [], traits: [], debuffs: ['Doom'], types: ['Shadow']}],
    ['Contagion', {name: 'Contagion', buffs: [], traits: [], debuffs: [], types: ['Nature']}],
    ['Path Of Decay', {name: 'Path Of Decay', buffs: [], traits: [], debuffs: ['Poison'], types: ['Nature']}],
    ['Shadow Grasp', {name: 'Shadow Grasp', buffs: [], traits: [], debuffs: [], types: ['Shadow', 'Swing']}],
    ['Electric Strike', {name: 'Electric Strike', buffs: ['Electrified'], traits: [], debuffs: [], types: ['Electric']}],
    ['Expansive Throw', {name: 'Expansive Throw', buffs: ['Prowess'], traits: [], debuffs: [], types: ['Slam']}],
    ['Whirling Defense', {name: 'Whirling Defense', buffs: ['Prowess', 'Resilience'], traits: ['Brutal'], debuffs: [], types: ['Slam']}],
    ['Ammo Box', {name: 'Ammo Box', buffs: ['Ammunition'], traits: [], debuffs: [], types: ['Blast']}],
    ['Heavy Artillery', {name: 'Heavy Artillery', buffs: [], traits: ['Impactful'], debuffs: ['Bleed', 'Weakness'], types: ['Bomb']}],
    ['Portable Nuke', {name: 'Portable Nuke', buffs: [], traits: ['Devastating'], debuffs: ['Disoriented', 'Stun'], types: ['Bomb']}],
    ['Jawstorm', {name: 'Jawstorm', buffs: ['IcyVeins'], traits: [], debuffs: ['Fragility'], types: ['Ice']}],
    ['Precision Wave', {name: 'Precision Wave', buffs: [], traits: [], debuffs: [], types: ['Thrust']}],
    ['Sea Current', {name: 'Sea Current', buffs: ['IcyVeins'], traits: ['Brutal'], debuffs: ['Slow'], types: ['Ice']}],
]);