export const all = [
    {
        hero: 'barbarian',
        wArray: [
            {wName: 'Whirlwind', buffs: ['Bulwark', 'Finesse'], traits: [], debuffs: []},
            {wName: 'Throw Axe', buffs: ['Finesse'], traits: ['Piercing'], debuffs: []},
            {wName: 'Shockwave', buffs: ['Colossal', 'Resilience'], traits: [], debuffs: []},
            {wName: 'Demolish', buffs: ['Colossal'], traits: ['Brutal'], debuffs: []},
            {wName: 'Thundering Slash', buffs: ['Electrified'], traits: [], debuffs: []},
            {wName: 'Thunder Clap', buffs: ['Electrified', 'Prowess'], traits: ['Brutal'], debuffs: []},
            {wName: 'Heavy Strike', buffs: ['Prowess', 'Resilience'], traits: [], debuffs: ['Bleed']},
            {wName: 'Ground Slam', buffs: ['Prowess'], traits: [], debuffs: []},
        ],
        sArray: [
            {sName: 'Piercing Shout', buffs: [], traits: [], debuffs: ['Shattered']},
            {sName: 'Savage Strike', buffs: ['Finesse'], traits: [], debuffs: []},
            {sName: 'Scent Of Blood' , buffs: [], traits: [], debuffs: []},
            {sName: 'Armor Shatter', buffs: ['Prowess'], traits: [], debuffs: ['Shattered']},
            {sName: 'Bladestorm', buffs: [], traits: [], debuffs: []},
            {sName: 'Bloody Saw', buffs: ['Finesse'], traits: [], debuffs: ['Bleed']},
            {sName: 'Body Slam', buffs: ['Prowess'], traits: [], debuffs: []},
            {sName: 'Chain Lightning', buffs: ['Electrified'], traits: [], debuffs: ['Distracted']},
            {sName: 'Chromatic Bolt', buffs: [], traits: [], debuffs: []},
            {sName: 'Double Slash', buffs: ['Bulwark', 'Finesse'], traits: [], debuffs: ['Debilitated']},
            {sName: 'Earth bolt', buffs: ['Colossal'], traits: [], debuffs: []},
            {sName: 'Earthquake', buffs: ['Colossal'], traits: [], debuffs: ['Brittle']},
            {sName: 'Earth Shield', buffs: ['Resilience'], traits: [], debuffs: []},
            {sName: 'Flurry', buffs: ['Form'], traits: [], debuffs: ['Bleed']},
            {sName: 'Ground Break', buffs: ['Prowess'], traits: ['Piercing'], debuffs: []},
            {sName: 'Heartrending Strike', buffs: ['Bulwark', 'Finesse'], traits: [], debuffs: ['Fragility']},
            {sName: 'Lightning bolt', buffs: ['Electrified'], traits: ['Devastating'], debuffs: []},
            {sName: 'Lightning Surge', buffs: [], traits: [], debuffs: ['Dazed']},
            {sName: 'On Guard', buffs: ['Bulwark', 'Form'], traits: [], debuffs: ['Exposed']},
            {sName: 'Power Conductor', buffs: ['Electrified'], traits: [], debuffs: ['Dazed']},
            {sName: 'Quick Strike', buffs: ['Form', 'Haste'], traits: [], debuffs: []},
            {sName: 'Resonant Slam', buffs: ['Prowess', 'Resilience'], traits: ['Brutal'], debuffs: []},
            {sName: 'Rolling Boulder', buffs: [], traits: [], debuffs: ['Stun']},
            {sName: 'Seismic Shock', buffs: ['Prowess', 'Resilience'], traits: [], debuffs: []},
            {sName: 'Sharp Spear', buffs: ['Haste', 'Form'], traits: ['Piercing'], debuffs: []},
            {sName: 'Shockwave Totem', buffs: [], traits: [], debuffs: ['Dazed']},
            {sName: 'Spear Trap', buffs: ['Form'], traits: [], debuffs: ['Exposed']},
            {sName: 'Subdue', buffs: [], traits: [], debuffs: []},
            {sName: 'Sugar Rush', buffs: [], traits: [], debuffs: []},
            {sName: 'Thunder strike', buffs: ['Electrified'], traits: [], debuffs: ['Stun']},
            {sName: 'Titans Cleaver', buffs: ['Finesse'], traits: [], debuffs: []},
        ],
    },
    {
        hero: 'pyromancer',
        wArray: [
            {wName: 'Fire Slash', buffs: ['Haste'], traits: [], debuffs: ['Burn']},
            {wName: 'Fire Walk', buffs: [], traits: [], debuffs: ['Burn']},
            {wName: 'Lightning Field', buffs: ['Electrified'], traits: [], debuffs: ['Dazed']},
            {wName: 'Overcharged Blast', buffs: ['Electrified'], traits: [], debuffs: []},
            {wName: 'Chaotic Inferno', buffs: [], traits: [], debuffs: ['Disarray']},
            {wName: 'Chaos Eruption', buffs: [], traits: ['Chaotic'], debuffs: []},
            {wName: 'Dark Swarm', buffs: [], traits: [], debuffs: ['Disoriented', 'Doom']},
            {wName: 'Gathering Shadows', buffs: [], traits: [], debuffs: ['Doom']},
        ],
        sArray: [
            {sName: 'Conflagrate', buffs: [], traits: [], debuffs: []},
            {sName: 'Fire Wall', buffs: [], traits: [], debuffs: ['Burn', 'Weakness']},
            {sName: 'Meteor Shower', buffs: [], traits: [], debuffs: []},
            {sName: 'Arcane Beam', buffs: [], traits: [], debuffs: ['Brittle']},
            {sName: 'Arcane Disc', buffs: ['Radiance'], traits: ['Piercing'], debuffs: []},
            {sName: 'Arcane Power', buffs: [], traits: [], debuffs: []},
            {sName: 'Arcane Sparks', buffs: ['Radiance'], traits: ['Piercing'], debuffs: []},
            {sName: 'Bloodlust', buffs: [], traits: [], debuffs: []},
            {sName: 'Chain Lightning', buffs: ['Electrified'], traits: [], debuffs: ['Distracted']},
            {sName: 'Chaos Bolt', buffs: [], traits: ['Chaotic', 'Precise'], debuffs: []},
            {sName: 'Chaotic Explosion', buffs: [], traits: ['Chaotic', 'Impactful'], debuffs: []},
            {sName: 'Chromatic Bolt', buffs: [], traits: [], debuffs: []},
            {sName: 'Combustion', buffs: [], traits: [], debuffs: ['Burn']},
            {sName: 'Death Claw', buffs: [], traits: ['Chaotic'], debuffs: []},
            {sName: 'Death Vortex', buffs: [], traits: [], debuffs: ['Doom']},
            {sName: 'Fire bolt', buffs: [], traits: [], debuffs: ['Burn', 'Weakness']},
            {sName: 'Flamethrower', buffs: [], traits: [], debuffs: ['Burn']},
            {sName: 'Flame Wave', buffs: [], traits: [], debuffs: ['Burn', 'Shattered']},
            {sName: 'Frenzied Bunnies', buffs: [], traits: [], debuffs: ['Disarray']},
            {sName: 'Lightning bolt', buffs: ['Electrified'], traits: ['Devastating'], debuffs: []},
            {sName: 'Lightning Surge', buffs: [], traits: [], debuffs: ['Dazed']},
            {sName: 'Magic Missiles', buffs: [], traits: [], debuffs: ['Fragility']},
            {sName: 'Meteor', buffs: [], traits: [], debuffs: ['Burn', 'Stun']},
            {sName: 'Power Conductor', buffs: ['Electrified'], traits: [], debuffs: ['Dazed']},
            {sName: 'Shadow Bolt', buffs: ['Aptitude'], traits: [], debuffs: ['Doom']},
            {sName: 'Shadow orb', buffs: [], traits: [], debuffs: ['Doom']},
            {sName: 'Shadow Spikes', buffs: [], traits: [], debuffs: []},
            {sName: 'Summon Chaos Golem', buffs: [], traits: ['Taunt'], debuffs: ['Disarray']},
            {sName: 'Thunder strike', buffs: ['Electrified'], traits: [], debuffs: ['Stun']},
            {sName: 'Void', buffs: [], traits: [], debuffs: ['Doom']},
        ],
    },
    {
        hero: 'houndmaster',
        wArray: [
            {wName: 'Mortar Shot', buffs: [], traits: [], debuffs: ['Bleed']},
            {wName: 'Bombardment', buffs: [], traits: [], debuffs: ['Bleed']},
            {wName: 'Buckshot', buffs: ['Ammunition'], traits: ['Brutal'], debuffs: []},
            {wName: 'Power Blast', buffs: ['Ammunition'], traits: ['Devastating'], debuffs: []},
            {wName: 'Pesticide Burst', buffs: [], traits: [], debuffs: ['Poison']},
            {wName: 'Threshing Blast', buffs: ['Ammunition'], traits: [], debuffs: ['Poison']},
            {wName: 'Bolt Barrage', buffs: ['Aptitude'], traits: [], debuffs: []},
            {wName: 'Cyclone Shot', buffs: ['Aptitude'], traits: [], debuffs: []},
        ],
        sArray: [
            {sName: 'Bear Trap', buffs: [], traits: [], debuffs: ['Bleed', 'Weakness']},
            {sName: 'Shrapnel Mine', buffs: [], traits: [], debuffs: ['Bleed']},
            {sName: 'Weakening Grenade', buffs: [], traits: ['Impactful'], debuffs: ['Bleed', 'Disoriented']},
            {sName: 'Acid Rain', buffs: [], traits: [], debuffs: ['Poison']},
            {sName: 'Bladed Chakram', buffs: ['Aptitude'], traits: ['Piercing'], debuffs: []},
            {sName: 'Bomb Barrage', buffs: [], traits: [], debuffs: ['Bleed']},
            {sName: 'Camors Arrow', buffs: [], traits: [], debuffs: ['Fragility', 'Stun']},
            {sName: 'Chromatic Bolt', buffs: [], traits: [], debuffs: []},
            {sName: 'Combustion', buffs: [], traits: [], debuffs: ['Burn']},
            {sName: 'Egg Shooter', buffs: [], traits: [], debuffs: ['Dazed']},
            {sName: 'Explosive Shot', buffs: ['Ammunition'], traits: [], debuffs: ['Shattered']},
            {sName: 'Explosive Trap', buffs: [], traits: [], debuffs: ['Bleed', 'Disoriented']},
            {sName: 'Fire bolt', buffs: [], traits: [], debuffs: ['Burn', 'Weakness']},
            {sName: 'Flamethrower', buffs: [], traits: [], debuffs: ['Burn']},
            {sName: 'Flame Wave', buffs: [], traits: [], debuffs: ['Burn', 'Shattered']},
            {sName: 'Frag Shot', buffs: ['Aptitude'], traits: [], debuffs: ['Dazed']},
            {sName: 'Heartbreak Orbs', buffs: ['Aptitude'], traits: ['Precise'], debuffs: []},
            {sName: 'Meteor', buffs: [], traits: [], debuffs: ['Burn', 'Stun']},
            {sName: 'Mine Field', buffs: [], traits: [], debuffs: ['Bleed']},
            {sName: 'Napalm Blast', buffs: ['Ammunition'], traits: [], debuffs: ['Shattered']},
            {sName: 'Pestilence', buffs: [], traits: [], debuffs: ['Poison']},
            {sName: 'Poison Bolt', buffs: [], traits: [], debuffs: ['Poison']},
            {sName: 'Poison Cloud', buffs: [], traits: [], debuffs: ['Poison', 'Weakness']},
            {sName: 'Poison Puddle', buffs: [], traits: [], debuffs: ['Poison', 'Debilitated']},
            {sName: 'Rapid Barrage', buffs: ['Ammunition'], traits: [], debuffs: []},
            {sName: 'Shrapnel Bomb', buffs: [], traits: [], debuffs: []},
            {sName: 'Shrapnel Shot', buffs: ['Ammunition'], traits: [], debuffs: ['Bleed']},
            {sName: 'Spread Shot', buffs: ['Aptitude'], traits: [], debuffs: ['Dazed']},
            {sName: 'Storm Of Arrows', buffs: [], traits: [], debuffs: []},
            {sName: 'Suction Bomb', buffs: [], traits: [], debuffs: ['Bleed']},
            {sName: 'Summon Ballista', buffs: [], traits: ['Piercing', 'Cunning'], debuffs: []},
            {sName: 'Surprise Gift', buffs: [], traits: [], debuffs: ['Bleed', 'Weakness']},
            {sName: 'Weakening Shot', buffs: ['Ammunition'], traits: [], debuffs: ['Exposed']},
        ],
    },
    {
        hero: 'spellblade',
        wArray: [

            {wName: 'Arcane Slash', buffs: ['Finesse', 'Radiance'], traits: [], debuffs: []},
            {wName: 'Arcane Overload', buffs: ['Radiance'], traits: [], debuffs: []},
            {wName: 'Slash', buffs: ['Bulwark', 'Finesse'], traits: [], debuffs: []},
            {wName: 'Uppercut', buffs: [], traits: [], debuffs: ['Stun']},
            {wName: 'Arctic Assault', buffs: ['IcyVeins'], traits: [], debuffs: ['Disoriented']},
            {wName: 'Frozen Blade', buffs: ['IcyVeins'], traits: ['Devastating'], debuffs: []},
            {wName: 'Firestorm', buffs: ['Haste'], traits: [], debuffs: ['Burn']},
            {wName: 'Fiery Blades', buffs: [], traits: ['Cunning'], debuffs: ['Burn']},
        ],
        sArray: [
            {sName: 'Arcane Assault', buffs: ['Radiance'], traits: [], debuffs: []},
            {sName: 'Arcane Blade', buffs: ['Finesse', 'Radiance'], traits: [], debuffs: []},
            {sName: 'Arcane Rift', buffs: [], traits: [], debuffs: ['Fragility']},
            {sName: 'Arcane Beam', buffs: [], traits: [], debuffs: ['Brittle']},
            {sName: 'Arcane Disc', buffs: ['Radiance'], traits: ['Piercing'], debuffs: []},
            {sName: 'Arcane Power', buffs: [], traits: [], debuffs: []},
            {sName: 'Arcane Sparks', buffs: ['Radiance'], traits: ['Piercing'], debuffs: []},
            {sName: 'Avalanche', buffs: [], traits: [], debuffs: ['Fragility', 'Slow']},
            {sName: 'Bladestorm', buffs: [], traits: [], debuffs: []},
            {sName: 'Blizzard', buffs: [], traits: [], debuffs: ['Slow']},
            {sName: 'Bloody Saw', buffs: ['Finesse'], traits: [], debuffs: ['Bleed']},
            {sName: 'Chromatic Bolt', buffs: [], traits: [], debuffs: []},
            {sName: 'Combustion', buffs: [], traits: [], debuffs: ['Burn']},
            {sName: 'Double Slash', buffs: ['Bulwark', 'Finesse'], traits: [], debuffs: ['Debilitated']},
            {sName: 'Fire bolt', buffs: [], traits: [], debuffs: ['Burn', 'Weakness']},
            {sName: 'Flamethrower', buffs: [], traits: [], debuffs: ['Burn']},
            {sName: 'Flame Wave', buffs: [], traits: [], debuffs: ['Burn', 'Shattered']},
            {sName: 'Flurry', buffs: ['Form'], traits: [], debuffs: ['Bleed']},
            {sName: 'Frost Bolt', buffs: ['IcyVeins'], traits: [], debuffs: []},
            {sName: 'Frost Totem', buffs: [], traits: ['Cunning'], debuffs: ['Slow']},
            {sName: 'Glacier', buffs: [], traits: [], debuffs: ['Disoriented', 'Slow']},
            {sName: 'Heartrending Strike', buffs: ['Bulwark', 'Finesse'], traits: [], debuffs: ['Fragility']},
            {sName: 'Ice Vortex', buffs: [], traits: [], debuffs: ['Slow']},
            {sName: 'Magic Missiles', buffs: [], traits: [], debuffs: ['Fragility']},
            {sName: 'Meteor', buffs: [], traits: [], debuffs: ['Burn', 'Stun']},
            {sName: 'On Guard', buffs: ['Bulwark', 'Form'], traits: [], debuffs: ['Exposed']},
            {sName: 'Quick Strike', buffs: ['Form', 'Haste'], traits: [], debuffs: []},
            {sName: 'Sharp Spear', buffs: ['Haste', 'Form'], traits: ['Piercing'], debuffs: []},
            {sName: 'Spear Trap', buffs: ['Form'], traits: [], debuffs: ['Exposed']},
            {sName: 'Subdue', buffs: [], traits: [], debuffs: []},
            {sName: 'Sugar Rush', buffs: [], traits: [], debuffs: []},
            {sName: 'Summon Helper Elves', buffs: [], traits: ['Cunning'], debuffs: ['Slow']},
            {sName: 'Titans Cleaver', buffs: ['Finesse'], traits: [], debuffs: []},
        ],
    },
    {
        hero: 'arcaneweaver',
        wArray: [

            {wName: 'Arcane Missiles', buffs: ['Radiance'], traits: [], debuffs: ['Brittle']},
            {wName: 'Arcane Explosion', buffs: ['Radiance'], traits: [], debuffs: ['Brittle']},
            {wName: 'Fiery Missiles', buffs: [], traits: [], debuffs: ['Burn']},
            {wName: 'Fire Pillar', buffs: [], traits: [], debuffs: ['Burn', 'Weakness']},
            {wName: 'Sacred Orb', buffs: ['Purity'], traits: [], debuffs: ['Exposed']},
            {wName: 'Celestial Retribution', buffs: ['Purity'], traits: [], debuffs: ['Exposed']},
            {wName: 'Frost Beam', buffs: ['IcyVeins'], traits: [], debuffs: []},
            {wName: 'Ice Shield', buffs: [], traits: [], debuffs: ['Slow', 'Fragility']},
        ],
        sArray: [
            {sName: 'Arcane Conjuration', buffs: ['Radiance'], traits: [], debuffs: ['Brittle']},
            {sName: 'Arcane Orb', buffs: ['Finesse', 'Radiance'], traits: [], debuffs: []},
            {sName: 'Arcane shield', buffs: [], traits: [], debuffs: []},
            {sName: 'Arcane Beam', buffs: [], traits: [], debuffs: ['Brittle']},
            {sName: 'Arcane Disc', buffs: ['Radiance'], traits: ['Piercing'], debuffs: []},
            {sName: 'Arcane Power', buffs: [], traits: [], debuffs: []},
            {sName: 'Arcane Sparks', buffs: ['Radiance'], traits: ['Piercing'], debuffs: []},
            {sName: 'Avalanche', buffs: [], traits: [], debuffs: ['Fragility', 'Slow']},
            {sName: 'Blizzard', buffs: [], traits: [], debuffs: ['Slow']},
            {sName: 'Bloodlust', buffs: [], traits: [], debuffs: []},
            {sName: 'Chaos Bolt', buffs: [], traits: ['Chaotic', 'Precise'], debuffs: []},
            {sName: 'Chaotic Explosion', buffs: [], traits: ['Chaotic', 'Impactful'], debuffs: []},
            {sName: 'Chromatic Bolt', buffs: [], traits: [], debuffs: []},
            {sName: 'Combustion', buffs: [], traits: [], debuffs: ['Burn']},
            {sName: 'Death Claw', buffs: [], traits: ['Chaotic'], debuffs: []},
            {sName: 'Fire bolt', buffs: [], traits: [], debuffs: ['Burn', 'Weakness']},
            {sName: 'Flamethrower', buffs: [], traits: [], debuffs: ['Burn']},
            {sName: 'Flame Wave', buffs: [], traits: [], debuffs: ['Burn', 'Shattered']},
            {sName: 'Frenzied Bunnies', buffs: [], traits: [], debuffs: ['Disarray']},
            {sName: 'Frost Bolt', buffs: ['IcyVeins'], traits: [], debuffs: []},
            {sName: 'Frost Totem', buffs: [], traits: ['Cunning'], debuffs: ['Slow']},
            {sName: 'Glacier', buffs: [], traits: [], debuffs: ['Disoriented', 'Slow']},
            {sName: 'Holy Beam', buffs: ['Purity', 'Prowess'], traits: [], debuffs: []},
            {sName: 'Ice Vortex', buffs: [], traits: [], debuffs: ['Slow']},
            {sName: 'Light Beam', buffs: [], traits: [], debuffs: ['Exposed']},
            {sName: 'Living Weapons', buffs: [], traits: [], debuffs: ['Dazed']},
            {sName: 'Magic Missiles', buffs: [], traits: [], debuffs: ['Fragility']},
            {sName: 'Meteor', buffs: [], traits: [], debuffs: ['Burn', 'Stun']},
            {sName: 'Might', buffs: [], traits: [], debuffs: []},
            {sName: 'Smite', buffs: ['Purity'], traits: [], debuffs: []},
            {sName: 'Summon Chaos Golem', buffs: [], traits: ['Taunt'], debuffs: ['Disarray']},
            {sName: 'Summon Helper Elves', buffs: [], traits: ['Cunning'], debuffs: ['Slow']},
        ],
    },
    {
        hero: 'sentinel',
        wArray: [
            {wName: 'Shoot', buffs: ['Aptitude'], traits: [], debuffs: []},
            {wName: 'Rain Of Arrows', buffs: ['Aptitude'], traits: [], debuffs: []},
            {wName: 'Explosive Arrows', buffs: [], traits: ['Devastating'], debuffs: ['Bleed']},
            {wName: 'Cluster Bomb', buffs: [], traits: [], debuffs: ['Bleed']},
            {wName: 'Obscure Arrow', buffs: ['Aptitude'], traits: [], debuffs: ['Doom']},
            {wName: 'Void Trap', buffs: [], traits: [], debuffs: ['Doom', 'Weakness']},
            {wName: 'Noxious Shot', buffs: ['Aptitude'], traits: [], debuffs: ['Poison']},
            {wName: 'Venomous Volley', buffs: [], traits: [], debuffs: ['Poison', 'Weakness']},
        ],
        sArray: [
            {sName: 'Ricochet Shot', buffs: ['Aptitude'], traits: ['Piercing'], debuffs: []},
            {sName: 'Sniper Shot', buffs: [], traits: ['Devastating', 'Precise'], debuffs: []},
            {sName: 'Split Shot', buffs: ['Aptitude'], traits: [], debuffs: ['Dazed']},
            {sName: 'Acid Rain', buffs: [], traits: [], debuffs: ['Poison']},
            {sName: 'Avalanche', buffs: [], traits: [], debuffs: ['Fragility', 'Slow']},
            {sName: 'Bladed Chakram', buffs: ['Aptitude'], traits: ['Piercing'], debuffs: []},
            {sName: 'Blizzard', buffs: [], traits: [], debuffs: ['Slow']},
            {sName: 'Bomb Barrage', buffs: [], traits: [], debuffs: ['Bleed']},
            {sName: 'Camors Arrow', buffs: [], traits: [], debuffs: ['Fragility', 'Stun']},
            {sName: 'Chromatic Bolt', buffs: [], traits: [], debuffs: []},
            {sName: 'Death Vortex', buffs: [], traits: [], debuffs: ['Doom']},
            {sName: 'Egg Shooter', buffs: [], traits: [], debuffs: ['Dazed']},
            {sName: 'Explosive Trap', buffs: [], traits: [], debuffs: ['Bleed', 'Disoriented']},
            {sName: 'Frag Shot', buffs: ['Aptitude'], traits: [], debuffs: ['Dazed']},
            {sName: 'Frost Bolt', buffs: ['IcyVeins'], traits: [], debuffs: []},
            {sName: 'Frost Totem', buffs: [], traits: ['Cunning'], debuffs: ['Slow']},
            {sName: 'Glacier', buffs: [], traits: [], debuffs: ['Disoriented', 'Slow']},
            {sName: 'Heartbreak Orbs', buffs: ['Aptitude'], traits: ['Precise'], debuffs: []},
            {sName: 'Ice Vortex', buffs: [], traits: [], debuffs: ['Slow']},
            {sName: 'Mine Field', buffs: [], traits: [], debuffs: ['Bleed']},
            {sName: 'Pestilence', buffs: [], traits: [], debuffs: ['Poison']},
            {sName: 'Poison Bolt', buffs: [], traits: [], debuffs: ['Poison']},
            {sName: 'Poison Cloud', buffs: [], traits: [], debuffs: ['Poison', 'Weakness']},
            {sName: 'Poison Puddle', buffs: [], traits: [], debuffs: ['Poison', 'Debilitated']},
            {sName: 'Shadow Bolt', buffs: ['Aptitude'], traits: [], debuffs: ['Doom']},
            {sName: 'Shadow orb', buffs: [], traits: [], debuffs: ['Doom']},
            {sName: 'Shadow Spikes', buffs: [], traits: [], debuffs: []},
            {sName: 'Shrapnel Bomb', buffs: [], traits: [], debuffs: []},
            {sName: 'Spread Shot', buffs: ['Aptitude'], traits: [], debuffs: ['Dazed']},
            {sName: 'Storm Of Arrows', buffs: [], traits: [], debuffs: []},
            {sName: 'Suction Bomb', buffs: [], traits: [], debuffs: ['Bleed']},
            {sName: 'Summon Ballista', buffs: [], traits: ['Piercing', 'Cunning'], debuffs: []},
            {sName: 'Summon Helper Elves', buffs: [], traits: ['Cunning'], debuffs: ['Slow']},
            {sName: 'Surprise Gift', buffs: [], traits: [], debuffs: ['Bleed', 'Weakness']},
            {sName: 'Void', buffs: [], traits: [], debuffs: ['Doom']},
        ],
    },
    {
        hero: 'paladin',
        wArray: [
            {wName: 'Blades Of Light', buffs: ['Purity', 'Prowess'], traits: [], debuffs: []},
            {wName: 'Holy Fire', buffs: ['Purity'], traits: [], debuffs: []},
            {wName: 'Heroic Strike', buffs: ['Purity', 'Finesse'], traits: [], debuffs: []},
            {wName: 'Hammer Of Justice', buffs: ['Purity', 'Finesse'], traits: ['Piercing'], debuffs: []},
            {wName: 'Radiant Light', buffs: ['Prowess', 'Radiance'], traits: [], debuffs: []},
            {wName: 'Arcane Mace', buffs: ['Radiance'], traits: [], debuffs: []},
            {wName: 'Fissure Strike', buffs: ['Prowess', 'Resilience'], traits: [], debuffs: []},
            {wName: 'Staggering Blow', buffs: ['Prowess'], traits: [], debuffs: []},
        ],
        sArray: [
            {sName: 'Beacon Of Light', buffs: ['Purity'], traits: [], debuffs: ['Exposed']},
            {sName: 'Penance', buffs: ['Purity'], traits: [], debuffs: ['Dazed']},
            {sName: 'Templars Verdict', buffs: ['Purity'], traits: ['Devastating'], debuffs: []},
            {sName: 'Arcane Beam', buffs: [], traits: [], debuffs: ['Brittle']},
            {sName: 'Arcane Disc', buffs: ['Radiance'], traits: ['Piercing'], debuffs: []},
            {sName: 'Arcane Power', buffs: [], traits: [], debuffs: []},
            {sName: 'Arcane Sparks', buffs: ['Radiance'], traits: ['Piercing'], debuffs: []},
            {sName: 'Armor Shatter', buffs: ['Prowess'], traits: [], debuffs: ['Shattered']},
            {sName: 'Bladestorm', buffs: [], traits: [], debuffs: []},
            {sName: 'Bloody Saw', buffs: ['Finesse'], traits: [], debuffs: ['Bleed']},
            {sName: 'Body Slam', buffs: ['Prowess'], traits: [], debuffs: []},
            {sName: 'Chain Lightning', buffs: ['Electrified'], traits: [], debuffs: ['Distracted']},
            {sName: 'Chromatic Bolt', buffs: [], traits: [], debuffs: []},
            {sName: 'Double Slash', buffs: ['Bulwark', 'Finesse'], traits: [], debuffs: ['Debilitated']},
            {sName: 'Ground Break', buffs: ['Prowess'], traits: ['Piercing'], debuffs: []},
            {sName: 'Heartrending Strike', buffs: ['Bulwark', 'Finesse'], traits: [], debuffs: ['Fragility']},
            {sName: 'Holy Beam', buffs: ['Purity', 'Prowess'], traits: [], debuffs: []},
            {sName: 'Light Beam', buffs: [], traits: [], debuffs: ['Exposed']},
            {sName: 'Lightning bolt', buffs: ['Electrified'], traits: ['Devastating'], debuffs: []},
            {sName: 'Lightning Surge', buffs: [], traits: [], debuffs: ['Dazed']},
            {sName: 'Living Weapons', buffs: [], traits: [], debuffs: ['Dazed']},
            {sName: 'Magic Missiles', buffs: [], traits: [], debuffs: ['Fragility']},
            {sName: 'Might', buffs: [], traits: [], debuffs: []},
            {sName: 'Power Conductor', buffs: ['Electrified'], traits: [], debuffs: ['Dazed']},
            {sName: 'Resonant Slam', buffs: ['Prowess', 'Resilience'], traits: ['Brutal'], debuffs: []},
            {sName: 'Seismic Shock', buffs: ['Prowess', 'Resilience'], traits: [], debuffs: []},
            {sName: 'Smite', buffs: ['Purity'], traits: [], debuffs: []},
            {sName: 'Subdue', buffs: [], traits: [], debuffs: []},
            {sName: 'Thunder strike', buffs: ['Electrified'], traits: [], debuffs: ['Stun']},
            {sName: 'Titans Cleaver', buffs: ['Finesse'], traits: [], debuffs: []},
        ],
    },
    {
        hero: 'chaoswalker',
        wArray: [
            {wName: 'Chaotic Missile', buffs: [], traits: ['Chaotic', 'Piercing'], debuffs: []},
            {wName: 'Unchained Chaos', buffs: [], traits: ['Chaotic'], debuffs: ['Disarray']},
            {wName: 'Infected Shot', buffs: [], traits: [], debuffs: ['Poison']},
            {wName: 'Corrosion', buffs: [], traits: [], debuffs: ['Poison']},
            {wName: 'Orbs Of Destruction', buffs: [], traits: [], debuffs: ['Burn']},
            {wName: 'Volcano Eruption', buffs: [], traits: [], debuffs: ['Burn']},
            {wName: 'Ripple Of Light', buffs: ['Purity'], traits: ['Brutal'], debuffs: []},
            {wName: 'Sanctified Orb', buffs: ['Purity'], traits: [], debuffs: ['Dazed']},
        ],
        sArray: [
            {sName: 'Chaos Totem', buffs: [], traits: ['Cunning'], debuffs: ['Disarray']},
            {sName: 'Chaos Wave', buffs: [], traits: ['Brutal', 'Chaotic'], debuffs: []},
            {sName: 'Manifestations Of Chaos', buffs: [], traits: ['Chaotic'], debuffs: []},
            {sName: 'Acid Rain', buffs: [], traits: [], debuffs: ['Poison']},
            {sName: 'Bloodlust', buffs: [], traits: [], debuffs: []},
            {sName: 'Chaos Bolt', buffs: [], traits: ['Chaotic', 'Precise'], debuffs: []},
            {sName: 'Chaotic Explosion', buffs: [], traits: ['Chaotic', 'Impactful'], debuffs: []},
            {sName: 'Chromatic Bolt', buffs: [], traits: [], debuffs: []},
            {sName: 'Combustion', buffs: [], traits: [], debuffs: ['Burn']},
            {sName: 'Death Claw', buffs: [], traits: ['Chaotic'], debuffs: []},
            {sName: 'Death Vortex', buffs: [], traits: [], debuffs: ['Doom']},
            {sName: 'Fire bolt', buffs: [], traits: [], debuffs: ['Burn', 'Weakness']},
            {sName: 'Flamethrower', buffs: [], traits: [], debuffs: ['Burn']},
            {sName: 'Flame Wave', buffs: [], traits: [], debuffs: ['Burn', 'Shattered']},
            {sName: 'Frenzied Bunnies', buffs: [], traits: [], debuffs: ['Disarray']},
            {sName: 'Holy Beam', buffs: ['Purity', 'Prowess'], traits: [], debuffs: []},
            {sName: 'Light Beam', buffs: [], traits: [], debuffs: ['Exposed']},
            {sName: 'Living Weapons', buffs: [], traits: [], debuffs: ['Dazed']},
            {sName: 'Meteor', buffs: [], traits: [], debuffs: ['Burn', 'Stun']},
            {sName: 'Might', buffs: [], traits: [], debuffs: []},
            {sName: 'Pestilence', buffs: [], traits: [], debuffs: ['Poison']},
            {sName: 'Poison Bolt', buffs: [], traits: [], debuffs: ['Poison']},
            {sName: 'Poison Cloud', buffs: [], traits: [], debuffs: ['Poison', 'Weakness']},
            {sName: 'Poison Puddle', buffs: [], traits: [], debuffs: ['Poison', 'Debilitated']},
            {sName: 'Shadow Bolt', buffs: ['Aptitude'], traits: [], debuffs: ['Doom']},
            {sName: 'Shadow orb', buffs: [], traits: [], debuffs: ['Doom']},
            {sName: 'Shadow Spikes', buffs: [], traits: [], debuffs: []},
            {sName: 'Smite', buffs: ['Purity'], traits: [], debuffs: []},
            {sName: 'Summon Chaos Golem', buffs: [], traits: ['Taunt'], debuffs: ['Disarray']},
            {sName: 'Void', buffs: [], traits: [], debuffs: ['Doom']},
        ],
    },
    {
        hero: 'beastmaster',
        wArray: [
            {wName: 'Venomous Strike', buffs: ['Finesse'], traits: [], debuffs: ['Poison']},
            {wName: 'Cobra Totem', buffs: [], traits: ['Cunning'], debuffs: ['Poison', 'Weakness']},
            {wName: 'Wild Strike', buffs: ['Finesse'], traits: [], debuffs: []},
            {wName: 'Summon Swamp Boar', buffs: [], traits: [], debuffs: ['Fragility']},
            {wName: 'Brutal Slam', buffs: ['Prowess'], traits: [], debuffs: []},
            {wName: 'Summon Cave Bear', buffs: [], traits: ['Taunt'], debuffs: []},
            {wName: 'Spider Cocoon', buffs: [], traits: [], debuffs: ['Bleed']},
            {wName: 'Summon Spider Queen', buffs: [], traits: ['Cunning'], debuffs: ['Bleed', 'Weakness']},
        ],
        sArray: [
            {sName: 'Bestial Wrath', buffs: [], traits: [], debuffs: []},
            {sName: 'Summon Battle Moose', buffs: [], traits: ['Taunt'], debuffs: ['Stun']},
            {sName: 'Summon War Tiger', buffs: [], traits: ['Cunning'], debuffs: ['Bleed']},
            {sName: 'Acid Rain', buffs: [], traits: [], debuffs: ['Poison']},
            {sName: 'Armor Shatter', buffs: ['Prowess'], traits: [], debuffs: ['Shattered']},
            {sName: 'Bladestorm', buffs: [], traits: [], debuffs: []},
            {sName: 'Bloody Saw', buffs: ['Finesse'], traits: [], debuffs: ['Bleed']},
            {sName: 'Body Slam', buffs: ['Prowess'], traits: [], debuffs: []},
            {sName: 'Bomb Barrage', buffs: [], traits: [], debuffs: ['Bleed']},
            {sName: 'Chromatic Bolt', buffs: [], traits: [], debuffs: []},
            {sName: 'Combustion', buffs: [], traits: [], debuffs: ['Burn']},
            {sName: 'Double Slash', buffs: ['Bulwark', 'Finesse'], traits: [], debuffs: ['Debilitated']},
            {sName: 'Explosive Trap', buffs: [], traits: [], debuffs: ['Bleed', 'Disoriented']},
            {sName: 'Fire bolt', buffs: [], traits: [], debuffs: ['Burn', 'Weakness']},
            {sName: 'Flamethrower', buffs: [], traits: [], debuffs: ['Burn']},
            {sName: 'Flame Wave', buffs: [], traits: [], debuffs: ['Burn', 'Shattered']},
            {sName: 'Ground Break', buffs: ['Prowess'], traits: ['Piercing'], debuffs: []},
            {sName: 'Heartrending Strike', buffs: ['Bulwark', 'Finesse'], traits: [], debuffs: ['Fragility']},
            {sName: 'Meteor', buffs: [], traits: [], debuffs: ['Burn', 'Stun']},
            {sName: 'Mine Field', buffs: [], traits: [], debuffs: ['Bleed']},
            {sName: 'Pestilence', buffs: [], traits: [], debuffs: ['Poison']},
            {sName: 'Poison Bolt', buffs: [], traits: [], debuffs: ['Poison']},
            {sName: 'Poison Cloud', buffs: [], traits: [], debuffs: ['Poison', 'Weakness']},
            {sName: 'Poison Puddle', buffs: [], traits: [], debuffs: ['Poison', 'Debilitated']},
            {sName: 'Resonant Slam', buffs: ['Prowess', 'Resilience'], traits: ['Brutal'], debuffs: []},
            {sName: 'Seismic Shock', buffs: ['Prowess', 'Resilience'], traits: [], debuffs: []},
            {sName: 'Shrapnel Bomb', buffs: [], traits: [], debuffs: []},
            {sName: 'Subdue', buffs: [], traits: [], debuffs: []},
            {sName: 'Suction Bomb', buffs: [], traits: [], debuffs: ['Bleed']},
            {sName: 'Surprise Gift', buffs: [], traits: [], debuffs: ['Bleed', 'Weakness']},
            {sName: 'Titans Cleaver', buffs: ['Finesse'], traits: [], debuffs: []},
        ],
    },
    {
        hero: 'assassin',
        wArray: [
            {wName: 'Sinister Strike', buffs: ['Form', 'Haste'], traits: ['Ambush'], debuffs: ['Bleed']},
            {wName: 'Eviscerate', buffs: ['Form', 'Haste'], traits: ['Ambush'], debuffs: ['Bleed']},
            {wName: 'Twin Daggers', buffs: ['Finesse', 'Haste'], traits: ['Ambush'], debuffs: ['Bleed']},
            {wName: 'Backstab', buffs: ['Finesse', 'Haste'], traits: ['Ambush'], debuffs: []},
            {wName: 'Debilitating Bomb', buffs: [], traits: [], debuffs: ['Bleed']},
            {wName: 'Fan Of Bombs', buffs: ['Finesse'], traits: [], debuffs: ['Bleed', 'Fragility']},
            {wName: 'Shadow Stab', buffs: ['Form'], traits: ['Ambush'], debuffs: ['Doom']},
            {wName: 'Reap', buffs: [], traits: ['Ambush'], debuffs: ['Doom']},
        ],
        sArray: [
            {sName: 'Rupture', buffs: ['Form'], traits: [], debuffs: ['Stun']},
            {sName: 'Shadow Step', buffs: [], traits: [], debuffs: ['Doom']},
            {sName: 'Smoke Bomb', buffs: [], traits: ['Ambush'], debuffs: ['Disoriented']},
            {sName: 'Summon Assassin Enclave', buffs: [], traits: ['Cunning'], debuffs: ['Bleed']},
            {sName: 'Acid Rain', buffs: [], traits: [], debuffs: ['Poison']},
            {sName: 'Bladestorm', buffs: [], traits: [], debuffs: []},
            {sName: 'Bloody Saw', buffs: ['Finesse'], traits: [], debuffs: ['Bleed']},
            {sName: 'Bomb Barrage', buffs: [], traits: [], debuffs: ['Bleed']},
            {sName: 'Chromatic Bolt', buffs: [], traits: [], debuffs: []},
            {sName: 'Death Vortex', buffs: [], traits: [], debuffs: ['Doom']},
            {sName: 'Double Slash', buffs: ['Bulwark', 'Finesse'], traits: [], debuffs: ['Debilitated']},
            {sName: 'Explosive Trap', buffs: [], traits: [], debuffs: ['Bleed', 'Disoriented']},
            {sName: 'Flurry', buffs: ['Form'], traits: [], debuffs: ['Bleed']},
            {sName: 'Heartrending Strike', buffs: ['Bulwark', 'Finesse'], traits: [], debuffs: ['Fragility']},
            {sName: 'Mine Field', buffs: [], traits: [], debuffs: ['Bleed']},
            {sName: 'On Guard', buffs: ['Bulwark', 'Form'], traits: [], debuffs: ['Exposed']},
            {sName: 'Pestilence', buffs: [], traits: [], debuffs: ['Poison']},
            {sName: 'Poison Bolt', buffs: [], traits: [], debuffs: ['Poison']},
            {sName: 'Poison Cloud', buffs: [], traits: [], debuffs: ['Poison', 'Weakness']},
            {sName: 'Poison Puddle', buffs: [], traits: [], debuffs: ['Poison', 'Debilitated']},
            {sName: 'Quick Strike', buffs: ['Form', 'Haste'], traits: [], debuffs: []},
            {sName: 'Shadow Bolt', buffs: ['Aptitude'], traits: [], debuffs: ['Doom']},
            {sName: 'Shadow orb', buffs: [], traits: [], debuffs: ['Doom']},
            {sName: 'Shadow Spikes', buffs: [], traits: [], debuffs: []},
            {sName: 'Sharp Spear', buffs: ['Haste', 'Form'], traits: ['Piercing'], debuffs: []},
            {sName: 'Shrapnel Bomb', buffs: [], traits: [], debuffs: []},
            {sName: 'Spear Trap', buffs: ['Form'], traits: [], debuffs: ['Exposed']},
            {sName: 'Subdue', buffs: [], traits: [], debuffs: []},
            {sName: 'Suction Bomb', buffs: [], traits: [], debuffs: ['Bleed']},
            {sName: 'Sugar Rush', buffs: [], traits: [], debuffs: []},
            {sName: 'Surprise Gift', buffs: [], traits: [], debuffs: ['Bleed', 'Weakness']},
            {sName: 'Titans Cleaver', buffs: ['Finesse'], traits: [], debuffs: []},
            {sName: 'Void', buffs: [], traits: [], debuffs: ['Doom']},
        ],
    },
    {
        hero: 'elementalist',
        wArray: [
            {wName: 'Lightning Beam', buffs: [], traits: [], debuffs: ['Dazed']},
            {wName: 'Call Lightning', buffs: ['Electrified'], traits: [], debuffs: []},
            {wName: 'Severe Cold', buffs: [], traits: [], debuffs: ['Disoriented', 'Slow']},
            {wName: 'Freezing Blow', buffs: ['IcyVeins'], traits: [], debuffs: ['Slow']},
            {wName: 'Ray Of Fire', buffs: ['Haste'], traits: [], debuffs: ['Burn']},
            {wName: 'Heat Explosion', buffs: [], traits: [], debuffs: ['Burn']},
            {wName: 'Contaminated Cut', buffs: [], traits: [], debuffs: []},
            {wName: 'Outbreak', buffs: [], traits: [], debuffs: ['Poison']},
        ],
        sArray: [
            {sName: 'Frozen Warhammer', buffs: ['Prowess', 'IcyVeins'], traits: [], debuffs: []},
            {sName: 'Lava Shield', buffs: [], traits: [], debuffs: ['Burn']},
            {sName: 'Tornado', buffs: ['Electrified'], traits: ['Devastating'], debuffs: []},
            {sName: 'Acid Rain', buffs: [], traits: [], debuffs: ['Poison']},
            {sName: 'Avalanche', buffs: [], traits: [], debuffs: ['Fragility', 'Slow']},
            {sName: 'Blizzard', buffs: [], traits: [], debuffs: ['Slow']},
            {sName: 'Chain Lightning', buffs: ['Electrified'], traits: [], debuffs: ['Distracted']},
            {sName: 'Chromatic Bolt', buffs: [], traits: [], debuffs: []},
            {sName: 'Combustion', buffs: [], traits: [], debuffs: ['Burn']},
            {sName: 'Earth bolt', buffs: ['Colossal'], traits: [], debuffs: []},
            {sName: 'Earthquake', buffs: ['Colossal'], traits: [], debuffs: ['Brittle']},
            {sName: 'Earth Shield', buffs: ['Resilience'], traits: [], debuffs: []},
            {sName: 'Fire bolt', buffs: [], traits: [], debuffs: ['Burn', 'Weakness']},
            {sName: 'Flamethrower', buffs: [], traits: [], debuffs: ['Burn']},
            {sName: 'Flame Wave', buffs: [], traits: [], debuffs: ['Burn', 'Shattered']},
            {sName: 'Frost Bolt', buffs: ['IcyVeins'], traits: [], debuffs: []},
            {sName: 'Frost Totem', buffs: [], traits: ['Cunning'], debuffs: ['Slow']},
            {sName: 'Glacier', buffs: [], traits: [], debuffs: ['Disoriented', 'Slow']},
            {sName: 'Ice Vortex', buffs: [], traits: [], debuffs: ['Slow']},
            {sName: 'Lightning bolt', buffs: ['Electrified'], traits: ['Devastating'], debuffs: []},
            {sName: 'Lightning Surge', buffs: [], traits: [], debuffs: ['Dazed']},
            {sName: 'Meteor', buffs: [], traits: [], debuffs: ['Burn', 'Stun']},
            {sName: 'Pestilence', buffs: [], traits: [], debuffs: ['Poison']},
            {sName: 'Poison Bolt', buffs: [], traits: [], debuffs: ['Poison']},
            {sName: 'Poison Cloud', buffs: [], traits: [], debuffs: ['Poison', 'Weakness']},
            {sName: 'Poison Puddle', buffs: [], traits: [], debuffs: ['Poison', 'Debilitated']},
            {sName: 'Power Conductor', buffs: ['Electrified'], traits: [], debuffs: ['Dazed']},
            {sName: 'Rolling Boulder', buffs: [], traits: [], debuffs: ['Stun']},
            {sName: 'Shockwave Totem', buffs: [], traits: [], debuffs: ['Dazed']},
            {sName: 'Summon Helper Elves', buffs: [], traits: ['Cunning'], debuffs: ['Slow']},
            {sName: 'Thunder strike', buffs: ['Electrified'], traits: [], debuffs: ['Stun']},
        ],
    },
    {
        hero: 'legionnaire',
        wArray: [
            {wName: 'Thrust', buffs: ['Form', 'Resilience'], traits: [], debuffs: []},
            {wName: 'Shield Bash', buffs: ['Form'], traits: [], debuffs: []},
            {wName: 'Jupiters Spear', buffs: ['Electrified'], traits: [], debuffs: ['Distracted']},
            {wName: 'Summon Infantry', buffs: [], traits: ['Cunning'], debuffs: ['Dazed']},
            {wName: 'Corrosive Spear', buffs: ['Vigor'], traits: [], debuffs: ['Poison']},
            {wName: 'Purging Slam', buffs: ['Vigor'], traits: [], debuffs: []},
            {wName: 'Piercing Flames', buffs: [], traits: [], debuffs: ['Burn', 'Shattered']},
            {wName: 'Incinerating Spear', buffs: ['Form'], traits: [], debuffs: ['Burn']},
        ],
        sArray: [
            {sName: 'Intimidating Shout', buffs: [], traits: [], debuffs: ['Distracted']},
            {sName: 'Shield Wall', buffs: [], traits: [], debuffs: []},
            {sName: 'Storm Of Spears', buffs: [], traits: [], debuffs: []},
            {sName: 'Acid Rain', buffs: [], traits: [], debuffs: ['Poison']},
            {sName: 'Bloodlust', buffs: [], traits: [], debuffs: []},
            {sName: 'Chain Lightning', buffs: ['Electrified'], traits: [], debuffs: ['Distracted']},
            {sName: 'Chaos Bolt', buffs: [], traits: ['Chaotic', 'Precise'], debuffs: []},
            {sName: 'Chaotic Explosion', buffs: [], traits: ['Chaotic', 'Impactful'], debuffs: []},
            {sName: 'Chromatic Bolt', buffs: [], traits: [], debuffs: []},
            {sName: 'Combustion', buffs: [], traits: [], debuffs: ['Burn']},
            {sName: 'Death Claw', buffs: [], traits: ['Chaotic'], debuffs: []},
            {sName: 'Fire bolt', buffs: [], traits: [], debuffs: ['Burn', 'Weakness']},
            {sName: 'Flamethrower', buffs: [], traits: [], debuffs: ['Burn']},
            {sName: 'Flame Wave', buffs: [], traits: [], debuffs: ['Burn', 'Shattered']},
            {sName: 'Flurry', buffs: ['Form'], traits: [], debuffs: ['Bleed']},
            {sName: 'Frenzied Bunnies', buffs: [], traits: [], debuffs: ['Disarray']},
            {sName: 'Lightning bolt', buffs: ['Electrified'], traits: ['Devastating'], debuffs: []},
            {sName: 'Lightning Surge', buffs: [], traits: [], debuffs: ['Dazed']},
            {sName: 'Meteor', buffs: [], traits: [], debuffs: ['Burn', 'Stun']},
            {sName: 'On Guard', buffs: ['Bulwark', 'Form'], traits: [], debuffs: ['Exposed']},
            {sName: 'Pestilence', buffs: [], traits: [], debuffs: ['Poison']},
            {sName: 'Poison Bolt', buffs: [], traits: [], debuffs: ['Poison']},
            {sName: 'Poison Cloud', buffs: [], traits: [], debuffs: ['Poison', 'Weakness']},
            {sName: 'Poison Puddle', buffs: [], traits: [], debuffs: ['Poison', 'Debilitated']},
            {sName: 'Power Conductor', buffs: ['Electrified'], traits: [], debuffs: ['Dazed']},
            {sName: 'Quick Strike', buffs: ['Form', 'Haste'], traits: [], debuffs: []},
            {sName: 'Sharp Spear', buffs: ['Haste', 'Form'], traits: ['Piercing'], debuffs: []},
            {sName: 'Spear Trap', buffs: ['Form'], traits: [], debuffs: ['Exposed']},
            {sName: 'Sugar Rush', buffs: [], traits: [], debuffs: []},
            {sName: 'Summon Chaos Golem', buffs: [], traits: ['Taunt'], debuffs: ['Disarray']},
            {sName: 'Thunder strike', buffs: ['Electrified'], traits: [], debuffs: ['Stun']},
        ],
    },
    {
        hero: 'necromancer',
        wArray: [
            {wName: 'Summon Skeletal Warrior', buffs: [], traits: ['Cunning'], debuffs: ['Crippled']},
            {wName: 'Shadow Nova', buffs: [], traits: [], debuffs: ['Doom']},
            {wName: 'Spectral Guardian', buffs: ['Radiance'], traits: [], debuffs: []},
            {wName: 'Soul Release', buffs: ['Radiance'], traits: ['Piercing'], debuffs: []},
            {wName: 'Summon Plague Rats', buffs: [], traits: [], debuffs: ['Poison', 'Weakness']},
            {wName: 'Putrefy', buffs: [], traits: [], debuffs: ['Poison']},
            {wName: 'Murder Of Crows', buffs: [], traits: ['Chaotic'], debuffs: []},
            {wName: 'Carrion Crows', buffs: [], traits: ['Chaotic'], debuffs: ['Disarray']},
        ],
        sArray: [
            {sName: 'Summon Putrid Hounds', buffs: [], traits: ['Cunning'], debuffs: []},
            {sName: 'Summon Skeletal Archer', buffs: [], traits: ['Cunning'], debuffs: []},
            {sName: 'Summon Skeletal Mage', buffs: [], traits: [], debuffs: ['Doom']},
            {sName: 'Acid Rain', buffs: [], traits: [], debuffs: ['Poison']},
            {sName: 'Arcane Beam', buffs: [], traits: [], debuffs: ['Brittle']},
            {sName: 'Arcane Disc', buffs: ['Radiance'], traits: ['Piercing'], debuffs: []},
            {sName: 'Arcane Power', buffs: [], traits: [], debuffs: []},
            {sName: 'Arcane Sparks', buffs: ['Radiance'], traits: ['Piercing'], debuffs: []},
            {sName: 'Avalanche', buffs: [], traits: [], debuffs: ['Fragility', 'Slow']},
            {sName: 'Blizzard', buffs: [], traits: [], debuffs: ['Slow']},
            {sName: 'Bloodlust', buffs: [], traits: [], debuffs: []},
            {sName: 'Chaos Bolt', buffs: [], traits: ['Chaotic', 'Precise'], debuffs: []},
            {sName: 'Chaotic Explosion', buffs: [], traits: ['Chaotic', 'Impactful'], debuffs: []},
            {sName: 'Chromatic Bolt', buffs: [], traits: [], debuffs: []},
            {sName: 'Death Claw', buffs: [], traits: ['Chaotic'], debuffs: []},
            {sName: 'Death Vortex', buffs: [], traits: [], debuffs: ['Doom']},
            {sName: 'Frenzied Bunnies', buffs: [], traits: [], debuffs: ['Disarray']},
            {sName: 'Frost Bolt', buffs: ['IcyVeins'], traits: [], debuffs: []},
            {sName: 'Frost Totem', buffs: [], traits: ['Cunning'], debuffs: ['Slow']},
            {sName: 'Glacier', buffs: [], traits: [], debuffs: ['Disoriented', 'Slow']},
            {sName: 'Ice Vortex', buffs: [], traits: [], debuffs: ['Slow']},
            {sName: 'Magic Missiles', buffs: [], traits: [], debuffs: ['Fragility']},
            {sName: 'Pestilence', buffs: [], traits: [], debuffs: ['Poison']},
            {sName: 'Poison Bolt', buffs: [], traits: [], debuffs: ['Poison']},
            {sName: 'Poison Cloud', buffs: [], traits: [], debuffs: ['Poison', 'Weakness']},
            {sName: 'Poison Puddle', buffs: [], traits: [], debuffs: ['Poison', 'Debilitated']},
            {sName: 'Shadow Bolt', buffs: ['Aptitude'], traits: [], debuffs: ['Doom']},
            {sName: 'Shadow orb', buffs: [], traits: [], debuffs: ['Doom']},
            {sName: 'Shadow Spikes', buffs: [], traits: [], debuffs: []},
            {sName: 'Summon Chaos Golem', buffs: [], traits: ['Taunt'], debuffs: ['Disarray']},
            {sName: 'Summon Helper Elves', buffs: [], traits: ['Cunning'], debuffs: ['Slow']},
            {sName: 'Void', buffs: [], traits: [], debuffs: ['Doom']},
        ],
    },
    {
        hero: 'deathknight',
        wArray: [
            {wName: 'Obliterate', buffs: ['Finesse'], traits: [], debuffs: ['Doom']},
            {wName: 'Ray Of Doom', buffs: [], traits: [], debuffs: ['Doom']},
            {wName: 'Festering Strike', buffs: [], traits: [], debuffs: ['Poison', 'Weakness']},
            {wName: 'Lethal Blade', buffs: [], traits: [], debuffs: []},
            {wName: 'Ravaging Strike', buffs: ['Bulwark', 'Finesse'], traits: [], debuffs: []},
            {wName: 'Carnage', buffs: ['Bulwark', 'Finesse'], traits: [], debuffs: []},
            {wName: 'Frost Strike', buffs: ['IcyVeins'], traits: [], debuffs: ['Fragility']},
            {wName: 'Glacial Affinity', buffs: [], traits: [], debuffs: []},
        ],
        sArray: [
            {sName: 'Contagion', buffs: [], traits: [], debuffs: []},
            {sName: 'Path Of Decay', buffs: [], traits: [], debuffs: ['Poison']},
            {sName: 'Shadow Grasp', buffs: [], traits: [], debuffs: []},
            {sName: 'Acid Rain', buffs: [], traits: [], debuffs: ['Poison']},
            {sName: 'Armor Shatter', buffs: ['Prowess'], traits: [], debuffs: ['Shattered']},
            {sName: 'Avalanche', buffs: [], traits: [], debuffs: ['Fragility', 'Slow']},
            {sName: 'Bladestorm', buffs: [], traits: [], debuffs: []},
            {sName: 'Blizzard', buffs: [], traits: [], debuffs: ['Slow']},
            {sName: 'Bloody Saw', buffs: ['Finesse'], traits: [], debuffs: ['Bleed']},
            {sName: 'Body Slam', buffs: ['Prowess'], traits: [], debuffs: []},
            {sName: 'Chromatic Bolt', buffs: [], traits: [], debuffs: []},
            {sName: 'Death Vortex', buffs: [], traits: [], debuffs: ['Doom']},
            {sName: 'Double Slash', buffs: ['Bulwark', 'Finesse'], traits: [], debuffs: ['Debilitated']},
            {sName: 'Frost Bolt', buffs: ['IcyVeins'], traits: [], debuffs: []},
            {sName: 'Frost Totem', buffs: [], traits: ['Cunning'], debuffs: ['Slow']},
            {sName: 'Glacier', buffs: [], traits: [], debuffs: ['Disoriented', 'Slow']},
            {sName: 'Ground Break', buffs: ['Prowess'], traits: ['Piercing'], debuffs: []},
            {sName: 'Heartrending Strike', buffs: ['Bulwark', 'Finesse'], traits: [], debuffs: ['Fragility']},
            {sName: 'Ice Vortex', buffs: [], traits: [], debuffs: ['Slow']},
            {sName: 'Pestilence', buffs: [], traits: [], debuffs: ['Poison']},
            {sName: 'Poison Bolt', buffs: [], traits: [], debuffs: ['Poison']},
            {sName: 'Poison Cloud', buffs: [], traits: [], debuffs: ['Poison', 'Weakness']},
            {sName: 'Poison Puddle', buffs: [], traits: [], debuffs: ['Poison', 'Debilitated']},
            {sName: 'Resonant Slam', buffs: ['Prowess', 'Resilience'], traits: ['Brutal'], debuffs: []},
            {sName: 'Seismic Shock', buffs: ['Prowess', 'Resilience'], traits: [], debuffs: []},
            {sName: 'Shadow Bolt', buffs: ['Aptitude'], traits: [], debuffs: ['Doom']},
            {sName: 'Shadow orb', buffs: [], traits: [], debuffs: ['Doom']},
            {sName: 'Shadow Spikes', buffs: [], traits: [], debuffs: []},
            {sName: 'Subdue', buffs: [], traits: [], debuffs: []},
            {sName: 'Summon Helper Elves', buffs: [], traits: ['Cunning'], debuffs: ['Slow']},
            {sName: 'Titans Cleaver', buffs: ['Finesse'], traits: [], debuffs: []},
            {sName: 'Void', buffs: [], traits: [], debuffs: ['Doom']},
        ],
    },
    {
        hero: 'monkeyking',
        wArray: [
            {wName: 'Massive Slam', buffs: ['Prowess'], traits: [], debuffs: []},
            {wName: 'Spinning Staff', buffs: ['Prowess'], traits: [], debuffs: ['Shattered']},
            {wName: 'Tempestuous Slash', buffs: ['Electrified', 'Form'], traits: [], debuffs: []},
            {wName: 'Nimbus Lightning', buffs: ['Electrified'], traits: [], debuffs: ['Dazed']},
            {wName: 'Gunpowder Strike', buffs: [], traits: [], debuffs: ['Bleed', 'Weakness']},
            {wName: 'Trickster Decoy', buffs: [], traits: [], debuffs: ['Bleed']},
            {wName: 'Fracturing Blow', buffs: ['Colossal'], traits: [], debuffs: []},
            {wName: 'Rock Crushing', buffs: ['Colossal', 'Resilience'], traits: [], debuffs: []},
        ],
        sArray: [
            {sName: 'Electric Strike', buffs: ['Electrified'], traits: [], debuffs: []},
            {sName: 'Expansive Throw', buffs: ['Prowess'], traits: [], debuffs: []},
            {sName: 'Whirling Defense', buffs: ['Prowess', 'Resilience'], traits: ['Brutal'], debuffs: []},
            {sName: 'Armor Shatter', buffs: ['Prowess'], traits: [], debuffs: ['Shattered']},
            {sName: 'Body Slam', buffs: ['Prowess'], traits: [], debuffs: []},
            {sName: 'Bomb Barrage', buffs: [], traits: [], debuffs: ['Bleed']},
            {sName: 'Chain Lightning', buffs: ['Electrified'], traits: [], debuffs: ['Distracted']},
            {sName: 'Chromatic Bolt', buffs: [], traits: [], debuffs: []},
            {sName: 'Earth bolt', buffs: ['Colossal'], traits: [], debuffs: []},
            {sName: 'Earthquake', buffs: ['Colossal'], traits: [], debuffs: ['Brittle']},
            {sName: 'Earth Shield', buffs: ['Resilience'], traits: [], debuffs: []},
            {sName: 'Explosive Trap', buffs: [], traits: [], debuffs: ['Bleed', 'Disoriented']},
            {sName: 'Ground Break', buffs: ['Prowess'], traits: ['Piercing'], debuffs: []},
            {sName: 'Holy Beam', buffs: ['Purity', 'Prowess'], traits: [], debuffs: []},
            {sName: 'Light Beam', buffs: [], traits: [], debuffs: ['Exposed']},
            {sName: 'Lightning bolt', buffs: ['Electrified'], traits: ['Devastating'], debuffs: []},
            {sName: 'Lightning Surge', buffs: [], traits: [], debuffs: ['Dazed']},
            {sName: 'Living Weapons', buffs: [], traits: [], debuffs: ['Dazed']},
            {sName: 'Might', buffs: [], traits: [], debuffs: []},
            {sName: 'Mine Field', buffs: [], traits: [], debuffs: ['Bleed']},
            {sName: 'Power Conductor', buffs: ['Electrified'], traits: [], debuffs: ['Dazed']},
            {sName: 'Resonant Slam', buffs: ['Prowess', 'Resilience'], traits: ['Brutal'], debuffs: []},
            {sName: 'Rolling Boulder', buffs: [], traits: [], debuffs: ['Stun']},
            {sName: 'Seismic Shock', buffs: ['Prowess', 'Resilience'], traits: [], debuffs: []},
            {sName: 'Shockwave Totem', buffs: [], traits: [], debuffs: ['Dazed']},
            {sName: 'Shrapnel Bomb', buffs: [], traits: [], debuffs: []},
            {sName: 'Smite', buffs: ['Purity'], traits: [], debuffs: []},
            {sName: 'Suction Bomb', buffs: [], traits: [], debuffs: ['Bleed']},
            {sName: 'Surprise Gift', buffs: [], traits: [], debuffs: ['Bleed', 'Weakness']},
            {sName: 'Thunder strike', buffs: ['Electrified'], traits: [], debuffs: ['Stun']},
        ],
    },
    {
        hero: 'engineer',
        wArray: [
            {wName: 'Burst Of Lead', buffs: ['Aptitude'], traits: ['Brutal'], debuffs: ['Dazed']},
            {wName: 'Guided Missiles', buffs: ['Aptitude'], traits: ['Impactful'], debuffs: []},
            {wName: 'EZ Sentry', buffs: ['Ammunition'], traits: ['Cunning'], debuffs: ['Bleed']},
            {wName: 'EZ Mechanical Spider', buffs: ['Ammunition'], traits: ['Cunning'], debuffs: ['Shattered']},
            {wName: 'Energizer', buffs: ['Electrified'], traits: [], debuffs: []},
            {wName: 'Power Generator', buffs: ['Electrified'], traits: [], debuffs: ['Dazed']},
            {wName: 'QT Bombuddy 1000', buffs: [], traits: ['Impactful'], debuffs: []},
            {wName: 'QT Land Surprise', buffs: [], traits: [], debuffs: ['Bleed']},
        ],
        sArray: [
            {sName: 'Ammo Box', buffs: ['Ammunition'], traits: [], debuffs: []},
            {sName: 'Heavy Artillery', buffs: [], traits: ['Impactful'], debuffs: ['Bleed', 'Weakness']},
            {sName: 'Portable Nuke', buffs: [], traits: ['Devastating'], debuffs: ['Disoriented', 'Stun']},
            {sName: 'Bladed Chakram', buffs: ['Aptitude'], traits: ['Piercing'], debuffs: []},
            {sName: 'Bomb Barrage', buffs: [], traits: [], debuffs: ['Bleed']},
            {sName: 'Camors Arrow', buffs: [], traits: [], debuffs: ['Fragility', 'Stun']},
            {sName: 'Chain Lightning', buffs: ['Electrified'], traits: [], debuffs: ['Distracted']},
            {sName: 'Chromatic Bolt', buffs: [], traits: [], debuffs: []},
            {sName: 'Earth bolt', buffs: ['Colossal'], traits: [], debuffs: []},
            {sName: 'Earthquake', buffs: ['Colossal'], traits: [], debuffs: ['Brittle']},
            {sName: 'Earth Shield', buffs: ['Resilience'], traits: [], debuffs: []},
            {sName: 'Egg Shooter', buffs: [], traits: [], debuffs: ['Dazed']},
            {sName: 'Explosive Shot', buffs: ['Ammunition'], traits: [], debuffs: ['Shattered']},
            {sName: 'Explosive Trap', buffs: [], traits: [], debuffs: ['Bleed', 'Disoriented']},
            {sName: 'Frag Shot', buffs: ['Aptitude'], traits: [], debuffs: ['Dazed']},
            {sName: 'Heartbreak Orbs', buffs: ['Aptitude'], traits: ['Precise'], debuffs: []},
            {sName: 'Lightning bolt', buffs: ['Electrified'], traits: ['Devastating'], debuffs: []},
            {sName: 'Lightning Surge', buffs: [], traits: [], debuffs: ['Dazed']},
            {sName: 'Mine Field', buffs: [], traits: [], debuffs: ['Bleed']},
            {sName: 'Napalm Blast', buffs: ['Ammunition'], traits: [], debuffs: ['Shattered']},
            {sName: 'Power Conductor', buffs: ['Electrified'], traits: [], debuffs: ['Dazed']},
            {sName: 'Rapid Barrage', buffs: ['Ammunition'], traits: [], debuffs: []},
            {sName: 'Rolling Boulder', buffs: [], traits: [], debuffs: ['Stun']},
            {sName: 'Shockwave Totem', buffs: [], traits: [], debuffs: ['Dazed']},
            {sName: 'Shrapnel Bomb', buffs: [], traits: [], debuffs: []},
            {sName: 'Shrapnel Shot', buffs: ['Ammunition'], traits: [], debuffs: ['Bleed']},
            {sName: 'Spread Shot', buffs: ['Aptitude'], traits: [], debuffs: ['Dazed']},
            {sName: 'Storm Of Arrows', buffs: [], traits: [], debuffs: []},
            {sName: 'Suction Bomb', buffs: [], traits: [], debuffs: ['Bleed']},
            {sName: 'Summon Ballista', buffs: [], traits: ['Piercing', 'Cunning'], debuffs: []},
            {sName: 'Surprise Gift', buffs: [], traits: [], debuffs: ['Bleed', 'Weakness']},
            {sName: 'Thunder strike', buffs: ['Electrified'], traits: [], debuffs: ['Stun']},
            {sName: 'Weakening Shot', buffs: ['Ammunition'], traits: [], debuffs: ['Exposed']},
        ],
    },
    {
        hero: 'myrmidon',
        wArray: [
            {wName: 'Glacial Trident', buffs: ['IcyVeins'], traits: [], debuffs: ['Slow']},
            {wName: 'Frozen Shard', buffs: [], traits: [], debuffs: ['Slow']},
            {wName: 'Tidal Thrust', buffs: ['Form'], traits: [], debuffs: []},
            {wName: 'Incisive Strike', buffs: [], traits: ['Piercing'], debuffs: []},
            {wName: 'Sanctified Throw', buffs: ['Purity'], traits: ['Devastating'], debuffs: ['Dazed']},
            {wName: 'Holy Frenzy', buffs: ['Purity'], traits: [], debuffs: ['Dazed']},
            {wName: 'Abyssal Fissure', buffs: ['Colossal', 'Form'], traits: [], debuffs: []},
            {wName: 'Fury Of The Depths', buffs: ['Resilience'], traits: [], debuffs: []},
        ],
        sArray: [
            {sName: 'Jawstorm', buffs: ['IcyVeins'], traits: [], debuffs: ['Fragility']},
            {sName: 'Precision Wave', buffs: [], traits: [], debuffs: []},
            {sName: 'Sea Current', buffs: ['IcyVeins'], traits: ['Brutal'], debuffs: ['Slow']},
            {sName: 'Arcane Beam', buffs: [], traits: [], debuffs: ['Brittle']},
            {sName: 'Arcane Disc', buffs: ['Radiance'], traits: ['Piercing'], debuffs: []},
            {sName: 'Arcane Power', buffs: [], traits: [], debuffs: []},
            {sName: 'Arcane Sparks', buffs: ['Radiance'], traits: ['Piercing'], debuffs: []},
            {sName: 'Avalanche', buffs: [], traits: [], debuffs: ['Fragility', 'Slow']},
            {sName: 'Blizzard', buffs: [], traits: [], debuffs: ['Slow']},
            {sName: 'Chromatic Bolt', buffs: [], traits: [], debuffs: []},
            {sName: 'Earth bolt', buffs: ['Colossal'], traits: [], debuffs: []},
            {sName: 'Earthquake', buffs: ['Colossal'], traits: [], debuffs: ['Brittle']},
            {sName: 'Earth Shield', buffs: ['Resilience'], traits: [], debuffs: []},
            {sName: 'Flurry', buffs: ['Form'], traits: [], debuffs: ['Bleed']},
            {sName: 'Frost Bolt', buffs: ['IcyVeins'], traits: [], debuffs: []},
            {sName: 'Frost Totem', buffs: [], traits: ['Cunning'], debuffs: ['Slow']},
            {sName: 'Glacier', buffs: [], traits: [], debuffs: ['Disoriented', 'Slow']},
            {sName: 'Holy Beam', buffs: ['Purity', 'Prowess'], traits: [], debuffs: []},
            {sName: 'Ice Vortex', buffs: [], traits: [], debuffs: ['Slow']},
            {sName: 'Light Beam', buffs: [], traits: [], debuffs: ['Exposed']},
            {sName: 'Living Weapons', buffs: [], traits: [], debuffs: ['Dazed']},
            {sName: 'Magic Missiles', buffs: [], traits: [], debuffs: ['Fragility']},
            {sName: 'Might', buffs: [], traits: [], debuffs: []},
            {sName: 'On Guard', buffs: ['Bulwark', 'Form'], traits: [], debuffs: ['Exposed']},
            {sName: 'Quick Strike', buffs: ['Form', 'Haste'], traits: [], debuffs: []},
            {sName: 'Rolling Boulder', buffs: [], traits: [], debuffs: ['Stun']},
            {sName: 'Sharp Spear', buffs: ['Haste', 'Form'], traits: ['Piercing'], debuffs: []},
            {sName: 'Shockwave Totem', buffs: [], traits: [], debuffs: ['Dazed']},
            {sName: 'Smite', buffs: ['Purity'], traits: [], debuffs: []},
            {sName: 'Spear Trap', buffs: ['Form'], traits: [], debuffs: ['Exposed']},
            {sName: 'Sugar Rush', buffs: [], traits: [], debuffs: []},
            {sName: 'Summon Helper Elves', buffs: [], traits: ['Cunning'], debuffs: ['Slow']},
        ],
    },
]