export const all = [
    {
        hero: 'barbarian',
        wArray: [
            {wName: 'Demolish', wImg: 'Demolish'},
            {wName: 'Ground Slam', wImg: 'GroundSlam'},
            {wName: 'Heavy Strike', wImg: 'HeavyStrike'},
            {wName: 'Shockwave', wImg: 'Shockwave'},
            {wName: 'Throw Axe', wImg: 'ThrowAxe'},
            {wName: 'Thunder Clap', wImg: 'ThunderClap'},
            {wName: 'Thundering Slash', wImg: 'ThunderingSlash'},
            {wName: 'Whirlwind', wImg: 'Whirlwind'},
        ],
        sArray: [
            {sName: 'Piercing Shout', sImg: ''},
            {sName: 'Savage Strike', sImg: ''},
            {sName: 'Scent Of Blood', sImg: ''},
            {sName: 'Armor Shatter', sImg: ''},
            {sName: 'Bladestorm', sImg: ''},
            {sName: 'Bloody Saw', sImg: ''},
            {sName: 'Body Slam', sImg: ''},
            {sName: 'Chain Lightning', sImg: ''},
            {sName: 'Chromatic Bolt', sImg: ''},
            {sName: 'Double Slash', sImg: ''},
            {sName: 'Earth Bolt', sImg: ''},
            {sName: 'Earthquake', sImg: ''},
            {sName: 'Earth Shield', sImg: ''},
            {sName: 'Flurry', sImg: ''},
            {sName: 'Ground Break', sImg: ''},
            {sName: 'Heartrending Strike', sImg: ''},
            {sName: 'Lightning Bolt', sImg: ''},
            {sName: 'Lightning Surge', sImg: ''},
            {sName: 'On Guard', sImg: ''},
            {sName: 'Power Conductor', sImg: ''},
            {sName: 'Quick Strike', sImg: ''},
            {sName: 'Resonant Slam', sImg: ''},
            {sName: 'Rolling Boulder', sImg: ''},
            {sName: 'Seismic Shock', sImg: ''},
            {sName: 'Sharp Spear', sImg: ''},
            {sName: 'Shockwave Totem', sImg: ''},
            {sName: 'Spear Trap', sImg: ''},
            {sName: 'Subdue', sImg: ''},
            {sName: 'Sugar Rush', sImg: ''},
            {sName: 'Thunder Strike', sImg: ''},
            {sName: 'Titans Cleaver', sImg: ''},

        ],
    },
    {
        hero: 'pyromancer',
        wArray: [
            {wName: 'Chaos Eruption', wImg: 'ChaosEruption'},
            {wName: 'Chaotic Inferno', wImg: 'ChaoticInferno'},
            {wName: 'Dark Swarm', wImg: 'DarkSwarm'},
            {wName: 'Fire Slash', wImg: 'FireSlash'},
            {wName: 'Fire Walk', wImg: 'FireWalk'},
            {wName: 'Gathering Shadows', wImg: 'GatheringShadows'},
            {wName: 'Lightning Field', wImg: 'LightningField'},
            {wName: 'Overcharged Blast', wImg: 'OverchargedBlast'},
        ],
        sArray: [
            {sName: 'Conflagrate', sImg: ''},
            {sName: 'Fire Wall', sImg: ''},
            {sName: 'Meteor Shower', sImg: ''},
            {sName: 'Arcane Beam', sImg: ''},
            {sName: 'Arcane Disc', sImg: ''},
            {sName: 'Arcane Power', sImg: ''},
            {sName: 'Arcane Sparks', sImg: ''},
            {sName: 'Bloodlust', sImg: ''},
            {sName: 'Chain Lightning', sImg: ''},
            {sName: 'Chaos Bolt', sImg: ''},
            {sName: 'Chaotic Explosion', sImg: ''},
            {sName: 'Chromatic Bolt', sImg: ''},
            {sName: 'Combustion', sImg: ''},
            {sName: 'Death Claw', sImg: ''},
            {sName: 'Death Vortex', sImg: ''},
            {sName: 'Fire Bolt', sImg: ''},
            {sName: 'Flamethrower', sImg: ''},
            {sName: 'Flame Wave', sImg: ''},
            {sName: 'Frenzied Bunnies', sImg: ''},
            {sName: 'Lightning Bolt', sImg: ''},
            {sName: 'Lightning Surge', sImg: ''},
            {sName: 'Magic Missiles', sImg: ''},
            {sName: 'Meteor', sImg: ''},
            {sName: 'Power Conductor', sImg: ''},
            {sName: 'Shadow Bolt', sImg: ''},
            {sName: 'Shadow Orb', sImg: ''},
            {sName: 'Shadow Spikes', sImg: ''},
            {sName: 'Summon Chaos Golem', sImg: ''},
            {sName: 'Thunder Strike', sImg: ''},
            {sName: 'Void', sImg: ''},
        ],
    },
    {
        hero: 'houndmaster',
        wArray: [
            {wName: 'Bolt Barrage', wImg: 'BoltBarrage'},
            {wName: 'Bombardment', wImg: 'Bombardment'},
            {wName: 'Buckshot', wImg: 'Buckshot'},
            {wName: 'Cyclone Shot', wImg: 'CycloneShot'},
            {wName: 'Mortar Shot', wImg: 'MortarShot'},
            {wName: 'Pesticide Burst', wImg: 'PesticideBurst'},
            {wName: 'Power Blast', wImg: 'PowerBlast'},
            {wName: 'Threshing Blast', wImg: 'ThreshingBlast'},
        ],
        sArray: [
            {sName: 'Bear Trap', sImg: ''},
            {sName: 'Shrapnel Mine', sImg: ''},
            {sName: 'Weakening Grenade', sImg: ''},
            {sName: 'Acid Rain', sImg: ''},
            {sName: 'Bladed Chakram', sImg: ''},
            {sName: 'Bomb Barrage', sImg: ''},
            {sName: 'Camors Arrow', sImg: ''},
            {sName: 'Chromatic Bolt', sImg: ''},
            {sName: 'Combustion', sImg: ''},
            {sName: 'Egg Shooter', sImg: ''},
            {sName: 'Explosive Shot', sImg: ''},
            {sName: 'Explosive Trap', sImg: ''},
            {sName: 'Fire Bolt', sImg: ''},
            {sName: 'Flamethrower', sImg: ''},
            {sName: 'Flame Wave', sImg: ''},
            {sName: 'Frag Shot', sImg: ''},
            {sName: 'Heartbreak Orbs', sImg: ''},
            {sName: 'Meteor', sImg: ''},
            {sName: 'Mine Field', sImg: ''},
            {sName: 'Napalm Blast', sImg: ''},
            {sName: 'Pestilence', sImg: ''},
            {sName: 'Poison Bolt', sImg: ''},
            {sName: 'Poison Cloud', sImg: ''},
            {sName: 'Poison Puddle', sImg: ''},
            {sName: 'Rapid Barrage', sImg: ''},
            {sName: 'Shrapnel Bomb', sImg: ''},
            {sName: 'Shrapnel Shot', sImg: ''},
            {sName: 'Spread Shot', sImg: ''},
            {sName: 'Storm Of Arrows', sImg: ''},
            {sName: 'Suction Bomb', sImg: ''},
            {sName: 'Summon Ballista', sImg: ''},
            {sName: 'Surprise Gift', sImg: ''},
            {sName: 'Weakening Shot', sImg: ''},
        ],
    },
    {
        hero: 'spellblade',
        wArray: [
            {wName: 'Arcane Overload', wImg: 'ArcaneOverload'},
            {wName: 'Arcane Slash', wImg: 'ArcaneSlash'},
            {wName: 'Arctic Assault', wImg: 'ArcticAssault'},
            {wName: 'Fiery Blades', wImg: 'FieryBlades'},
            {wName: 'Firestorm', wImg: 'Firestorm'},
            {wName: 'Frozen Blade', wImg: 'FrozenBlade'},
            {wName: 'Slash', wImg: 'Slash'},
            {wName: 'Uppercut', wImg: 'Uppercut'},
        ],
        sArray: [
            {sName: 'Arcane Assault', sImg: ''},
            {sName: 'Arcane Blade', sImg: ''},
            {sName: 'Arcane Rift', sImg: ''},
            {sName: 'Arcane Beam', sImg: ''},
            {sName: 'Arcane Disc', sImg: ''},
            {sName: 'Arcane Power', sImg: ''},
            {sName: 'Arcane Sparks', sImg: ''},
            {sName: 'Avalanche', sImg: ''},
            {sName: 'Bladestorm', sImg: ''},
            {sName: 'Blizzard', sImg: ''},
            {sName: 'Bloody Saw', sImg: ''},
            {sName: 'Chromatic Bolt', sImg: ''},
            {sName: 'Combustion', sImg: ''},
            {sName: 'Double Slash', sImg: ''},
            {sName: 'Fire Bolt', sImg: ''},
            {sName: 'Flamethrower', sImg: ''},
            {sName: 'Flame Wave', sImg: ''},
            {sName: 'Flurry', sImg: ''},
            {sName: 'Frost Bolt', sImg: ''},
            {sName: 'Frost Totem', sImg: ''},
            {sName: 'Glacier', sImg: ''},
            {sName: 'Heartrending Strike', sImg: ''},
            {sName: 'Ice Vortex', sImg: ''},
            {sName: 'Magic Missiles', sImg: ''},
            {sName: 'Meteor', sImg: ''},
            {sName: 'On Guard', sImg: ''},
            {sName: 'Quick Strike', sImg: ''},
            {sName: 'Sharp Spear', sImg: ''},
            {sName: 'Spear Trap', sImg: ''},
            {sName: 'Subdue', sImg: ''},
            {sName: 'Sugar Rush', sImg: ''},
            {sName: 'Summon Helper Elves', sImg: ''},
            {sName: 'Titans Cleaver', sImg: ''},
        ],
    },
    {
        hero: 'arcaneweaver',
        wArray: [
            {wName: 'Arcane Explosion', wImg: 'ArcaneExplosion'},
            {wName: 'Arcane Missiles', wImg: 'ArcaneMissiles'},
            {wName: 'Celestial Retribution', wImg: 'CelestialRetribution'},
            {wName: 'Fiery Missiles', wImg: 'FieryMissiles'},
            {wName: 'Fire Pillar', wImg: 'FirePillar'},
            {wName: 'Frost Beam', wImg: 'FrostBeam'},
            {wName: 'Ice Shield', wImg: 'IceShield'},
            {wName: 'Sacred Orb', wImg: 'SacredOrb'},
        ],
        sArray: [
            {sName: 'Arcane Conjuration', sImg: ''},
            {sName: 'Arcane Orb', sImg: ''},
            {sName: 'Arcane Shield', sImg: ''},
            {sName: 'Arcane Beam', sImg: ''},
            {sName: 'Arcane Disc', sImg: ''},
            {sName: 'Arcane Power', sImg: ''},
            {sName: 'Arcane Sparks', sImg: ''},
            {sName: 'Avalanche', sImg: ''},
            {sName: 'Blizzard', sImg: ''},
            {sName: 'Bloodlust', sImg: ''},
            {sName: 'Chaos Bolt', sImg: ''},
            {sName: 'Chaotic Explosion', sImg: ''},
            {sName: 'Chromatic Bolt', sImg: ''},
            {sName: 'Combustion', sImg: ''},
            {sName: 'Death Claw', sImg: ''},
            {sName: 'Fire Bolt', sImg: ''},
            {sName: 'Flamethrower', sImg: ''},
            {sName: 'Flame Wave', sImg: ''},
            {sName: 'Frenzied Bunnies', sImg: ''},
            {sName: 'Frost Bolt', sImg: ''},
            {sName: 'Frost Totem', sImg: ''},
            {sName: 'Glacier', sImg: ''},
            {sName: 'Holy Beam', sImg: ''},
            {sName: 'Ice Vortex', sImg: ''},
            {sName: 'Light Beam', sImg: ''},
            {sName: 'Living Weapons', sImg: ''},
            {sName: 'Magic Missiles', sImg: ''},
            {sName: 'Meteor', sImg: ''},
            {sName: 'Might', sImg: ''},
            {sName: 'Smite', sImg: ''},
            {sName: 'Summon Chaos Golem', sImg: ''},
            {sName: 'Summon Helper Elves', sImg: ''},
        ],
    },
    {
        hero: 'sentinel',
        wArray: [
            {wName: 'Cluster Bomb', wImg: 'ClusterBomb'},
            {wName: 'Explosive Arrows', wImg: 'ExplosiveArrows'},
            {wName: 'Noxious Shot', wImg: 'NoxiousShot'},
            {wName: 'Obscure Arrow', wImg: 'ObscureArrow'},
            {wName: 'Rain Of Arrows', wImg: 'RainOfArrows'},
            {wName: 'Shoot', wImg: 'Shoot'},
            {wName: 'Venomous Volley', wImg: 'VenomousVolley'},
            {wName: 'Void Trap', wImg: 'VoidTrap'},
        ],
        sArray: [
            {sName: 'Ricochet Shot', sImg: ''},
            {sName: 'Sniper Shot', sImg: ''},
            {sName: 'Split Shot', sImg: ''},
            {sName: 'Acid Rain', sImg: ''},
            {sName: 'Avalanche', sImg: ''},
            {sName: 'Bladed Chakram', sImg: ''},
            {sName: 'Blizzard', sImg: ''},
            {sName: 'Bomb Barrage', sImg: ''},
            {sName: 'Camors Arrow', sImg: ''},
            {sName: 'Chromatic Bolt', sImg: ''},
            {sName: 'Death Vortex', sImg: ''},
            {sName: 'Egg Shooter', sImg: ''},
            {sName: 'Explosive Trap', sImg: ''},
            {sName: 'Frag Shot', sImg: ''},
            {sName: 'Frost Bolt', sImg: ''},
            {sName: 'Frost Totem', sImg: ''},
            {sName: 'Glacier', sImg: ''},
            {sName: 'Heartbreak Orbs', sImg: ''},
            {sName: 'Ice Vortex', sImg: ''},
            {sName: 'Mine Field', sImg: ''},
            {sName: 'Pestilence', sImg: ''},
            {sName: 'Poison Bolt', sImg: ''},
            {sName: 'Poison Cloud', sImg: ''},
            {sName: 'Poison Puddle', sImg: ''},
            {sName: 'Shadow Bolt', sImg: ''},
            {sName: 'Shadow Orb', sImg: ''},
            {sName: 'Shadow Spikes', sImg: ''},
            {sName: 'Shrapnel Bomb', sImg: ''},
            {sName: 'Spread Shot', sImg: ''},
            {sName: 'Storm Of Arrows', sImg: ''},
            {sName: 'Suction Bomb', sImg: ''},
            {sName: 'Summon Ballista', sImg: ''},
            {sName: 'Summon Helper Elves', sImg: ''},
            {sName: 'Surprise Gift', sImg: ''},
            {sName: 'Void', sImg: ''},
        ],
    },
    {
        hero: 'paladin',
        wArray: [
            {wName: 'Arcane Mace', wImg: 'ArcaneMace'},
            {wName: 'Blades Of Light', wImg: 'BladesOfLight'},
            {wName: 'Fissure Strike', wImg: 'FissureStrike'},
            {wName: 'Hammer Of Justice', wImg: 'HammerOfJustice'},
            {wName: 'Heroic Strike', wImg: 'HeroicStrike'},
            {wName: 'Holy Fire', wImg: 'HolyFire'},
            {wName: 'Radiant Light', wImg: 'RadiantLight'},
            {wName: 'Staggering Blow', wImg: 'StaggeringBlow'},
        ],
        sArray: [
            {sName: 'Beacon Of Light', sImg: ''},
            {sName: 'Penance', sImg: ''},
            {sName: 'Templars Verdict', sImg: ''},
            {sName: 'Arcane Beam', sImg: ''},
            {sName: 'Arcane Disc', sImg: ''},
            {sName: 'Arcane Power', sImg: ''},
            {sName: 'Arcane Sparks', sImg: ''},
            {sName: 'Armor Shatter', sImg: ''},
            {sName: 'Bladestorm', sImg: ''},
            {sName: 'Bloodysaw', sImg: ''},
            {sName: 'Body Slam', sImg: ''},
            {sName: 'Chain Lightning', sImg: ''},
            {sName: 'Chromatic Bolt', sImg: ''},
            {sName: 'Double Slash', sImg: ''},
            {sName: 'Ground Break', sImg: ''},
            {sName: 'Heartrending Strike', sImg: ''},
            {sName: 'Holy Beam', sImg: ''},
            {sName: 'Light Beam', sImg: ''},
            {sName: 'Lightning Bolt', sImg: ''},
            {sName: 'Lightning Surge', sImg: ''},
            {sName: 'Living Weapons', sImg: ''},
            {sName: 'Magic Missiles', sImg: ''},
            {sName: 'Might', sImg: ''},
            {sName: 'Power Conductor', sImg: ''},
            {sName: 'Resonant Slam', sImg: ''},
            {sName: 'Seismic Shock', sImg: ''},
            {sName: 'Smite', sImg: ''},
            {sName: 'Subdue', sImg: ''},
            {sName: 'Thunder Strike', sImg: ''},
            {sName: 'Titans Cleaver', sImg: ''},
        ],
    },
    {
        hero: 'chaoswalker',
        wArray: [
            {wName: 'Chaotic Missile', wImg: 'ChaoticMissile'},
            {wName: 'Corrosion', wImg: 'Corrosion'},
            {wName: 'Infected Shot', wImg: 'InfectedShot'},
            {wName: 'Orbs Of Destruction', wImg: 'OrbsOfDestruction'},
            {wName: 'Ripple Of Light', wImg: 'RippleOfLight'},
            {wName: 'Sanctified Orb', wImg: 'SanctifiedOrb'},
            {wName: 'Unchained Chaos', wImg: 'UnchainedChaos'},
            {wName: 'Volcano Eruption', wImg: 'VolcanoEruption'},
        ],
        sArray: [
            {sName: 'Chaos Totem', sImg: ''},
            {sName: 'Chaos Wave', sImg: ''},
            {sName: 'Manifestations Of Chaos', sImg: ''},
            {sName: 'Acid Rain', sImg: ''},
            {sName: 'Bloodlust', sImg: ''},
            {sName: 'Chaos Bolt', sImg: ''},
            {sName: 'Chaotic Explosion', sImg: ''},
            {sName: 'Chromatic Bolt', sImg: ''},
            {sName: 'Combustion', sImg: ''},
            {sName: 'Death Claw', sImg: ''},
            {sName: 'Death Vortex', sImg: ''},
            {sName: 'Fire Bolt', sImg: ''},
            {sName: 'Flamethrower', sImg: ''},
            {sName: 'Flame Wave', sImg: ''},
            {sName: 'Frenzied Bunnies', sImg: ''},
            {sName: 'Holy Beam', sImg: ''},
            {sName: 'Light Beam', sImg: ''},
            {sName: 'Living Weapons', sImg: ''},
            {sName: 'Meteor', sImg: ''},
            {sName: 'Might', sImg: ''},
            {sName: 'Pestilence', sImg: ''},
            {sName: 'Poison Bolt', sImg: ''},
            {sName: 'Poison Cloud', sImg: ''},
            {sName: 'Poison Puddle', sImg: ''},
            {sName: 'Shadow Bolt', sImg: ''},
            {sName: 'Shadow Orb', sImg: ''},
            {sName: 'Shadow Spikes', sImg: ''},
            {sName: 'Smite', sImg: ''},
            {sName: 'Summon Chaos Golem', sImg: ''},
            {sName: 'Void', sImg: ''},
        ],
    },
    {
        hero: 'beastmaster',
        wArray: [
            {wName: 'Brutal Slam', wImg: 'BrutalSlam'},
            {wName: 'Cobra Totem', wImg: 'CobraTotem'},
            {wName: 'Spider Cocoon', wImg: 'SpiderCocoon'},
            {wName: 'Cave Bear', wImg: 'SummonCaveBear'},
            {wName: 'Spider Queen', wImg: 'SummonSpiderQueen'},
            {wName: 'Swamp Boar', wImg: 'SummonSwampBoar'},
            {wName: 'Venomous Strike', wImg: 'VenomousStrike'},
            {wName: 'Wild Strike', wImg: 'WildStrike'},
        ],
        sArray: [
            {sName: 'Bestial Wrath', sImg: ''},
            {sName: 'Summon Battle Moose', sImg: ''},
            {sName: 'Summon War Tiger', sImg: ''},
            {sName: 'Acid Rain', sImg: ''},
            {sName: 'Armor Shatter', sImg: ''},
            {sName: 'Bladestorm', sImg: ''},
            {sName: 'Bloody Saw', sImg: ''},
            {sName: 'Body Slam', sImg: ''},
            {sName: 'Bomb Barrage', sImg: ''},
            {sName: 'Chromatic Bolt', sImg: ''},
            {sName: 'Combustion', sImg: ''},
            {sName: 'Double Slash', sImg: ''},
            {sName: 'Explosive Trap', sImg: ''},
            {sName: 'Fire Bolt', sImg: ''},
            {sName: 'Flamethrower', sImg: ''},
            {sName: 'Flame Wave', sImg: ''},
            {sName: 'Ground Break', sImg: ''},
            {sName: 'Heartrending Strike', sImg: ''},
            {sName: 'Meteor', sImg: ''},
            {sName: 'Mine Field', sImg: ''},
            {sName: 'Pestilence', sImg: ''},
            {sName: 'Poison Bolt', sImg: ''},
            {sName: 'Poison Cloud', sImg: ''},
            {sName: 'Poison Puddle', sImg: ''},
            {sName: 'Resonant Slam', sImg: ''},
            {sName: 'Seismic Shock', sImg: ''},
            {sName: 'Shrapnel Bomb', sImg: ''},
            {sName: 'Subdue', sImg: ''},
            {sName: 'Suction Bomb', sImg: ''},
            {sName: 'Surprise Gift', sImg: ''},
            {sName: 'Titans Cleaver', sImg: ''},
        ],
    },
    {
        hero: 'assassin',
        wArray: [
            {wName: 'Backstab', wImg: 'Backstab'},
            {wName: 'Debilitating Bomb', wImg: 'DebilitatingBomb'},
            {wName: 'Eviscerate', wImg: 'Eviscerate'},
            {wName: 'Fan Of Bombs', wImg: 'FanOfBombs'},
            {wName: 'Reap', wImg: 'Reap'},
            {wName: 'Shadow Stab', wImg: 'ShadowStab'},
            {wName: 'Sinister Strike', wImg: 'SinisterStrike'},
            {wName: 'Twin Daggers', wImg: 'TwinDaggers'},
        ],
        sArray: [
            {sName: 'Rupture', sImg: ''},
            {sName: 'Shadow Step', sImg: ''},
            {sName: 'Smoke Bomb', sImg: ''},
            {sName: 'Summon Assassin Enclave', sImg: ''},
            {sName: 'Acid Rain', sImg: ''},
            {sName: 'Bladestorm', sImg: ''},
            {sName: 'Bloody Saw', sImg: ''},
            {sName: 'Bomb Barrage', sImg: ''},
            {sName: 'Chromatic Bolt', sImg: ''},
            {sName: 'Death Vortex', sImg: ''},
            {sName: 'Double Slash', sImg: ''},
            {sName: 'Explosive Trap', sImg: ''},
            {sName: 'Flurry', sImg: ''},
            {sName: 'Heartrending Strike', sImg: ''},
            {sName: 'Mine Field', sImg: ''},
            {sName: 'On Guard', sImg: ''},
            {sName: 'Pestilence', sImg: ''},
            {sName: 'Poison Bolt', sImg: ''},
            {sName: 'Poison Cloud', sImg: ''},
            {sName: 'Poison Puddle', sImg: ''},
            {sName: 'Quick Strike', sImg: ''},
            {sName: 'Shadow Bolt', sImg: ''},
            {sName: 'Shadow Orb', sImg: ''},
            {sName: 'Shadow Spikes', sImg: ''},
            {sName: 'Sharp Spear', sImg: ''},
            {sName: 'Shrapnel Bomb', sImg: ''},
            {sName: 'Spear Trap', sImg: ''},
            {sName: 'Subdue', sImg: ''},
            {sName: 'Suction Bomb', sImg: ''},
            {sName: 'Sugar Rush', sImg: ''},
            {sName: 'Surprise Gift', sImg: ''},
            {sName: 'Titans Cleaver', sImg: ''},
            {sName: 'Void', sImg: ''},
        ],
    },
    {
        hero: 'elementalist',
        wArray: [
            {wName: 'Call Lightning', wImg: 'CallLightning'},
            {wName: 'Contaminated Cut', wImg: 'ContaminatedCut'},
            {wName: 'Freezing Blow', wImg: 'FreezingBlow'},
            {wName: 'Heat Explosion', wImg: 'HeatExplosion'},
            {wName: 'Lightning Beam', wImg: 'LightningBeam'},
            {wName: 'Outbreak', wImg: 'Outbreak'},
            {wName: 'Ray Of Fire', wImg: 'RayOfFire'},
            {wName: 'Severe Cold', wImg: 'SevereCold'},
        ],
        sArray: [
            {sName: 'Frozen Warhammer', sImg: ''},
            {sName: 'Lava Shield', sImg: ''},
            {sName: 'Tornado', sImg: ''},
            {sName: 'Acid Rain', sImg: ''},
            {sName: 'Avalanche', sImg: ''},
            {sName: 'Blizzard', sImg: ''},
            {sName: 'Chain Lightning', sImg: ''},
            {sName: 'Chromatic Bolt', sImg: ''},
            {sName: 'Combustion', sImg: ''},
            {sName: 'Earth Bolt', sImg: ''},
            {sName: 'Earthquake', sImg: ''},
            {sName: 'Earth Shield', sImg: ''},
            {sName: 'Fire Bolt', sImg: ''},
            {sName: 'Flamethrower', sImg: ''},
            {sName: 'Flame Wave', sImg: ''},
            {sName: 'Frost Bolt', sImg: ''},
            {sName: 'Frost Totem', sImg: ''},
            {sName: 'Glacier', sImg: ''},
            {sName: 'Ice Vortex', sImg: ''},
            {sName: 'Lightning Bolt', sImg: ''},
            {sName: 'Lightning Surge', sImg: ''},
            {sName: 'Meteor', sImg: ''},
            {sName: 'Pestilence', sImg: ''},
            {sName: 'Poison Bolt', sImg: ''},
            {sName: 'Poison Cloud', sImg: ''},
            {sName: 'Poison Puddle', sImg: ''},
            {sName: 'Power Conductor', sImg: ''},
            {sName: 'Rolling Boulder', sImg: ''},
            {sName: 'Shockwave Totem', sImg: ''},
            {sName: 'Summon Helper Elves', sImg: ''},
            {sName: 'Thunder Strike', sImg: ''},
        ],
    },
    {
        hero: 'legionnaire',
        wArray: [
            {wName: 'Corrosive Spear', wImg: 'CorrosiveSpear'},
            {wName: 'Incinerating Spear', wImg: 'IncineratingSpear'},
            {wName: 'Jupiters Spear', wImg: 'JupitersSpear'},
            {wName: 'Piercing Flames', wImg: 'PiercingFlames'},
            {wName: 'Purging Slam', wImg: 'PurgingSlam'},
            {wName: 'Shield Bash', wImg: 'ShieldBash'},
            {wName: 'Summon Infantry', wImg: 'SummonInfantry'},
            {wName: 'Thrust', wImg: 'Thrust'},
        ],
        sArray: [
            {sName: 'Intimidating Shout', sImg: ''},
            {sName: 'Shield Wall', sImg: ''},
            {sName: 'Storm Of Spears', sImg: ''},
            {sName: 'Acid Rain', sImg: ''},
            {sName: 'Bloodlust', sImg: ''},
            {sName: 'Chain Lightning', sImg: ''},
            {sName: 'Chaos Bolt', sImg: ''},
            {sName: 'Chaotic Explosion', sImg: ''},
            {sName: 'Chromatic Bolt', sImg: ''},
            {sName: 'Combustion', sImg: ''},
            {sName: 'Death Claw', sImg: ''},
            {sName: 'Fire Bolt', sImg: ''},
            {sName: 'Flamethrower', sImg: ''},
            {sName: 'Flame Wave', sImg: ''},
            {sName: 'Flurry', sImg: ''},
            {sName: 'Frenzied Bunnies', sImg: ''},
            {sName: 'Lightning Bolt', sImg: ''},
            {sName: 'Lightning Surge', sImg: ''},
            {sName: 'Meteor', sImg: ''},
            {sName: 'On Guard', sImg: ''},
            {sName: 'Pestilence', sImg: ''},
            {sName: 'Poison Bolt', sImg: ''},
            {sName: 'Poison Cloud', sImg: ''},
            {sName: 'Poison Puddle', sImg: ''},
            {sName: 'Power Conductor', sImg: ''},
            {sName: 'Quick Strike', sImg: ''},
            {sName: 'Sharp Spear', sImg: ''},
            {sName: 'Spear Trap', sImg: ''},
            {sName: 'Sugar Rush', sImg: ''},
            {sName: 'Summon Chaos Golem', sImg: ''},
            {sName: 'Thunder Strike', sImg: ''},
        ],
    },
    {
        hero: 'necromancer',
        wArray: [
            {wName: 'Carrion Crows', wImg: 'CarrionCrows'},
            {wName: 'Murder Of Crows', wImg: 'MurderOfCrows'},
            {wName: 'Putrefy', wImg: 'Putrefy'},
            {wName: 'Shadow Nova', wImg: 'ShadowNova'},
            {wName: 'Soul Release', wImg: 'SoulRelease'},
            {wName: 'Spectral Guardian', wImg: 'SpectralGuardian'},
            {wName: 'Plague Rats', wImg: 'SummonPlagueRats'},
            {wName: 'Skeletal Warriors', wImg: 'SummonSkeletalWarrior'},
        ],
        sArray: [
            {sName: 'Summon Putrid Hounds', sImg: ''},
            {sName: 'Summon Skeletal Archer', sImg: ''},
            {sName: 'Summon Skeletal Mage', sImg: ''},
            {sName: 'Acid Rain', sImg: ''},
            {sName: 'Arcane Beam', sImg: ''},
            {sName: 'Arcane Disc', sImg: ''},
            {sName: 'Arcane Power', sImg: ''},
            {sName: 'Arcane Sparks', sImg: ''},
            {sName: 'Avalanche', sImg: ''},
            {sName: 'Blizzard', sImg: ''},
            {sName: 'Bloodlust', sImg: ''},
            {sName: 'Chaos Bolt', sImg: ''},
            {sName: 'Chaotic Explosion', sImg: ''},
            {sName: 'Chromatic Bolt', sImg: ''},
            {sName: 'Death Claw', sImg: ''},
            {sName: 'Death Vortex', sImg: ''},
            {sName: 'Frenzied Bunnies', sImg: ''},
            {sName: 'Frost Bolt', sImg: ''},
            {sName: 'Frost Totem', sImg: ''},
            {sName: 'Glacier', sImg: ''},
            {sName: 'Ice Vortex', sImg: ''},
            {sName: 'Magic Missiles', sImg: ''},
            {sName: 'Pestilence', sImg: ''},
            {sName: 'Poison Bolt', sImg: ''},
            {sName: 'Poison Cloud', sImg: ''},
            {sName: 'Poison Puddle', sImg: ''},
            {sName: 'Shadow Bolt', sImg: ''},
            {sName: 'Shadow Orb', sImg: ''},
            {sName: 'Shadow Spikes', sImg: ''},
            {sName: 'Summon Chaos Golem', sImg: ''},
            {sName: 'Summon Helper Elves', sImg: ''},
            {sName: 'Void', sImg: ''},
        ],
    },
    {
        hero: 'deathknight',
        wArray: [
            {wName: 'Carnage', wImg: 'Carnage'},
            {wName: 'Festering Strike', wImg: 'FesteringStrike'},
            {wName: 'Frost Strike', wImg: 'FrostStrike'},
            {wName: 'Glacial Affinity', wImg: 'GlacialAffinity'},
            {wName: 'Lethal Blade', wImg: 'LethalBlade'},
            {wName: 'Obliterate', wImg: 'Obliterate'},
            {wName: 'Ravaging Strike', wImg: 'RavagingStrike'},
            {wName: 'Ray Of Doom', wImg: 'RayOfDoom'},
        ],
        sArray: [
            {sName: 'Contagion', sImg: ''},
            {sName: 'Path Of Decay', sImg: ''},
            {sName: 'Shadow Grasp', sImg: ''},
            {sName: 'Acid Rain', sImg: ''},
            {sName: 'Armor Shatter', sImg: ''},
            {sName: 'Avalanche', sImg: ''},
            {sName: 'Bladestorm', sImg: ''},
            {sName: 'Blizzard', sImg: ''},
            {sName: 'Bloody Saw', sImg: ''},
            {sName: 'Body Slam', sImg: ''},
            {sName: 'Chromatic Bolt', sImg: ''},
            {sName: 'Death Vortex', sImg: ''},
            {sName: 'Double Slash', sImg: ''},
            {sName: 'Frost Bolt', sImg: ''},
            {sName: 'Frost Totem', sImg: ''},
            {sName: 'Glacier', sImg: ''},
            {sName: 'Ground Break', sImg: ''},
            {sName: 'Heartrending Strike', sImg: ''},
            {sName: 'Ice Vortex', sImg: ''},
            {sName: 'Pestilence', sImg: ''},
            {sName: 'Poison Bolt', sImg: ''},
            {sName: 'Poison Cloud', sImg: ''},
            {sName: 'Poison Puddle', sImg: ''},
            {sName: 'Resonant Slam', sImg: ''},
            {sName: 'Seismic Shock', sImg: ''},
            {sName: 'Shadow Bolt', sImg: ''},
            {sName: 'Shadow Orb', sImg: ''},
            {sName: 'Shadow Spikes', sImg: ''},
            {sName: 'Subdue', sImg: ''},
            {sName: 'Summon Helper Elves', sImg: ''},
            {sName: 'Titans Cleaver', sImg: ''},
            {sName: 'Void', sImg: ''},
        ],
    },
    {
        hero: 'monkeyking',
        wArray: [
            {wName: 'Fracturing Blow', wImg: 'FracturingBlow'},
            {wName: 'Gunpowder Strike', wImg: 'GunpowderStrike'},
            {wName: 'Massive Slam', wImg: 'MassiveSlam'},
            {wName: 'Nimbus Lightning', wImg: 'NimbusLightning'},
            {wName: 'Rock Crushing', wImg: 'RockCrushing'},
            {wName: 'Spinning Staff', wImg: 'SpinningStaff'},
            {wName: 'Tempestuous Slash', wImg: 'TempestuousSlash'},
            {wName: 'Trickster Decoy', wImg: 'TricksterDecoy'},
        ],
        sArray: [
            {sName: 'Electric Strike', sImg: ''},
            {sName: 'Expansive Throw', sImg: ''},
            {sName: 'Whirling Defense', sImg: ''},
            {sName: 'Armor Shatter', sImg: ''},
            {sName: 'Body Slam', sImg: ''},
            {sName: 'Bomb Barrage', sImg: ''},
            {sName: 'Chain Lightning', sImg: ''},
            {sName: 'Chromatic Bolt', sImg: ''},
            {sName: 'Earth Bolt', sImg: ''},
            {sName: 'Earthquake', sImg: ''},
            {sName: 'Earth Shield', sImg: ''},
            {sName: 'Explosive Trap', sImg: ''},
            {sName: 'Ground Break', sImg: ''},
            {sName: 'Holy Beam', sImg: ''},
            {sName: 'Light Beam', sImg: ''},
            {sName: 'Lightning Bolt', sImg: ''},
            {sName: 'Lightning Surge', sImg: ''},
            {sName: 'Living Weapons', sImg: ''},
            {sName: 'Might', sImg: ''},
            {sName: 'Mine Field', sImg: ''},
            {sName: 'Power Conductor', sImg: ''},
            {sName: 'Resonant Slam', sImg: ''},
            {sName: 'Rolling Boulder', sImg: ''},
            {sName: 'Seismic Shock', sImg: ''},
            {sName: 'Shockwave Totem', sImg: ''},
            {sName: 'Shrapnel Bomb', sImg: ''},
            {sName: 'Smite', sImg: ''},
            {sName: 'Suction Bomb', sImg: ''},
            {sName: 'Surprise Gift', sImg: ''},
            {sName: 'Thunder Strike', sImg: ''},
        ],
    },
    {
        hero: 'engineer',
        wArray: [
            {wName: 'Burst Of Lead', wImg: 'BurstOfLead'},
            {wName: 'Energizer', wImg: 'Energizer'},
            {wName: 'EZ Mechanical Spider', wImg: 'EZMechanicalSpider'},
            {wName: 'EZ Sentry', wImg: 'EZSentry'},
            {wName: 'Guided Missiles', wImg: 'GuidedMissiles'},
            {wName: 'Power Generator', wImg: 'PowerGenerator'},
            {wName: 'QT Bombuddy 100', wImg: 'QTBombuddy1000'},
            {wName: 'QT Land Surprise', wImg: 'QTLandSurprise'},
        ],
        sArray: [
            {sName: 'Ammo Box', sImg: ''},
            {sName: 'Heavy Artillery', sImg: ''},
            {sName: 'Portable Nuke', sImg: ''},
            {sName: 'Bladed Chakram', sImg: ''},
            {sName: 'Bomb Barrage', sImg: ''},
            {sName: 'Camors Arrow', sImg: ''},
            {sName: 'Chain Lightning', sImg: ''},
            {sName: 'Chromatic Bolt', sImg: ''},
            {sName: 'Earth Bolt', sImg: ''},
            {sName: 'Earthquake', sImg: ''},
            {sName: 'Earth Shield', sImg: ''},
            {sName: 'Egg Shooter', sImg: ''},
            {sName: 'Explosive Shot', sImg: ''},
            {sName: 'Explosive Trap', sImg: ''},
            {sName: 'Frag Shot', sImg: ''},
            {sName: 'Heartbreak Orbs', sImg: ''},
            {sName: 'Lightning Bolt', sImg: ''},
            {sName: 'Lightning Surge', sImg: ''},
            {sName: 'Mine Field', sImg: ''},
            {sName: 'Napalm Blast', sImg: ''},
            {sName: 'Power Conductor', sImg: ''},
            {sName: 'Rapid Barrage', sImg: ''},
            {sName: 'Rolling Boulder', sImg: ''},
            {sName: 'Shockwave Totem', sImg: ''},
            {sName: 'Shrapnel Bomb', sImg: ''},
            {sName: 'Shrapnel Shot', sImg: ''},
            {sName: 'Spread Shot', sImg: ''},
            {sName: 'Storm Of Arrows', sImg: ''},
            {sName: 'Suction Bomb', sImg: ''},
            {sName: 'Summon Ballista', sImg: ''},
            {sName: 'Surprise Gift', sImg: ''},
            {sName: 'Thunder Strike', sImg: ''},
            {sName: 'Weakening Shot', sImg: ''},
        ],
    },
    {
        hero: 'myrmidon',
        wArray: [
            {wName: 'Abyssal Fissure', wImg: 'AbyssalFissure'},
            {wName: 'Frozen Shard', wImg: 'FrozenShard'},
            {wName: 'Fury Of The Depths', wImg: 'FuryOfTheDepths'},
            {wName: 'Glacial Trident', wImg: 'GlacialTrident'},
            {wName: 'Holy Frenzy', wImg: 'HolyFrenzy'},
            {wName: 'Incisive Strike', wImg: 'IncisiveStrike'},
            {wName: 'Sanctified Throw', wImg: 'SanctifiedThrow'},
            {wName: 'Tidal Thrust', wImg: 'TidalThrust'},
        ],
        sArray: [
            {sName: 'Jawstorm', sImg: ''},
            {sName: 'Precision Wave', sImg: ''},
            {sName: 'Sea Current', sImg: ''},
            {sName: 'Arcane Beam', sImg: ''},
            {sName: 'Arcane Disc', sImg: ''},
            {sName: 'Arcane Power', sImg: ''},
            {sName: 'Arcane Sparks', sImg: ''},
            {sName: 'Avalanche', sImg: ''},
            {sName: 'Blizzard', sImg: ''},
            {sName: 'Chromatic Bolt', sImg: ''},
            {sName: 'Earth Bolt', sImg: ''},
            {sName: 'Earthquake', sImg: ''},
            {sName: 'Earth Shield', sImg: ''},
            {sName: 'Flurry', sImg: ''},
            {sName: 'Frost Bolt', sImg: ''},
            {sName: 'Frost Totem', sImg: ''},
            {sName: 'Glacier', sImg: ''},
            {sName: 'Holy Beam', sImg: ''},
            {sName: 'Ice Vortex', sImg: ''},
            {sName: 'Light Beam', sImg: ''},
            {sName: 'Living Weapons', sImg: ''},
            {sName: 'Magic Missiles', sImg: ''},
            {sName: 'Might', sImg: ''},
            {sName: 'On Guard', sImg: ''},
            {sName: 'Quick Strike', sImg: ''},
            {sName: 'Rolling Boulder', sImg: ''},
            {sName: 'Sharp Spear', sImg: ''},
            {sName: 'Shockwave Totem', sImg: ''},
            {sName: 'Smite', sImg: ''},
            {sName: 'Spear Trap', sImg: ''},
            {sName: 'Sugar Rush', sImg: ''},
            {sName: 'Summon Helper Elves', sImg: ''},
        ],
    },
]