export const all = [
    {
        hero: 'barbarian',
        wArray: [
            {wName: 'Demolish', buffs: ['Colossal']},
            {wName: 'Ground Slam', buffs: ['Prowess']},
            {wName: 'Heavy Strike', buffs: ['Prowess', 'Resilience']},
            {wName: 'Shockwave', buffs: ['Colossal', 'Resilience']},
            {wName: 'Throw Axe', buffs: ['Finesse']},
            {wName: 'Thunder Clap', buffs: ['Electrified', 'Prowess']},
            {wName: 'Thundering Slash', buffs: ['Electrified']},
            {wName: 'Whirlwind', buffs: ['Bulwark', 'Finesse']},
        ],
        sArray: [
            {sName: 'Piercing Shout', buffs: []},
            {sName: 'Savage Strike', buffs: ['Finesse']},
            {sName: 'Scent Of Blood' , buffs: []},
            {sName: 'Armor Shatter', buffs: ['Prowess']},
            {sName: 'Bladestorm', buffs: []},
            {sName: 'Bloody Saw', buffs: ['Finesse']},
            {sName: 'Body Slam', buffs: ['Prowess']},
            {sName: 'Chain Lightning', buffs: ['Electrified']},
            {sName: 'Chromatic Bolt', buffs: []},
            {sName: 'Double Slash', buffs: ['Bulwark', 'Finesse']},
            {sName: 'Earth bolt', buffs: ['Colossal']},
            {sName: 'Earthquake', buffs: ['Colossal']},
            {sName: 'Earth Shield', buffs: ['Resilience']},
            {sName: 'Flurry', buffs: ['Form']},
            {sName: 'Ground Break', buffs: ['Prowess']},
            {sName: 'Heartrending Strike', buffs: ['Bulwark', 'Finesse']},
            {sName: 'Lightning bolt', buffs: ['Electrified']},
            {sName: 'Lightning Surge', buffs: []},
            {sName: 'On Guard', buffs: ['Bulwark', 'Form']},
            {sName: 'Power Conductor', buffs: ['Electrified']},
            {sName: 'Quick Strike', buffs: ['Form', 'Haste']},
            {sName: 'Resonant Slam', buffs: ['Prowess', 'Resilience']},
            {sName: 'Rolling Boulder', buffs: []},
            {sName: 'Seismic Shock', buffs: ['Prowess', 'Resilience']},
            {sName: 'Sharp Spear', buffs: ['Haste', 'Form']},
            {sName: 'Shockwave Totem', buffs: []},
            {sName: 'Spear Trap', buffs: ['Form']},
            {sName: 'Subdue', buffs: []},
            {sName: 'Sugar Rush', buffs: []},
            {sName: 'Thunder strike', buffs: ['Electrified']},
            {sName: 'Titans Cleaver', buffs: ['Finesse']},
        ],
    },
    {
        hero: 'pyromancer',
        wArray: [
            {wName: 'Chaos Eruption', buffs: []},
            {wName: 'Chaotic Inferno', buffs: []},
            {wName: 'Dark Swarm', buffs: []},
            {wName: 'Fire Slash', buffs: ['Haste']},
            {wName: 'Fire Walk', buffs: []},
            {wName: 'Gathering Shadows', buffs: []},
            {wName: 'Lightning Field', buffs: ['Electrified']},
            {wName: 'Overcharged Blast', buffs: ['Electrified']},
        ],
        sArray: [
            {sName: 'Conflagrate', buffs: []},
            {sName: 'Fire Wall', buffs: []},
            {sName: 'Meteor Shower', buffs: []},
            {sName: 'Arcane Beam', buffs: []},
            {sName: 'Arcane Disc', buffs: ['Radiance']},
            {sName: 'Arcane Power', buffs: []},
            {sName: 'Arcane Sparks', buffs: ['Radiance']},
            {sName: 'Bloodlust', buffs: []},
            {sName: 'Chain Lightning', buffs: ['Electrified']},
            {sName: 'Chaos Bolt', buffs: []},
            {sName: 'Chaotic Explosion', buffs: []},
            {sName: 'Chromatic Bolt', buffs: []},
            {sName: 'Combustion', buffs: []},
            {sName: 'Death Claw', buffs: []},
            {sName: 'Death Vortex', buffs: []},
            {sName: 'Fire bolt', buffs: []},
            {sName: 'Flamethrower', buffs: []},
            {sName: 'Flame Wave', buffs: []},
            {sName: 'Frenzied Bunnies', buffs: []},
            {sName: 'Lightning bolt', buffs: ['Electrified']},
            {sName: 'Lightning Surge', buffs: []},
            {sName: 'Magic Missiles', buffs: []},
            {sName: 'Meteor', buffs: []},
            {sName: 'Power Conductor', buffs: ['Electrified']},
            {sName: 'Shadow Bolt', buffs: ['Aptitude']},
            {sName: 'Shadow orb', buffs: []},
            {sName: 'Shadow Spikes', buffs: []},
            {sName: 'Summon Chaos Golem', buffs: []},
            {sName: 'Thunder strike', buffs: ['Electrified']},
            {sName: 'Void', buffs: []},
        ],
    },
    {
        hero: 'houndmaster',
        wArray: [
            {wName: 'Bolt Barrage', buffs: ['Aptitude']},
            {wName: 'Bombardment', buffs: []},
            {wName: 'Buckshot', buffs: ['Ammunition']},
            {wName: 'Cyclone Shot', buffs: ['Aptitude']},
            {wName: 'Mortar Shot', buffs: []},
            {wName: 'Pesticide Burst', buffs: []},
            {wName: 'Power Blast', buffs: ['Ammunition']},
            {wName: 'Threshing Blast', buffs: ['Ammunition']},
        ],
        sArray: [
            {sName: 'Bear Trap', buffs: []},
            {sName: 'Shrapnel Mine', buffs: []},
            {sName: 'Weakening Grenade', buffs: []},
            {sName: 'Acid Rain', buffs: []},
            {sName: 'Bladed Chakram', buffs: ['Aptitude']},
            {sName: 'Bomb Barrage', buffs: []},
            {sName: 'Camors Arrow', buffs: []},
            {sName: 'Chromatic Bolt', buffs: []},
            {sName: 'Combustion', buffs: []},
            {sName: 'Egg Shooter', buffs: []},
            {sName: 'Explosive Shot', buffs: ['Ammunition']},
            {sName: 'Explosive Trap', buffs: []},
            {sName: 'Fire bolt', buffs: []},
            {sName: 'Flamethrower', buffs: []},
            {sName: 'Flame Wave', buffs: []},
            {sName: 'Frag Shot', buffs: ['Aptitude']},
            {sName: 'Heartbreak Orbs', buffs: ['Aptitude']},
            {sName: 'Meteor', buffs: []},
            {sName: 'Mine Field', buffs: []},
            {sName: 'Napalm Blast', buffs: ['Ammunition']},
            {sName: 'Pestilence', buffs: []},
            {sName: 'Poison Bolt', buffs: []},
            {sName: 'Poison Cloud', buffs: []},
            {sName: 'Poison Puddle', buffs: []},
            {sName: 'Rapid Barrage', buffs: ['Ammunition']},
            {sName: 'Shrapnel Bomb', buffs: []},
            {sName: 'Shrapnel Shot', buffs: ['Ammunition']},
            {sName: 'Spread Shot', buffs: ['Aptitude']},
            {sName: 'Storm Of Arrows', buffs: []},
            {sName: 'Suction Bomb', buffs: []},
            {sName: 'Summon Ballista', buffs: []},
            {sName: 'Surprise Gift', buffs: []},
            {sName: 'Weakening Shot', buffs: ['Ammunition']},
        ],
    },
    {
        hero: 'spellblade',
        wArray: [
            {wName: 'Arcane Overload', buffs: ['Radiance']},
            {wName: 'Arcane Slash', buffs: ['Finesse', 'Radiance']},
            {wName: 'Arctic Assault', buffs: ['IcyVeins']},
            {wName: 'Fiery Blades', buffs: []},
            {wName: 'Firestorm', buffs: ['Haste']},
            {wName: 'Frozen Blade', buffs: ['IcyVeins']},
            {wName: 'Slash', buffs: ['Bulwark', 'Finesse']},
            {wName: 'Uppercut', buffs: []},
        ],
        sArray: [
            {sName: 'Arcane Assault', buffs: ['Radiance']},
            {sName: 'Arcane Blade', buffs: ['Finesse', 'Radiance']},
            {sName: 'Arcane Rift', buffs: []},
            {sName: 'Arcane Beam', buffs: []},
            {sName: 'Arcane Disc', buffs: ['Radiance']},
            {sName: 'Arcane Power', buffs: []},
            {sName: 'Arcane Sparks', buffs: ['Radiance']},
            {sName: 'Avalanche', buffs: []},
            {sName: 'Bladestorm', buffs: []},
            {sName: 'Blizzard', buffs: []},
            {sName: 'Bloody Saw', buffs: ['Finesse']},
            {sName: 'Chromatic Bolt', buffs: []},
            {sName: 'Combustion', buffs: []},
            {sName: 'Double Slash', buffs: ['Bulwark', 'Finesse']},
            {sName: 'Fire bolt', buffs: []},
            {sName: 'Flamethrower', buffs: []},
            {sName: 'Flame Wave', buffs: []},
            {sName: 'Flurry', buffs: ['Form']},
            {sName: 'Frost Bolt', buffs: ['IcyVeins']},
            {sName: 'Frost Totem', buffs: []},
            {sName: 'Glacier', buffs: []},
            {sName: 'Heartrending Strike', buffs: ['Bulwark', 'Finesse']},
            {sName: 'Ice Vortex', buffs: []},
            {sName: 'Magic Missiles', buffs: []},
            {sName: 'Meteor', buffs: []},
            {sName: 'On Guard', buffs: ['Bulwark', 'Form']},
            {sName: 'Quick Strike', buffs: ['Form', 'Haste']},
            {sName: 'Sharp Spear', buffs: ['Haste', 'Form']},
            {sName: 'Spear Trap', buffs: ['Form']},
            {sName: 'Subdue', buffs: []},
            {sName: 'Sugar Rush', buffs: []},
            {sName: 'Summon Helper Elves', buffs: []},
            {sName: 'Titans Cleaver', buffs: ['Finesse']},
        ],
    },
    {
        hero: 'arcaneweaver',
        wArray: [
            {wName: 'Arcane Explosion', buffs: ['Radiance']},
            {wName: 'Arcane Missiles', buffs: ['Radiance']},
            {wName: 'Celestial Retribution', buffs: ['Purity']},
            {wName: 'Fiery Missiles', buffs: []},
            {wName: 'Fire Pillar', buffs: []},
            {wName: 'Frost Beam', buffs: ['IcyVeins']},
            {wName: 'Ice Shield', buffs: []},
            {wName: 'Sacred Orb', buffs: ['Purity']},
        ],
        sArray: [
            {sName: 'Arcane Conjuration', buffs: ['Radiance']},
            {sName: 'Arcane Orb', buffs: ['Finesse', 'Radiance']},
            {sName: 'Arcane shield', buffs: []},
            {sName: 'Arcane Beam', buffs: []},
            {sName: 'Arcane Disc', buffs: ['Radiance']},
            {sName: 'Arcane Power', buffs: []},
            {sName: 'Arcane Sparks', buffs: ['Radiance']},
            {sName: 'Avalanche', buffs: []},
            {sName: 'Blizzard', buffs: []},
            {sName: 'Bloodlust', buffs: []},
            {sName: 'Chaos Bolt', buffs: []},
            {sName: 'Chaotic Explosion', buffs: []},
            {sName: 'Chromatic Bolt', buffs: []},
            {sName: 'Combustion', buffs: []},
            {sName: 'Death Claw', buffs: []},
            {sName: 'Fire bolt', buffs: []},
            {sName: 'Flamethrower', buffs: []},
            {sName: 'Flame Wave', buffs: []},
            {sName: 'Frenzied Bunnies', buffs: []},
            {sName: 'Frost Bolt', buffs: ['IcyVeins']},
            {sName: 'Frost Totem', buffs: []},
            {sName: 'Glacier', buffs: []},
            {sName: 'Holy Beam', buffs: ['Purity', 'Prowess']},
            {sName: 'Ice Vortex', buffs: []},
            {sName: 'Light Beam', buffs: []},
            {sName: 'Living Weapons', buffs: []},
            {sName: 'Magic Missiles', buffs: []},
            {sName: 'Meteor', buffs: []},
            {sName: 'Might', buffs: []},
            {sName: 'Smite', buffs: ['Purity']},
            {sName: 'Summon Chaos Golem', buffs: []},
            {sName: 'Summon Helper Elves', buffs: []},
        ],
    },
    {
        hero: 'sentinel',
        wArray: [
            {wName: 'Cluster Bomb', buffs: []},
            {wName: 'Explosive Arrows', buffs: []},
            {wName: 'Noxious Shot', buffs: ['Aptitude']},
            {wName: 'Obscure Arrow', buffs: ['Aptitude']},
            {wName: 'Rain Of Arrows', buffs: ['Aptitude']},
            {wName: 'Shoot', buffs: ['Aptitude']},
            {wName: 'Venomous Volley', buffs: []},
            {wName: 'Void Trap', buffs: []},
        ],
        sArray: [
            {sName: 'Ricochet Shot', buffs: ['Aptitude']},
            {sName: 'Sniper Shot', buffs: []},
            {sName: 'Split Shot', buffs: ['Aptitude']},
            {sName: 'Acid Rain', buffs: []},
            {sName: 'Avalanche', buffs: []},
            {sName: 'Bladed Chakram', buffs: ['Aptitude']},
            {sName: 'Blizzard', buffs: []},
            {sName: 'Bomb Barrage', buffs: []},
            {sName: 'Camors Arrow', buffs: []},
            {sName: 'Chromatic Bolt', buffs: []},
            {sName: 'Death Vortex', buffs: []},
            {sName: 'Egg Shooter', buffs: []},
            {sName: 'Explosive Trap', buffs: []},
            {sName: 'Frag Shot', buffs: ['Aptitude']},
            {sName: 'Frost Bolt', buffs: ['IcyVeins']},
            {sName: 'Frost Totem', buffs: []},
            {sName: 'Glacier', buffs: []},
            {sName: 'Heartbreak Orbs', buffs: ['Aptitude']},
            {sName: 'Ice Vortex', buffs: []},
            {sName: 'Mine Field', buffs: []},
            {sName: 'Pestilence', buffs: []},
            {sName: 'Poison Bolt', buffs: []},
            {sName: 'Poison Cloud', buffs: []},
            {sName: 'Poison Puddle', buffs: []},
            {sName: 'Shadow Bolt', buffs: ['Aptitude']},
            {sName: 'Shadow orb', buffs: []},
            {sName: 'Shadow Spikes', buffs: []},
            {sName: 'Shrapnel Bomb', buffs: []},
            {sName: 'Spread Shot', buffs: ['Aptitude']},
            {sName: 'Storm Of Arrows', buffs: []},
            {sName: 'Suction Bomb', buffs: []},
            {sName: 'Summon Ballista', buffs: []},
            {sName: 'Summon Helper Elves', buffs: []},
            {sName: 'Surprise Gift', buffs: []},
            {sName: 'Void', buffs: []},
        ],
    },
    {
        hero: 'paladin',
        wArray: [
            {wName: 'Arcane Mace', buffs: ['Radiance']},
            {wName: 'Blades Of Light', buffs: ['Purity', 'Prowess']},
            {wName: 'Fissure Strike', buffs: ['Prowess', 'Resilience']},
            {wName: 'Hammer Of Justice', buffs: ['Purity', 'Finesse']},
            {wName: 'Heroic Strike', buffs: ['Purity', 'Finesse']},
            {wName: 'Holy Fire', buffs: ['Purity']},
            {wName: 'Radiant Light', buffs: ['Prowess', 'Radiance']},
            {wName: 'Staggering Blow', buffs: ['Prowess']},
        ],
        sArray: [
            {sName: 'Beacon Of Light', buffs: ['Purity']},
            {sName: 'Penance', buffs: ['Purity']},
            {sName: 'Templars Verdict', buffs: ['Purity']},
            {sName: 'Arcane Beam', buffs: []},
            {sName: 'Arcane Disc', buffs: ['Radiance']},
            {sName: 'Arcane Power', buffs: []},
            {sName: 'Arcane Sparks', buffs: ['Radiance']},
            {sName: 'Armor Shatter', buffs: ['Prowess']},
            {sName: 'Bladestorm', buffs: []},
            {sName: 'Bloody Saw', buffs: ['Finesse']},
            {sName: 'Body Slam', buffs: ['Prowess']},
            {sName: 'Chain Lightning', buffs: ['Electrified']},
            {sName: 'Chromatic Bolt', buffs: []},
            {sName: 'Double Slash', buffs: ['Bulwark', 'Finesse']},
            {sName: 'Ground Break', buffs: ['Prowess']},
            {sName: 'Heartrending Strike', buffs: ['Bulwark', 'Finesse']},
            {sName: 'Holy Beam', buffs: ['Purity', 'Prowess']},
            {sName: 'Light Beam', buffs: []},
            {sName: 'Lightning bolt', buffs: ['Electrified']},
            {sName: 'Lightning Surge', buffs: []},
            {sName: 'Living Weapons', buffs: []},
            {sName: 'Magic Missiles', buffs: []},
            {sName: 'Might', buffs: []},
            {sName: 'Power Conductor', buffs: ['Electrified']},
            {sName: 'Resonant Slam', buffs: ['Prowess', 'Resilience']},
            {sName: 'Seismic Shock', buffs: ['Prowess', 'Resilience']},
            {sName: 'Smite', buffs: ['Purity']},
            {sName: 'Subdue', buffs: []},
            {sName: 'Thunder strike', buffs: ['Electrified']},
            {sName: 'Titans Cleaver', buffs: ['Finesse']},
        ],
    },
    {
        hero: 'chaoswalker',
        wArray: [
            {wName: 'Chaotic Missile', buffs: []},
            {wName: 'Corrosion', buffs: []},
            {wName: 'Infected Shot', buffs: []},
            {wName: 'Orbs Of Destruction', buffs: []},
            {wName: 'Ripple Of Light', buffs: ['Purity']},
            {wName: 'Sanctified Orb', buffs: ['Purity']},
            {wName: 'Unchained Chaos', buffs: []},
            {wName: 'Volcano Eruption', buffs: []},
        ],
        sArray: [
            {sName: 'Chaos Totem', buffs: []},
            {sName: 'Chaos Wave', buffs: []},
            {sName: 'Manifestations Of Chaos', buffs: []},
            {sName: 'Acid Rain', buffs: []},
            {sName: 'Bloodlust', buffs: []},
            {sName: 'Chaos Bolt', buffs: []},
            {sName: 'Chaotic Explosion', buffs: []},
            {sName: 'Chromatic Bolt', buffs: []},
            {sName: 'Combustion', buffs: []},
            {sName: 'Death Claw', buffs: []},
            {sName: 'Death Vortex', buffs: []},
            {sName: 'Fire bolt', buffs: []},
            {sName: 'Flamethrower', buffs: []},
            {sName: 'Flame Wave', buffs: []},
            {sName: 'Frenzied Bunnies', buffs: []},
            {sName: 'Holy Beam', buffs: ['Purity', 'Prowess']},
            {sName: 'Light Beam', buffs: []},
            {sName: 'Living Weapons', buffs: []},
            {sName: 'Meteor', buffs: []},
            {sName: 'Might', buffs: []},
            {sName: 'Pestilence', buffs: []},
            {sName: 'Poison Bolt', buffs: []},
            {sName: 'Poison Cloud', buffs: []},
            {sName: 'Poison Puddle', buffs: []},
            {sName: 'Shadow Bolt', buffs: ['Aptitude']},
            {sName: 'Shadow orb', buffs: []},
            {sName: 'Shadow Spikes', buffs: []},
            {sName: 'Smite', buffs: ['Purity']},
            {sName: 'Summon Chaos Golem', buffs: []},
            {sName: 'Void', buffs: []},
        ],
    },
    {
        hero: 'beastmaster',
        wArray: [
            {wName: 'Brutal Slam', buffs: ['Prowess']},
            {wName: 'Cobra Totem', buffs: []},
            {wName: 'Spider Cocoon', buffs: []},
            {wName: 'Summon Cave Bear', buffs: []},
            {wName: 'Summon Spider Queen', buffs: []},
            {wName: 'Summon Swamp Boar', buffs: []},
            {wName: 'Venomous Strike', buffs: ['Finesse']},
            {wName: 'Wild Strike', buffs: ['Finesse']},
        ],
        sArray: [
            {sName: 'Bestial Wrath', buffs: []},
            {sName: 'Summon Battle Moose', buffs: []},
            {sName: 'Summon War Tiger', buffs: []},
            {sName: 'Acid Rain', buffs: []},
            {sName: 'Armor Shatter', buffs: ['Prowess']},
            {sName: 'Bladestorm', buffs: []},
            {sName: 'Bloody Saw', buffs: ['Finesse']},
            {sName: 'Body Slam', buffs: ['Prowess']},
            {sName: 'Bomb Barrage', buffs: []},
            {sName: 'Chromatic Bolt', buffs: []},
            {sName: 'Combustion', buffs: []},
            {sName: 'Double Slash', buffs: ['Bulwark', 'Finesse']},
            {sName: 'Explosive Trap', buffs: []},
            {sName: 'Fire bolt', buffs: []},
            {sName: 'Flamethrower', buffs: []},
            {sName: 'Flame Wave', buffs: []},
            {sName: 'Ground Break', buffs: ['Prowess']},
            {sName: 'Heartrending Strike', buffs: ['Bulwark', 'Finesse']},
            {sName: 'Meteor', buffs: []},
            {sName: 'Mine Field', buffs: []},
            {sName: 'Pestilence', buffs: []},
            {sName: 'Poison Bolt', buffs: []},
            {sName: 'Poison Cloud', buffs: []},
            {sName: 'Poison Puddle', buffs: []},
            {sName: 'Resonant Slam', buffs: ['Prowess', 'Resilience']},
            {sName: 'Seismic Shock', buffs: ['Prowess', 'Resilience']},
            {sName: 'Shrapnel Bomb', buffs: []},
            {sName: 'Subdue', buffs: []},
            {sName: 'Suction Bomb', buffs: []},
            {sName: 'Surprise Gift', buffs: []},
            {sName: 'Titans Cleaver', buffs: ['Finesse']},
        ],
    },
    {
        hero: 'assassin',
        wArray: [
            {wName: 'Backstab', buffs: ['Finesse', 'Haste']},
            {wName: 'Debilitating Bomb', buffs: []},
            {wName: 'Eviscerate', buffs: ['Form', 'Haste']},
            {wName: 'Fan Of Bombs', buffs: ['Finesse']},
            {wName: 'Reap', buffs: []},
            {wName: 'Shadow Stab', buffs: ['Form']},
            {wName: 'Sinister Strike', buffs: ['Form', 'Haste']},
            {wName: 'Twin Daggers', buffs: ['Finesse', 'Haste']},
        ],
        sArray: [
            {sName: 'Rupture', buffs: ['Form']},
            {sName: 'Shadow Step', buffs: []},
            {sName: 'Smoke Bomb', buffs: []},
            {sName: 'Summon Assassin Enclave', buffs: []},
            {sName: 'Acid Rain', buffs: []},
            {sName: 'Bladestorm', buffs: []},
            {sName: 'Bloody Saw', buffs: ['Finesse']},
            {sName: 'Bomb Barrage', buffs: []},
            {sName: 'Chromatic Bolt', buffs: []},
            {sName: 'Death Vortex', buffs: []},
            {sName: 'Double Slash', buffs: ['Bulwark', 'Finesse']},
            {sName: 'Explosive Trap', buffs: []},
            {sName: 'Flurry', buffs: ['Form']},
            {sName: 'Heartrending Strike', buffs: ['Bulwark', 'Finesse']},
            {sName: 'Mine Field', buffs: []},
            {sName: 'On Guard', buffs: ['Bulwark', 'Form']},
            {sName: 'Pestilence', buffs: []},
            {sName: 'Poison Bolt', buffs: []},
            {sName: 'Poison Cloud', buffs: []},
            {sName: 'Poison Puddle', buffs: []},
            {sName: 'Quick Strike', buffs: ['Form', 'Haste']},
            {sName: 'Shadow Bolt', buffs: ['Aptitude']},
            {sName: 'Shadow orb', buffs: []},
            {sName: 'Shadow Spikes', buffs: []},
            {sName: 'Sharp Spear', buffs: ['Haste', 'Form']},
            {sName: 'Shrapnel Bomb', buffs: []},
            {sName: 'Spear Trap', buffs: ['Form']},
            {sName: 'Subdue', buffs: []},
            {sName: 'Suction Bomb', buffs: []},
            {sName: 'Sugar Rush', buffs: []},
            {sName: 'Surprise Gift', buffs: []},
            {sName: 'Titans Cleaver', buffs: ['Finesse']},
            {sName: 'Void', buffs: []},
        ],
    },
    {
        hero: 'elementalist',
        wArray: [
            {wName: 'Call Lightning', buffs: ['Electrified']},
            {wName: 'Contaminated Cut', buffs: []},
            {wName: 'Freezing Blow', buffs: ['IcyVeins']},
            {wName: 'Heat Explosion', buffs: []},
            {wName: 'Lightning Beam', buffs: []},
            {wName: 'Outbreak', buffs: []},
            {wName: 'Ray Of Fire', buffs: ['Haste']},
            {wName: 'Severe Cold', buffs: []},
        ],
        sArray: [
            {sName: 'Frozen Warhammer', buffs: ['Prowess', 'IcyVeins']},
            {sName: 'Lava Shield', buffs: []},
            {sName: 'Tornado', buffs: ['Electrified']},
            {sName: 'Acid Rain', buffs: []},
            {sName: 'Avalanche', buffs: []},
            {sName: 'Blizzard', buffs: []},
            {sName: 'Chain Lightning', buffs: ['Electrified']},
            {sName: 'Chromatic Bolt', buffs: []},
            {sName: 'Combustion', buffs: []},
            {sName: 'Earth bolt', buffs: ['Colossal']},
            {sName: 'Earthquake', buffs: ['Colossal']},
            {sName: 'Earth Shield', buffs: ['Resilience']},
            {sName: 'Fire bolt', buffs: []},
            {sName: 'Flamethrower', buffs: []},
            {sName: 'Flame Wave', buffs: []},
            {sName: 'Frost Bolt', buffs: ['IcyVeins']},
            {sName: 'Frost Totem', buffs: []},
            {sName: 'Glacier', buffs: []},
            {sName: 'Ice Vortex', buffs: []},
            {sName: 'Lightning bolt', buffs: ['Electrified']},
            {sName: 'Lightning Surge', buffs: []},
            {sName: 'Meteor', buffs: []},
            {sName: 'Pestilence', buffs: []},
            {sName: 'Poison Bolt', buffs: []},
            {sName: 'Poison Cloud', buffs: []},
            {sName: 'Poison Puddle', buffs: []},
            {sName: 'Power Conductor', buffs: ['Electrified']},
            {sName: 'Rolling Boulder', buffs: []},
            {sName: 'Shockwave Totem', buffs: []},
            {sName: 'Summon Helper Elves', buffs: []},
            {sName: 'Thunder strike', buffs: ['Electrified']},
        ],
    },
    {
        hero: 'legionnaire',
        wArray: [
            {wName: 'Corrosive Spear', buffs: ['Vigor']},
            {wName: 'Incinerating Spear', buffs: ['Form']},
            {wName: 'Jupiters Spear', buffs: ['Electrified']},
            {wName: 'Piercing Flames', buffs: []},
            {wName: 'Purging Slam', buffs: ['Vigor']},
            {wName: 'Shield Bash', buffs: ['Form']},
            {wName: 'Summon Infantry', buffs: []},
            {wName: 'Thrust', buffs: ['Form', 'Resilience']},
        ],
        sArray: [
            {sName: 'Intimidating Shout', buffs: []},
            {sName: 'Shield Wall', buffs: []},
            {sName: 'Storm Of Spears', buffs: []},
            {sName: 'Acid Rain', buffs: []},
            {sName: 'Bloodlust', buffs: []},
            {sName: 'Chain Lightning', buffs: ['Electrified']},
            {sName: 'Chaos Bolt', buffs: []},
            {sName: 'Chaotic Explosion', buffs: []},
            {sName: 'Chromatic Bolt', buffs: []},
            {sName: 'Combustion', buffs: []},
            {sName: 'Death Claw', buffs: []},
            {sName: 'Fire bolt', buffs: []},
            {sName: 'Flamethrower', buffs: []},
            {sName: 'Flame Wave', buffs: []},
            {sName: 'Flurry', buffs: ['Form']},
            {sName: 'Frenzied Bunnies', buffs: []},
            {sName: 'Lightning bolt', buffs: ['Electrified']},
            {sName: 'Lightning Surge', buffs: []},
            {sName: 'Meteor', buffs: []},
            {sName: 'On Guard', buffs: ['Bulwark', 'Form']},
            {sName: 'Pestilence', buffs: []},
            {sName: 'Poison Bolt', buffs: []},
            {sName: 'Poison Cloud', buffs: []},
            {sName: 'Poison Puddle', buffs: []},
            {sName: 'Power Conductor', buffs: ['Electrified']},
            {sName: 'Quick Strike', buffs: ['Form', 'Haste']},
            {sName: 'Sharp Spear', buffs: ['Haste', 'Form']},
            {sName: 'Spear Trap', buffs: ['Form']},
            {sName: 'Sugar Rush', buffs: []},
            {sName: 'Summon Chaos Golem', buffs: []},
            {sName: 'Thunder strike', buffs: ['Electrified']},
        ],
    },
    {
        hero: 'necromancer',
        wArray: [
            {wName: 'Carrion Crows', buffs: []},
            {wName: 'Murder Of Crows', buffs: []},
            {wName: 'Putrefy', buffs: []},
            {wName: 'Shadow Nova', buffs: []},
            {wName: 'Soul Release', buffs: ['Radiance']},
            {wName: 'Spectral Guardian', buffs: ['Radiance']},
            {wName: 'Summon Plague Rats', buffs: []},
            {wName: 'Summon Skeletal Warrior', buffs: []},
        ],
        sArray: [
            {sName: 'Summon Putrid Hounds', buffs: []},
            {sName: 'Summon Skeletal Archer', buffs: []},
            {sName: 'Summon Skeletal Mage', buffs: []},
            {sName: 'Acid Rain', buffs: []},
            {sName: 'Arcane Beam', buffs: []},
            {sName: 'Arcane Disc', buffs: ['Radiance']},
            {sName: 'Arcane Power', buffs: []},
            {sName: 'Arcane Sparks', buffs: ['Radiance']},
            {sName: 'Avalanche', buffs: []},
            {sName: 'Blizzard', buffs: []},
            {sName: 'Bloodlust', buffs: []},
            {sName: 'Chaos Bolt', buffs: []},
            {sName: 'Chaotic Explosion', buffs: []},
            {sName: 'Chromatic Bolt', buffs: []},
            {sName: 'Death Claw', buffs: []},
            {sName: 'Death Vortex', buffs: []},
            {sName: 'Frenzied Bunnies', buffs: []},
            {sName: 'Frost Bolt', buffs: ['IcyVeins']},
            {sName: 'Frost Totem', buffs: []},
            {sName: 'Glacier', buffs: []},
            {sName: 'Ice Vortex', buffs: []},
            {sName: 'Magic Missiles', buffs: []},
            {sName: 'Pestilence', buffs: []},
            {sName: 'Poison Bolt', buffs: []},
            {sName: 'Poison Cloud', buffs: []},
            {sName: 'Poison Puddle', buffs: []},
            {sName: 'Shadow Bolt', buffs: ['Aptitude']},
            {sName: 'Shadow orb', buffs: []},
            {sName: 'Shadow Spikes', buffs: []},
            {sName: 'Summon Chaos Golem', buffs: []},
            {sName: 'Summon Helper Elves', buffs: []},
            {sName: 'Void', buffs: []},
        ],
    },
    {
        hero: 'deathknight',
        wArray: [
            {wName: 'Carnage', buffs: ['Bulwark', 'Finesse']},
            {wName: 'Festering Strike', buffs: []},
            {wName: 'Frost Strike', buffs: ['IcyVeins']},
            {wName: 'Glacial Affinity', buffs: []},
            {wName: 'Lethal Blade', buffs: []},
            {wName: 'Obliterate', buffs: ['Finesse']},
            {wName: 'Ravaging Strike', buffs: ['Bulwark', 'Finesse']},
            {wName: 'Ray Of Doom', buffs: []},
        ],
        sArray: [
            {sName: 'Contagion', buffs: []},
            {sName: 'Path Of Decay', buffs: []},
            {sName: 'Shadow Grasp', buffs: []},
            {sName: 'Acid Rain', buffs: []},
            {sName: 'Armor Shatter', buffs: ['Prowess']},
            {sName: 'Avalanche', buffs: []},
            {sName: 'Bladestorm', buffs: []},
            {sName: 'Blizzard', buffs: []},
            {sName: 'Bloody Saw', buffs: ['Finesse']},
            {sName: 'Body Slam', buffs: ['Prowess']},
            {sName: 'Chromatic Bolt', buffs: []},
            {sName: 'Death Vortex', buffs: []},
            {sName: 'Double Slash', buffs: ['Bulwark', 'Finesse']},
            {sName: 'Frost Bolt', buffs: ['IcyVeins']},
            {sName: 'Frost Totem', buffs: []},
            {sName: 'Glacier', buffs: []},
            {sName: 'Ground Break', buffs: ['Prowess']},
            {sName: 'Heartrending Strike', buffs: ['Bulwark', 'Finesse']},
            {sName: 'Ice Vortex', buffs: []},
            {sName: 'Pestilence', buffs: []},
            {sName: 'Poison Bolt', buffs: []},
            {sName: 'Poison Cloud', buffs: []},
            {sName: 'Poison Puddle', buffs: []},
            {sName: 'Resonant Slam', buffs: ['Prowess', 'Resilience']},
            {sName: 'Seismic Shock', buffs: ['Prowess', 'Resilience']},
            {sName: 'Shadow Bolt', buffs: ['Aptitude']},
            {sName: 'Shadow orb', buffs: []},
            {sName: 'Shadow Spikes', buffs: []},
            {sName: 'Subdue', buffs: []},
            {sName: 'Summon Helper Elves', buffs: []},
            {sName: 'Titans Cleaver', buffs: ['Finesse']},
            {sName: 'Void', buffs: []},
        ],
    },
    {
        hero: 'monkeyking',
        wArray: [
            {wName: 'Fracturing Blow', buffs: ['Colossal']},
            {wName: 'Gunpowder Strike', buffs: []},
            {wName: 'Massive Slam', buffs: ['Prowess']},
            {wName: 'Nimbus Lightning', buffs: ['Electrified']},
            {wName: 'Rock Crushing', buffs: ['Colossal', 'Resilience']},
            {wName: 'Spinning Staff', buffs: ['Prowess']},
            {wName: 'Tempestuous Slash', buffs: ['Electrified', 'Form']},
            {wName: 'Trickster Decoy', buffs: []},
        ],
        sArray: [
            {sName: 'Electric Strike', buffs: ['Electrified']},
            {sName: 'Expansive Throw', buffs: ['Prowess']},
            {sName: 'Whirling Defense', buffs: ['Prowess', 'Resilience']},
            {sName: 'Armor Shatter', buffs: ['Prowess']},
            {sName: 'Body Slam', buffs: ['Prowess']},
            {sName: 'Bomb Barrage', buffs: []},
            {sName: 'Chain Lightning', buffs: ['Electrified']},
            {sName: 'Chromatic Bolt', buffs: []},
            {sName: 'Earth bolt', buffs: ['Colossal']},
            {sName: 'Earthquake', buffs: ['Colossal']},
            {sName: 'Earth Shield', buffs: ['Resilience']},
            {sName: 'Explosive Trap', buffs: []},
            {sName: 'Ground Break', buffs: ['Prowess']},
            {sName: 'Holy Beam', buffs: ['Purity', 'Prowess']},
            {sName: 'Light Beam', buffs: []},
            {sName: 'Lightning bolt', buffs: ['Electrified']},
            {sName: 'Lightning Surge', buffs: []},
            {sName: 'Living Weapons', buffs: []},
            {sName: 'Might', buffs: []},
            {sName: 'Mine Field', buffs: []},
            {sName: 'Power Conductor', buffs: ['Electrified']},
            {sName: 'Resonant Slam', buffs: ['Prowess', 'Resilience']},
            {sName: 'Rolling Boulder', buffs: []},
            {sName: 'Seismic Shock', buffs: ['Prowess', 'Resilience']},
            {sName: 'Shockwave Totem', buffs: []},
            {sName: 'Shrapnel Bomb', buffs: []},
            {sName: 'Smite', buffs: ['Purity']},
            {sName: 'Suction Bomb', buffs: []},
            {sName: 'Surprise Gift', buffs: []},
            {sName: 'Thunder strike', buffs: ['Electrified']},
        ],
    },
    {
        hero: 'engineer',
        wArray: [
            {wName: 'Burst Of Lead', buffs: ['Aptitude']},
            {wName: 'Energizer', buffs: ['Electrified']},
            {wName: 'EZ Mechanical Spider', buffs: ['Ammunition']},
            {wName: 'EZ Sentry', buffs: ['Ammunition']},
            {wName: 'Guided Missiles', buffs: ['Aptitude']},
            {wName: 'Power Generator', buffs: ['Electrified']},
            {wName: 'QT Bombuddy 1000', buffs: []},
            {wName: 'QT Land Surprise', buffs: []},
        ],
        sArray: [
            {sName: 'Ammo Box', buffs: ['Ammunition']},
            {sName: 'Heavy Artillery', buffs: []},
            {sName: 'Portable Nuke', buffs: []},
            {sName: 'Bladed Chakram', buffs: ['Aptitude']},
            {sName: 'Bomb Barrage', buffs: []},
            {sName: 'Camors Arrow', buffs: []},
            {sName: 'Chain Lightning', buffs: ['Electrified']},
            {sName: 'Chromatic Bolt', buffs: []},
            {sName: 'Earth bolt', buffs: ['Colossal']},
            {sName: 'Earthquake', buffs: ['Colossal']},
            {sName: 'Earth Shield', buffs: ['Resilience']},
            {sName: 'Egg Shooter', buffs: []},
            {sName: 'Explosive Shot', buffs: ['Ammunition']},
            {sName: 'Explosive Trap', buffs: []},
            {sName: 'Frag Shot', buffs: ['Aptitude']},
            {sName: 'Heartbreak Orbs', buffs: ['Aptitude']},
            {sName: 'Lightning bolt', buffs: ['Electrified']},
            {sName: 'Lightning Surge', buffs: []},
            {sName: 'Mine Field', buffs: []},
            {sName: 'Napalm Blast', buffs: ['Ammunition']},
            {sName: 'Power Conductor', buffs: ['Electrified']},
            {sName: 'Rapid Barrage', buffs: ['Ammunition']},
            {sName: 'Rolling Boulder', buffs: []},
            {sName: 'Shockwave Totem', buffs: []},
            {sName: 'Shrapnel Bomb', buffs: []},
            {sName: 'Shrapnel Shot', buffs: ['Ammunition']},
            {sName: 'Spread Shot', buffs: ['Aptitude']},
            {sName: 'Storm Of Arrows', buffs: []},
            {sName: 'Suction Bomb', buffs: []},
            {sName: 'Summon Ballista', buffs: []},
            {sName: 'Surprise Gift', buffs: []},
            {sName: 'Thunder strike', buffs: ['Electrified']},
            {sName: 'Weakening Shot', buffs: ['Ammunition']},
        ],
    },
    {
        hero: 'myrmidon',
        wArray: [
            {wName: 'Abyssal Fissure', buffs: ['Colossal', 'Form']},
            {wName: 'Frozen Shard', buffs: []},
            {wName: 'Fury Of The Depths', buffs: ['Resilience']},
            {wName: 'Glacial Trident', buffs: ['IcyVeins']},
            {wName: 'Holy Frenzy', buffs: ['Purity']},
            {wName: 'Incisive Strike', buffs: []},
            {wName: 'Sanctified Throw', buffs: ['Purity']},
            {wName: 'Tidal Thrust', buffs: ['Form']},
        ],
        sArray: [
            {sName: 'Jawstorm', buffs: ['IcyVeins']},
            {sName: 'Precision Wave', buffs: []},
            {sName: 'Sea Current', buffs: ['IcyVeins']},
            {sName: 'Arcane Beam', buffs: []},
            {sName: 'Arcane Disc', buffs: ['Radiance']},
            {sName: 'Arcane Power', buffs: []},
            {sName: 'Arcane Sparks', buffs: ['Radiance']},
            {sName: 'Avalanche', buffs: []},
            {sName: 'Blizzard', buffs: []},
            {sName: 'Chromatic Bolt', buffs: []},
            {sName: 'Earth bolt', buffs: ['Colossal']},
            {sName: 'Earthquake', buffs: ['Colossal']},
            {sName: 'Earth Shield', buffs: ['Resilience']},
            {sName: 'Flurry', buffs: ['Form']},
            {sName: 'Frost Bolt', buffs: ['IcyVeins']},
            {sName: 'Frost Totem', buffs: []},
            {sName: 'Glacier', buffs: []},
            {sName: 'Holy Beam', buffs: ['Purity', 'Prowess']},
            {sName: 'Ice Vortex', buffs: []},
            {sName: 'Light Beam', buffs: []},
            {sName: 'Living Weapons', buffs: []},
            {sName: 'Magic Missiles', buffs: []},
            {sName: 'Might', buffs: []},
            {sName: 'On Guard', buffs: ['Bulwark', 'Form']},
            {sName: 'Quick Strike', buffs: ['Form', 'Haste']},
            {sName: 'Rolling Boulder', buffs: []},
            {sName: 'Sharp Spear', buffs: ['Haste', 'Form']},
            {sName: 'Shockwave Totem', buffs: []},
            {sName: 'Smite', buffs: ['Purity']},
            {sName: 'Spear Trap', buffs: ['Form']},
            {sName: 'Sugar Rush', buffs: []},
            {sName: 'Summon Helper Elves', buffs: []},
        ],
    },
]